### ISSUE TITLE
Modrinth API dependency with Sodium is not set.

### ISSUE THREAD

**Issue by andreinonea** [comp500/Indium#102]
Hi!

Could you please update the dependencies for the Indium release with the corresponding Sodium releases? It helps in automation tasks and not necessarily only that.

For me, I tried to use the Modrinth API to automate downloading a bunch of mods but I ended up getting incompatible versions of Indium/Sodium at run-time. The dependency is specified in the title of the Version, but not in the appropriate "dependencies" field, which would be more helpful :).

Thank you!

**Comment by comp500** [comment]
I don't think this is possible from the Modrinth frontend yet, only the backend implements dependencies currently.

**Comment by andreinonea** [comment]
I see. That's unfortunate. I looked at several other mods and it seems that most of them don't have the dependencies set either. Modrinth provides a easy-to-use REST API which can be easily scripted with Python, but it's still in beta, I guess. Anyway, thank you for your time!

**Comment by comp500** [comment]
The redesign that was just released adds this to the frontend, so I've added dependency metadata to all the files!

**Comment by YoshiRulz** [comment]
Could you also add the Fabric API? Sodium embeds the parts it needs, so it's not a transitive dep.
