### ISSUE TITLE
Does Indium's latest release still work on 1.18.1?

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [comp500/Indium#108]
Heya, i saw that Indium has a 1.18.2 build and that it doesn't run on 1.18.1, but is there any version specific code preventing that from happening? As many mods still use 1.18.1 so it would be useful if i could build the jar for 1.18.1

**Comment by comp500** [comment]
You can still use the 1.18.1 alpha builds of Sodium and Indium, as long as you use the right versions (i.e. Indium 1.0.2-alpha3 with Sodium 0.4.0-alpha6). These are both published on Modrinth, CurseForge and Github.

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Ah okay then, thanks!
