### ISSUE TITLE
entering nether crashes game

### ISSUE THREAD

**Issue by Akane-N** [comp500/Indium#109]
hello, every time I enter the nether with this mod (and the continuity mod which is why I need indium) installed everything goes black and I cant do anything in game, I'll try to save and quit game which then freezes it on the saving world screen and the only way to exit Minecraft completely is to restart my computer, which is also why I cant even get a crash report for it, I have other mods installed but I tested each one, one at a time as I added them to my modpack and its only when I added  the indium and continuity mods this problem happens, anyone else having this issue or know what's causing it?

**Comment by comp500** [comment]
Could you send the latest.log file, in the logs folder next to your mods folder?

**Comment by Akane-N** [comment]
Hello, Unfortunately due to the way I had to shut down my computer everytime to get out of Minecraft it doesn't show up in the latest logs file either, it only showed a previous crash problem I had due to a different mod that has since been removed and the modpack remade without it. It's very strange, I've never experienced a crash like this before, I wish I could give you something more to be more helpful, all I know is it definitely has to do with this mod because it's only when I add it to my pack that the glitch happens.

**Comment by comp500** [comment]
Hmm... could you remove Indium and Continuity and get a latest.log file? Ideally as well hold down `F3 + C` when in a world to generate a crash report, that should have some more information about the versions of mods you have installed and your hardware.

**Comment by Akane-N** [comment]
Yes I can do that, but just to clarify to check I understand what your asking for, I have made a whole new modpack without those two mods in it on the curseforge app, you want me to enter a new world using that modpack and it will create a new latest log file automatically that I can send? Also while in that new world if I press f3 + c that will create a crash report to also send you? Also do you want the latest log from my modpack log folder or Minecraft folder  Sorry I just want to try and be as clear as possible so I'm helpful, because I'm still new to learning this stuff and using mods ^~^

**Comment by comp500** [comment]
Yep that's right. The log should be from your modpack log folder, which is in the folder that opens when you click the "Open Folder" option in the CurseForge app, here:
![image](https://user-images.githubusercontent.com/1138417/161361687-60d79063-5c7f-4743-8ec6-c3a0c31ecc31.png)

**Comment by Akane-N** [comment]
wonderful thankyou! ok I believe this is it, I couldn't get the crash report one to work though unfortunately, but here's the latest log file.
[latest.log](https://github.com/comp500/Indium/files/8401637/latest.log)
.

**Comment by comp500** [comment]
Hmm, could you try entering the nether without Iris, or just with Indium but without Continuity? I think Iris or Sodium themselves are certainly much more likely to be causing such a crash, due to how they interact with the GPU.

**Comment by comp500** [comment]
Closing: I don't think this is an Indium issue (will reopen if author responds)
