### ISSUE TITLE
Lag issue while placing block

### ISSUE THREAD

**Issue by arturek1666** [comp500/Indium#114]
**Minecraft version:** 1.18.2
**Plugin version:** indium-1.0.2+mc1.18.2
**Computer Specs:** 
- AMD Ryzen 9 x3950X 16-Core Processor, 3493MHZ, 16 Core(s), 32 Logical Processor(s)
- 32GB Ram
- GeForce GTX 1070
- Windows 11
- Java 17

**Mod List:**
![image](https://user-images.githubusercontent.com/1558228/162633212-34241d19-b7b6-4d0d-a0f7-9a3d4258a83f.png)

**The Issue:**
The issue is that every time I place a block it lags like crazy, what has been noticed is this:
If I delete Indium issue fixed however than the resource pack I use has black and pink texture for all blocks
If I delete resource pack the blocks are not lagging, the other issue is the resource is Patrix_1.18_128x_addon and because it's paid source I can't share it with is the worse as I am stuck. I had write on resource pack discord to see what is going on. Also I didn't tested other resources but the matrix has multiply modules and the basic one works just the extra make things lag, only when the plugin Indium is installed with is strange.

**Comment by comp500** [comment]
Does the lag still happen when you remove Sodium as well as Indium? What about when you remove just Continuity?

**Comment by arturek1666** [comment]
Iris requires Sodium so I would have to remove Iris as well with it.  However the lag issue disappears by just removing Indium, I do get this tho xD:
![image](https://user-images.githubusercontent.com/1558228/162636707-3f9185df-2770-4326-b3ff-2dad2121bb89.png)
I can confirm that If I enable all my mods but disable continuity the lag issue is gone. 

Sadly without the continuity I have texture issues xD
![image](https://user-images.githubusercontent.com/1558228/162636791-4668ca77-e9f4-4ce8-b214-c50118ef56e5.png)

**Comment by comp500** [comment]
> Iris requires Sodium so I would have to remove Iris as well with it.

Remove Iris as well then :P
Just trying to determine if this still occurs without Indium (i.e. with Indigo); if it does it's very likely to be an issue with Continuity.

**Comment by arturek1666** [comment]
Disabled: 
Indium
Iris
Sodium

And left continuity and it's fine no lag, part from ghost blocks for 2 seconds when placing, I did remove continuity and the ghost effect also disappear.

**Comment by arturek1666** [comment]
Enabled all mods part from Continuity and works fine, but strange that if Indium is enabled with continuity it has stronger issue than without I am a bit confused xD

**Comment by comp500** [comment]
Ah, what happens if you enable everything then go into the Sodium settings (video settings) and enable Always Defer Chunk Updates in the Performance tab? Sodium's default functionality intends to prevent block place/break delay when updating chunks, with the drawback that slow chunk update performance can impact frame times more heavily.

The root of the issue is likely to be more related to your resource pack or Continuity, since those are what cause chunk updating to take a while. (could be due to excessive geometry in your resource pack, or a Continuity bug)

**Comment by arturek1666** [comment]
Update it lag less but there is more invisible blocks and they update late etc. Block placing and destroying is slow.

**Comment by comp500** [comment]
Yeah, that makes sense. This isn't an Indium or Sodium issue, it is an issue with your resource pack or Continuity.
