### ISSUE TITLE
the game crashes when entering a world (dont happend without indium)

### ISSUE THREAD

**Issue by Fefedu973** [comp500/Indium#118]
[lastest.log](https://github.com/comp500/Indium/files/8596306/lastest.log)

**Comment by comp500** [comment]
The crash occurs during rendering of an Enhanced Block Entities model; try updating it?

**Comment by Fefedu973** [comment]
it can't be his it intervenes on all worlds even new ones

**Comment by Fefedu973** [comment]
I also have my crash report
[crash-2022-04-30_08.39.22-client.txt](https://github.com/comp500/Indium/files/8597010/crash-2022-04-30_08.39.22-client.txt)
t

**Comment by comp500** [comment]
That's a completely different crash on a completely different *Minecraft version*. Please try narrowing down the mods you have installed to determine specifically what mods might be causing the crash, and tell me what versions of Minecraft, Sodium and Indium you're even using. Also make sure all your mods are up to date; and note that [Physics Mod is currently incompatible with the latest version of Indium](https://github.com/haubna/PhysicsMod/issues/330).

**Comment by Fefedu973** [comment]
weird because it's the correct crash report normally but it's good I found the culprit it's physics mod weird because on curseforge they indicate that it's compatible 
Tank you very much

**Comment by srnyx** [comment]
@Fefedu973 @comp500 It only occurs on the latest version of Indium (1.0.3), if you go back a version (1.0.2), it works fine.

**Comment by Fefedu973** [comment]
yes i saw thank you very much  ☺️

**Comment by srnyx** [comment]
> yes i saw thank you very much ☺️

Oh, comp500 said that, sorry... (you can delete these 3 comments if you want, comp500)
