### ISSUE TITLE
game crashes on world enter

### ISSUE THREAD

**Issue by janPita** [comp500/Indium#119]
I'm trying to use continuity to get connected textures to work in fabric 1.18.2, so I got Indium. Won't work at all, and crashes when I enter a world. Here's the log: https://pastebin.com/22KpfGLe

Any help is appreciated

**Comment by janPita** [comment]
I just took off every mod besides fabric api, sodium, indium, and continuity, and I'm still having that issue.

**Comment by DragonEggBedrockBreaking** [comment]
Update iris to 1.2.4.

**Comment by janPita** [comment]
Thanks, this fixes it
