### ISSUE TITLE
Rendering issue with indium ( i think ) 

### ISSUE THREAD

**Issue by kingbruh16** [comp500/Indium#121]
The game crashed whilst unexpected error
[latest.log](https://github.com/comp500/Indium/files/8794211/latest.log)

Error: java.util.concurrent.CompletionException: net.minecraft.class_148: Tessellating block in world - Indium Renderer
Exit Code: -1

**Comment by comp500** [comment]
I don't think this is an Indium issue; please test without Sodium and Indium. It looks like one of your mods is setting a null BlockState in the world somewhere, or generating blocks that aren't registered properly.

**Comment by ghost** [comment]
I am also having the same issue. It would be cool if we could figure out how to determine which block(state) from which mod is causing the issues here.

**Comment by ghost** [comment]
Crash report and latest log: https://gist.github.com/Brittank88/3c0a9061c2357808c1cdfa93d5f66261

**Comment by ghost** [comment]
Heads up, this might be a result of Fabric Rendering API's `SpriteFinderImpl`...basically just giving up entirely: https://github.com/PepperCode1/Continuity/issues/120

**Comment by comp500** [comment]
Fixed in Indigo (https://github.com/FabricMC/fabric/commit/c0ae659db23d759a232f17767d080b0ba3f501fa), needs port to Indium; see https://github.com/PepperCode1/Continuity/issues/120#issuecomment-1280003103

**Comment by comp500** [comment]
Oh huh, I never realised this was a fix in the rendering API, not Indigo. I've increased the rendering API dependency version for other reasons anyway; this should be fixed with the Fabric API update.
