### ISSUE TITLE
no 1.19?

### ISSUE THREAD

**Issue by Robertpuggle** [comp500/Indium#123]
**I still see 1.18.2 but not 1.19?**

**Comment by comp500** [comment]
1.19 isn't even a day old, how fast do you expect me to be?? also there's literally already a PR updating it, so clearly I don't need to be reminded that 1.19 exists.

**Comment by seanimusprime** [comment]
> **I still see 1.18.2 but not 1.19?**

https://github.com/IMS212/Indium/tree/1.19.x/main

If you're impatient you're more than welcome to use gradle and build it yourself until it's officially released.

**Comment by Rxflectwtf** [comment]
> 1.19 isn't even a day old, how fast do you expect me to be?? also there's literally already a PR updating it, so clearly I don't need to be reminded that 1.19 exists.

Then when will it be released?
