### ISSUE TITLE
Crash on world join

### ISSUE THREAD

**Issue by condblock** [comp500/Indium#125]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 22. 6. 12. 오후 9:47
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null
	at net.minecraft.class_757.method_3188(class_757.java:1007)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.method_3188(class_757.java:1007)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 1024, 513
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,4,48), Section: (at 0,4,0 in 0,0,3; chunk contains blocks 0,-64,48 to 15,319,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 144809 game time, 106802 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_746.method_3135()" because "this.field_3729.field_1724" is null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Cindustry, VanillaTweaks_r797583.zip, font, Dramatic+Skys+Demo+1.4

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1396712656 bytes (1332 MiB) / 3087007744 bytes (2944 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.21
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: DriverVersion=25.20.100.6577
	Graphics card #1 name: NVIDIA GeForce GTX 1050
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1c8d
	Graphics card #1 versionInfo: DriverVersion=27.21.14.5763
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20211.76
	Virtual memory used (MB): 17317.10
	Swap memory total (MB): 3980.65
	Swap memory used (MB): 89.53
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		alternatecurrent: Alternate Current 1.1.0
		appleskin: AppleSkin 2.4.0+mc1.18.2
		authme: Auth Me 2.2.0
		boostedbrightness: Boosted Brightness 2.1.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.7.0
		caffeineconfig: CaffeineConfig 1.1.0
		cem: Custom Entity Models 0.7.1
		chime: Chime 1.2.1
		citresewn: CIT Resewn 1.0.1+1.18.2
		citresewn-defaults: CIT Resewn: Defaults 1.0.1+1.18.2
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		com_github_llamalad7_mixinextras: MixinExtras 0.0.6
		com_ishland_c2me_libs_: libs 0.2.0+alpha.7.0
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		completeconfig: CompleteConfig 1.0.0
		dcch: DCCH 2.0+1.17
		dynamicfps: Dynamic FPS 2.1.0
		entity_texture_features: Entity Texture Features 2.5.10
		entityculling: EntityCulling-Fabric 1.5.0
		fabric: Fabric API 0.48.0+1.18.2
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.7+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.3+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.2+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.13+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.3+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.10+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.4+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.3+40c91ec860
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.17+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.2+d1027f7d60
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.14+40c91ec860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.14+cca23f9360
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+40c91ec860
		fabricloader: Fabric Loader 0.13.3
		fabricskyboxes: FabricSkyBoxes 0.5.5
		fabrishot: Fabrishot ${version}
		fastopenlinksandfolders: FastOpenResourcePacks 1.1.0
		ferritecore: FerriteCore 4.2.0
		indium: Indium 1.0.3+mc1.18.2
		iris: Iris 1.2.2-build.32
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.1.9
		lazydfu: LazyDFU 0.1.2
		libzoomer: LibZoomer 0.4.2+1.18.2
		lithium: Lithium 0.7.9
		malilib: MaLiLib 0.12.1
		mcpppp: MCPPPP 0.7.0
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.1.0
		nightvisionflashbegone: Night Vision Flash be gone! 1.1.0
		no_fog: No Fog 1.2.1+1.16.5-1.18.2
		okzoomer: Ok Zoomer 5.0.0-beta.6+1.18.2
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_yaml_snakeyaml: snakeyaml 1.30
		quilt_base: Quilt Base API 1.0.0+1.18.2-SNAPSHOT
		quilt_client_command: Quilt Client Command API 1.0.0+1.18.2-SNAPSHOT
		quilt_command: Quilt Command API 1.0.0+1.18.2-SNAPSHOT
		quilt_lifecycle_events: Quilt Lifecycle Events 1.0.0+1.18.2-SNAPSHOT
		quilt_resource_loader: Quilt Resource Loader 1.0.0+1.18.2-SNAPSHOT
		quilt_tags: Quilt Tags API 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-api-base: Quilted Fabric API Base 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-command-api-v1: Quilted Fabric Command API (v1) 2.0.0+1.18.2-SNAPSHOT
		quilted-fabric-lifecycle-events-v1: Quilted Fabric Lifecycle Events (v1) 3.0.0+1.18.2-SNAPSHOT
		quilted-fabric-resource-loader-v0: Quilted Fabric Resource Loader (v0) 1.0.2+1.18.2-SNAPSHOT
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		resolutioncontrol: ResolutionControl+ 3.0.0+1.18
		signtools: Sign Tools 1.0.0
		sodium: Sodium 0.4.1+build.15
		sodium-extra: Sodium Extra 0.4.3
		spark: spark 1.8.14
		spruceui: SpruceUI 3.3.3+1.18
		starlight: Starlight 1.0.2+fabric.89b8d9f
		viafabric: ViaFabric 0.4.6+266-main
		viafabric-mc118: ViaFabric for 1.18 0.4.6+266-main
		viaversion: ViaVersion 4.2.1
		whyamionfire: Why Am I on Fire? 1.1.2
		xaerominimap: Xaero's Minimap 22.7.0
		xaeroworldmap: Xaero's World Map 1.21.2
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050/PCIe/SSE2 GL version 3.2.0 NVIDIA 457.63, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Cindustry, file/VanillaTweaks_r797583.zip, file/font, file/Dramatic+Skys+Demo+1.4
	Current Language: 한국어 (대한민국)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['cond_b'/20, l='ServerLevel[연구소]', x=11.83, y=29.93, z=33.68]]
	Data Packs: vanilla
	World Generation: Stable

**Comment by comp500** [comment]
Does the crash still occur when you remove Sodium and Indium?

**Comment by condblock** [comment]
> Does the crash still occur when you remove Sodium and Indium?

Nope

**Comment by comp500** [comment]
Then this isn't the right issue tracker :P

**Comment by SzczurekYT** [comment]
> Then this isn't the right issue tracker :P

I also have this, where should I report it?
Also why it isn't right issue tracker when removing Indium fixes this?

**Comment by SzczurekYT** [comment]
[crash-2022-06-12_20.48.29-client.txt](https://github.com/comp500/Indium/files/8916502/crash-2022-06-12_20.48.29-client.txt)

**Comment by comp500** [comment]
Sorry, I misread that reply... I'll look into it, not sure what would cause this crash

**Comment by comp500** [comment]
It looks like both of you have Fabric API and Quilted Fabric API (bundled with QSL) installed? I don't think this is supported, just remove Fabric API.

**Comment by SzczurekYT** [comment]
I don't think so, I'm on fabric, not on quilt loader. Fabric API is needed for like half of the mods, so it can't be removed and I didn't downloaded anything quilt realted.
＼(°o°)／

**Comment by comp500** [comment]
Ah, you're both using an unsupported version of Ok Zoomer (5.0.0-beta.6), see [the CurseForge page](https://www.curseforge.com/minecraft/mc-mods/ok-zoomer). Please remove it, or switch to [Quilt loader](https://quiltmc.org/) and [QSL/QFAPI](https://modrinth.com/mod/qsl) and update it.

**Comment by SzczurekYT** [comment]
Oh, didnt't knew that ok zoomer moved to quilt.
I will check that later.

**Comment by SzczurekYT** [comment]
> Ah, you're both using an unsupported version of Ok Zoomer (5.0.0-beta.6), see [the CurseForge page](https://www.curseforge.com/minecraft/mc-mods/ok-zoomer). Please remove it, or switch to [Quilt loader](https://quiltmc.org/) and [QSL/QFAPI](https://modrinth.com/mod/qsl) and update it.

I switched to quilt, updated ok zoomer and removed fabric api, and this didn't help, minecraft also crashed.
[latest.log](https://github.com/comp500/Indium/files/8936229/latest.log)

**Comment by comp500** [comment]
Try updating Iris, you're using an older version.

**Comment by PixelFHD** [comment]
For me, updating Iris seems to have fixed the issue.

**Comment by SzczurekYT** [comment]
> For me, updating Iris seems to have fixed the issue.

For me too.

**Comment by SzczurekYT** [comment]
Thank for the help.
