### ISSUE TITLE
Need a Released version or a compiled version

### ISSUE THREAD

**Issue by AsrielDewitt** [comp500/Indium#13]
Like the title says, I don't know computer enough to compile this on my own, It would be very useful if you have a release version ready

**Comment by DragonEggBedrockBreaking** [comment]
Indium has been officially released for a while now, get it from https://modrinth.com/mod/indium!  
(- comp500)
<details><summary>Original comment</summary>
You can use github actions.

1) click on the 'actions' tab  (between pull requests and projects)
2) search for the top most commit on the master branch (ignore other branches/forks) that has a tick next to it (a red 'x' means the build failed)
3) click on the commit title (e.g. Make gradlew executable (#12))
4) scroll to the bottom
5) click on 'build artifacts'
6) download the .zip file
7) unzip the .zip file
8) the correct file is called indium-1.0.0 (later on the version could be higher) or indium-1.0.0.jar; basically, the one without '-dev', '-sources' or '-sources-dev' at the end
</details>

**Comment by green-stalk** [comment]
I have no idea how to compile stuff either and whenever I click on 'build artifacts' it just gives me a 404, and no zip file

**Comment by DragonEggBedrockBreaking** [comment]
i think you need to be logged in for it to work
idk why

**Comment by IMS212** [comment]
Yes, you need to be logged in to access GitHub actions. Also this mod is probably not released for a reason, like bugs.

**Comment by comp500** [comment]
See above for instructions on how to use the Github Actions builds. I'll be releasing this only when Sodium 1.16.x/next has a released version - releasing before then will only confuse users who try to use Sodium 0.1.0 with it, and cause undue support burden for Jelly and her moderators.

**Comment by WelcomedBison93** [comment]
we need a 1.20.4 and 1.20.5

**Comment by GrinlexGH** [comment]
and 1.20.6
