### ISSUE TITLE
1.18.2 After a single person joins the world, it becomes a saved world crash, and only by uninstalling indium can it load normally

### ISSUE THREAD

**Issue by xujinjie55** [comp500/Indium#133]
1.18.2The version joins the world and then becomes a saved world, and then crashes only uninstalling indium to continue, I don't know what the reason is, hope to help this is the log
[latest.log](https://github.com/comp500/Indium/files/9282605/latest.log)
[rei.log](https://github.com/comp500/Indium/files/9282606/rei.log)
[minecraft-exported-crash-info-2022-08-08T22-39-16.zip](https://github.com/comp500/Indium/files/9282625/minecraft-exported-crash-info-2022-08-08T22-39-16.zip)

**Comment by comp500** [comment]
Try removing DashLoader?

**Comment by xujinjie55** [comment]
The author, I've tried this, and this is still falling apart.

**Comment by xujinjie55** [comment]
> 尝试删除DashLoader？

Author I tried this, but it still collapsed

**Comment by comp500** [comment]
Please send the crash report / log with DashLoader removed.

**Comment by xujinjie55** [comment]
> 请在删除 DashLoader 的情况下发送崩溃报告/日志。
[minecraft-exported-crash-info-2022-08-09T11-51-25.zip](https://github.com/comp500/Indium/files/9286609/minecraft-exported-crash-info-2022-08-09T11-51-25.zip)
[2022-08-08-2.log.gz](https://github.com/comp500/Indium/files/9286612/2022-08-08-2.log.gz)
[latest.log](https://github.com/comp500/Indium/files/9286613/latest.log)
[rei.log](https://github.com/comp500/Indium/files/9286614/rei.log)
Please look

**Comment by comp500** [comment]
Try updating Iris to the latest version for 1.18.2?

**Comment by xujinjie55** [comment]
> 尝试将 Iris 更新到 1.18.2 的最新版本？

Thanks for the success of your reminder thanks for your reminder you can end this thing up

**Comment by xujinjie55** [comment]
The author, I've tried this, and this is still falling apart.



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 9, 2022 01:27 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [comp500/Indium] 1.18.2 After a single person joins the world, itbecomes a saved world crash, and only by uninstalling indium can it loadnormally (Issue #133)




 
Try removing DashLoader?

**Comment by comp500** [comment]
Please send the crash report / log again.
