### ISSUE TITLE
Rendering Issue With 1.19.2

### ISSUE THREAD

**Issue by cora8dale** [comp500/Indium#135]
hi!! my game keeps crashing when i have indium installed, but works fine (albeit with broken textures for a few things) without indium. i apologize for wasting your time if it is one of the other mods i have installed, but i figured i would ask about it here first.
[crash-2022-08-26_15.27.49-client.txt](https://github.com/comp500/Indium/files/9436300/crash-2022-08-26_15.27.49-client.txt)

**Comment by comp500** [comment]
This looks to be a bug with Supplementaries, please report it to their issue tracker.

**Comment by lostopkk** [comment]
> hi!! my game keeps crashing when i have indium installed, but works fine (albeit with broken textures for a few things) without indium. i apologize for wasting your time if it is one of the other mods i have installed, but i figured i would ask about it here first. [crash-2022-08-26_15.27.49-client.txt](https://github.com/comp500/Indium/files/9436300/crash-2022-08-26_15.27.49-client.txt)

update supplementaries newest version
