### ISSUE TITLE
Connected glass looks wierd

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [comp500/Indium#14]
[Connected Block Textures](https://github.com/Nuclearfarts/connected-block-textures) glass looks weird when used with Sodium + Indium. It's difficult to explain, so I use the screenshots. This is the only issue I could not reproduce without Sodium + Indium, all the others were CBT bugs.

Without Indium + Sodium (what it should be like):

![2021-01-27_11 00 55](https://user-images.githubusercontent.com/68545280/105982729-974e1a00-608f-11eb-9484-e4b90b8f395b.png)

With Indium + Sodium (your fork):

<img width="960" alt="javaw_Xh943tZHlv" src="https://user-images.githubusercontent.com/68545280/105982768-a59c3600-608f-11eb-88ea-a164a1e92d62.png">

<img width="960" alt="javaw_scrWJOiLr5" src="https://user-images.githubusercontent.com/68545280/105982774-a9c85380-608f-11eb-95e0-4550732f0ad3.png">

<img width="960" alt="javaw_5feIFREnRH" src="https://user-images.githubusercontent.com/68545280/105982778-ab921700-608f-11eb-9cd1-0d5063970616.png">

**Comment by comp500** [comment]
I do need to implement face culling properly, but this is probably also related to https://github.com/jellysquid3/sodium-fabric/issues/38

**Comment by DragonEggBedrockBreaking** [comment]
Should I close? Should I rename?

**Comment by comp500** [comment]
Leave it for now, I'm interested to see how it changes after I implement face culling.

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> Leave it for now, I'm interested to see how it changes after I implement face culling.

Ok. Remember to comment here so I can test.

**Comment by comp500** [comment]
Ignore me, Indigo does implement face culling further down in the pipeline (I just haven't fed it through to Sodium's more efficient system). I'm pretty sure this is due to that Sodium issue, I'll close this one.
