### ISSUE TITLE
Conflicting information in FAQ

### ISSUE THREAD

**Issue by Fabian42** [comp500/Indium#142]
The [FAQ](https://modrinth.com/mod/indium) mentions both:

> Indium is an addon mod for Sodium

…and also:

> Indigo disables itself when Sodium is installed.

Which one is it? The rest of the FAQ sounds like I should use both Sodium AND Indigo, but this is confusing.

**Comment by comp500** [comment]
Indigo is not Indium - though Indium is adapted from Indigo. Technically when you use Sodium and Indium with Fabric API there are 2 implementations of the Fabric Rendering API installed - both Indium and Indigo (included in Fabric API) - but Indigo is disabled when Sodium is installed, as it is not compatible; Indium is an alternative implementation that works with Sodium.

**Comment by Fabian42** [comment]
Oh, that is confusing naming! Could there maybe be a little hint at that in the FAQ, please?
