### ISSUE TITLE
Minecraft crashed!

### ISSUE THREAD

**Issue by tunaflsh** [comp500/Indium#149]
Minecraft crashed whenever I activated a small contraption with pistons and slime blocks. The crash report said More Culling, Indium and Sodium might be potential causes. After playing around I could reproduce the crash multiple times when there were both ImmediatelyFast mod and More Culling enabled. However now I cannot reproduce the crash anymore. I'm submitting a crash report here anyway https://mclo.gs/2UTSIg1

**Comment by comp500** [comment]
Looks like a duplicate of #146; try disabling DashLoader and/or MoreCulling.

**Comment by comp500** [comment]
Closing: I don't think this is an Indium issue (will reopen if issue is reproduced without aforementioned mods)
