### ISSUE TITLE
Sandwichable RockySalt and SaltyStone cause the 4 chunks its in to not render

### ISSUE THREAD

**Issue by dandin87** [comp500/Indium#15]
While testing AoF3 2.6.0, which re-adds Sandwichable, I found that Sandwichable RockySalt and SaltyStone cause the 4 chunks its in to not render. Landing on the invisable area and breaking a block in creative caused a crash. But I also think it caused a crash just going near one of these areas, as it stopped loading/unloading chunks then eventually crashed. And here is the 4 chunks failing to render https://paste.lucko.me/RSYGxEz5wf, nothing else relevant in the log. And now that I am looking it appears to have not generated a crash report for either of those crashes. Pictures in AoF discord.

**Comment by comp500** [comment]
As discussed in AoF discord: The issue was caused by Sandwichable not registering a block it generates in the world.
