### ISSUE TITLE
Indium vs. Fabric API?

### ISSUE THREAD

**Issue by Eiion** [comp500/Indium#150]
Do I understand it correctly that if Indium is based on Indigo, which is part of the Fabric API, Indium is not needed for instances already including Fabric API in their list of loader mods?
If so, I'd appreciate a better (i.e. more clear) description in the README.md as well as the curseforge mod desscription page.

Young/average users might not fully understand the current description. Adding a "(not needed when using Fabric API)" or "can be used instead of Fabric API" would be quite beneficial to those users not fully aware what Indium is actually about when almost every tutorial out their is telling people they need Fabric API if they're using the Fabric Loader.

Though, I'm honestly not even 100% sure I understood it correctly. So a simplyfied more straight to the point description - at least on the curseforge page - as suggested would be much appreciated.

**Comment by comp500** [comment]
Indium is based on Indigo, but Indigo itself does not support Sodium (and disables itself when Sodium is installed). So you need *both* Fabric API (providing the rendering API) and Indium (implementing the rendering API) when using Sodium with mods that use the rendering API.

**Comment by Eiion** [comment]
Ok. Thanks for clarification.
This answer added to the mod description page would be great! Thanks for considering.
Feel free to close this issue - unless you want to to tag it as Feature Request.
