### ISSUE TITLE
Stay True not working properly 

### ISSUE THREAD

**Issue by Prayzou** [comp500/Indium#151]
![Minecraft_ 1 19 2 24_11_2022 23_33_24](https://user-images.githubusercontent.com/119015949/203870882-9f233ba1-eff6-46fb-9dee-395df53ad791.png)

**Comment by rdrpenguin04** [comment]
What is supposed to happen / what isn't happening?

**Comment by Prayzou** [comment]
Connected texture on the side is not working

**Comment by comp500** [comment]
Which connected textures mod are you using? Does this still occur if you remove Sodium and Indium?

**Comment by Prayzou** [comment]
The mod I'm using is continuity

**Comment by comp500** [comment]
Does this issue still occur if you remove Sodium/Indium/Iris? If it does, report the issue to the Continuity author.

**Comment by comp500** [comment]
Closing: I don't think this is an Indium issue (will reopen if author responds)
