### ISSUE TITLE
Minecraft crashes when loading into the game finishes

### ISSUE THREAD

**Issue by codaah** [comp500/Indium#152]
not when loading into a world, but into the game. i have not enough crashes and it says indium makes the game crash. when i remove it the game works fine but things dont render in applied energistics for example

**Comment by comp500** [comment]
Please send the full crash report, ideally also the latest.log file; otherwise I have no way of diagnosing the issue.

**Comment by comp500** [comment]
Closing: insufficient information provided, unable to replicate issue
