### ISSUE TITLE
Crashing when opening inventory with enchanted item

### ISSUE THREAD

**Issue by 7controversed** [comp500/Indium#156]
The crash occurs when you open your inventory IN SURVIVAL while holding an enchanted item, xp bottle or an enchanted golden apple, in single & multiplayer.
I'm playing with a modpack by the way.

[crash-2022-12-10_15.27.33-client.txt](https://github.com/comp500/Indium/files/10200267/crash-2022-12-10_15.27.33-client.txt)

**Comment by comp500** [comment]
Does the crash still occur when you remove both Indium and Sodium?

**Comment by 7controversed** [comment]
Discovered that it's due to Sodium.
But I have some mod that needs sodium like iris shaders, paradise lost...

In the 1.19.3 version of sodium it's fixed, but we're playing in 1.19.2 cause there is a lot of mods with this version :/

**Comment by comp500** [comment]
It could also be an Iris issue, try updating Iris; see https://github.com/IrisShaders/Iris/issues/1777

**Comment by 7controversed** [comment]
Thank's, it's working perfectly !
