### ISSUE TITLE
Cannot compile, Sodium dependency .xml link does not exist

### ISSUE THREAD

**Issue by ArchitektRadim** [comp500/Indium#16]
https://jitpack.io/com/github/jellysquid3/sodium-fabric/1.16.x~next-SNAPSHOT/maven-metadata.xml timeout, it seems link doesn't exist anymore. Failed to compile.

**Log:**
https://pastebin.com/raw/rcYy0T9N

**Comment by comp500** [comment]
Try again? Jitpack is a bit flaky sometimes, it seems to be working for me now..

**Comment by ArchitektRadim** [comment]
> 
> 
> Try again? Jitpack is a bit flaky sometimes, it seems to be working for me now..

**Comment by ArchitektRadim** [comment]
> 
> 
> Try again? Jitpack is a bit flaky sometimes, it seems to be working for me now..

Ah, yes it seems working now. Didn't know that about Jitpack, thanks!
