### ISSUE TITLE
Crash with supplementaries mod when placing a lantern on a wall. Fabric 1.19.2

### ISSUE THREAD

**Issue by AnomalousDeity** [comp500/Indium#160]
just immediately crashes when placing a lantern on the wall when Indium is installed. and i cant quite take indium out without causing other mods to have issues without it. 

[crash-2022-12-15_12.13.52-client.txt](https://github.com/comp500/Indium/files/10240569/crash-2022-12-15_12.13.52-client.txt)

**Comment by comp500** [comment]
Not an Indium issue, update Supplementaries and Moonlight (see [issue on CF](https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/547))
