### ISSUE TITLE
crashes after a few seconds/a minute in a new world

### ISSUE THREAD

**Issue by Randomly-Neon** [comp500/Indium#163]
[crash-2022-12-28_17.55.48-client.txt](https://github.com/comp500/Indium/files/10315454/crash-2022-12-28_17.55.48-client.txt)
its consistent (every time i load into a previous or a new world), it doesnt happen when indium is not used, i use the 1.0.7 version of indium because i play on 1.19.
(also i am unable to remove iris as both it and indium are needed for some of my texture packs)

**Comment by comp500** [comment]
Can you disable your texture packs and test without Sodium/Indium/Iris? It doesn't seem likely that any of these would directly cause this issue; the crash seems to indicate that another mod is accessing the client's world from the wrong thread. When you test without Sodium, set the "Chunk Builder" option to "Threaded" (as this makes it more likely for you to replicate the issue).

**Comment by comp500** [comment]
Closing: old issue with insufficient information to diagnose
