### ISSUE TITLE
Incompatibility with Sodium 0.4.7

### ISSUE THREAD

**Issue by Owehttamy** [comp500/Indium#165]
Fabric fails to run on startup due to Indium searching for version 0.4.6.

**Comment by TechPro424** [comment]
Please fix

**Comment by TheManchineel** [comment]
Tried doing some quick and dirty JAR file surgery editing the mod manifest but the game still crashes. Guess I'll just wait for a real update from the devs :)

Current Sodium version is 0.4.7+build.21

**Comment by comp500** [comment]
What mods are people actually using on 1.19.3 that require the Fabric Rendering API? I don't think any of the mods I use to test it are even updated!

**Comment by Koekieezz** [comment]
> What mods are people actually using on 1.19.3 that require the Fabric Rendering API? I don't think any of the mods I use to test it are even updated!

i dont really know but these are my mods:
![image](https://user-images.githubusercontent.com/112951868/210141220-8e1b2e37-8e71-4f26-9252-b3f983a9c6de.png)

These are the highlights, since iris 1.5 is releasing at new year (confirmed by IMS itself as the dev of sodium and iris, on iris discord server):
![image](https://user-images.githubusercontent.com/112951868/210141354-f5ff43e1-2aa9-49a0-92df-42fd1f338c77.png)


if you could, please update it to support sodium 0.4.7 :D

**Comment by comp500** [comment]
As far as I can tell, none of those mods need Indium... you can just remove it.

**Comment by autistukral** [comment]
![OBwpHOy0J1](https://user-images.githubusercontent.com/67871935/210150691-b2670113-7a31-4e76-952e-c850df27b0c6.png)
-CIT Resewn, that one still isn't updated to 1.19.3

**Comment by Koekieezz** [comment]
> As far as I can tell, none of those mods need Indium... you can just remove it.

i dont really know what indium is useful at but i would like to use it XD

**Comment by Liyze09** [comment]
Many mod need indium to work with sodium.

**Comment by Liyze09** [comment]
Many mods need indium to work with sodium.

**Comment by Liyze09** [comment]
Action has the new build

**Comment by giorov** [comment]
Iris requires Sodium 0.4.7

**Comment by AlvinKitchens** [comment]
![Screenshot (403)](https://user-images.githubusercontent.com/77103620/210187188-cffb103a-8b0b-4360-8c15-3953e348d6f8.png)
Litematica, minihud, shulkerboxtooltips a few of the mods i use require the fabric api

**Comment by comp500** [comment]
> Litematica, minihud, shulkerboxtooltips a few of the mods i use require the fabric api#

These mods require the Fabric API (not the Fabric *Rendering* API that Indium implements). I still haven't been able to test Indium with an actual use case, since to my knowledge there are no mods released for 1.19.3 that use the Fabric Rendering API.
