### ISSUE TITLE
Crashes when looking around the world or missing textues

### ISSUE THREAD

**Issue by Kamiszewskyy** [comp500/Indium#168]
Hi, so I have random crashes when I look around a world. It also happens when there is liquid from **Hephaestus (Tinker's Port)**. Here is the crash-report:
[crash-2023-01-30_06.57.50-client.txt](https://github.com/comp500/Indium/files/10532920/crash-2023-01-30_06.57.50-client.txt)

I also have problem with textues, but I'm not sure if the problem is due to **Indium**.
![2023-01-30_06 56 22](https://user-images.githubusercontent.com/62818516/215398862-cf71ba61-0932-489b-a191-00e08d40a6f7.png)
![2023-01-30_06 32 38](https://user-images.githubusercontent.com/62818516/215398869-20387d71-92ba-4138-b7a6-cf07b6f634b3.png)

**Comment by comp500** [comment]
I can't seem to replicate this issue, it might be a conflict with another of the mods you have? Try removing DashLoader and/or C2ME.

**Comment by Kamiszewskyy** [comment]
It looks like it was **Colormatic** and removing it or updating to the latest version from modrinth fixes it.
