### ISSUE TITLE
Iris compatibility

### ISSUE THREAD

**Issue by Slainlight** [comp500/Indium#17]
I don't know if this is within the scope of the project, but it would be pretty darn cool.
Iris is a mod that allows shaders to be run in fabric without Optifine and can work with sodium.
using [Iris](https://github.com/IrisShaders/Iris/tree/sodium-compatibility) and [Iris's fork of sodium](https://github.com/IrisShaders/sodium-fabric) there are issues.

I used CTM (connected textures mod) and bits and chisels to test, and CTM didn't connect textures, and bits and chisels crashes the game.

Here's a video of me demonstrating
[youtube link](https://www.youtube.com/watch?v=kUvRGePUA8k&feature=youtu.be)

Here is a 7zip of the mods used:
[google drive link](https://drive.google.com/file/d/1SLtG7v56SlO045oZGvQc1TBQGJnp_IIK/view?usp=sharing)

Minecraft 1.16.5
Fabric 0.11.1
Fabric API 0.30.0

**Comment by comp500** [comment]
If I remember correctly, Iris's fork of Sodium is too old to work with Indium currently. You can merge them yourself (I think someone in the Iris discord has?) but I won't be doing that myself, it's up to coderbot to update the fork.

Note that the outline rendering doesn't require the Fabric Rendering API to work - the game just crashes when Indium tries to render the Bits and Chisels block in the world. CTMF doesn't come with a built in resource pack either, you'll need to download one (such as https://www.curseforge.com/minecraft/texture-packs/mc-connected-ctm) for it to actually do anything.

**Comment by Slainlight** [comment]
![image](https://user-images.githubusercontent.com/18296791/106856950-29e44f80-6674-11eb-8a2c-380cad2ec24c.png)
Well, dang you're right. Thanks for the feedback.

**Comment by Tiebe** [comment]
Is this possible yet?

**Comment by DragonEggBedrockBreaking** [comment]
> If I remember correctly, Iris's fork of Sodium is too old to work with Indium currently. You can merge them yourself (I think someone in the Iris discord has?) but I won't be doing that myself, it's up to coderbot to update the fork.

The fork just got updated btw. https://github.com/IrisShaders/sodium-fabric
