### ISSUE TITLE
Uncompatible with newest version of Iris

### ISSUE THREAD

**Issue by InAgony** [comp500/Indium#177]

**Comment by comp500** [comment]
The newest version of Iris works fine for me, what versions of Sodium / Indium are you using?

**Comment by InAgony** [comment]
Latest version of all

**Comment by comp500** [comment]
How are they incompatible? Do you have a crash report / log you can send, or is some functionality broken?

Just to confirm, the latest versions are Iris 1.5.2, Sodium 0.4.9 and Indium 1.0.14 - are you definitely using these?

**Comment by pholdud-e** [comment]
I had no problems while testing those, works perfectly fine without other specfic mods. @InAgony do you have mod Continuity installed? Version [2.0.1+1.19] of continuity paired with those mods caused startup crashes for me.

**Comment by InAgony** [comment]
I don't have continutity installed, ill send the most recent crash report.

**Comment by comp500** [comment]
As mentioned in https://github.com/comp500/Indium/issues/180 this is not an Indium issue, update your version of Fabric API / QSL.
