### ISSUE TITLE
Directions on how to compile

### ISSUE THREAD

**Issue by Ocraftyone** [comp500/Indium#18]
Would you be able to provide more information on how to compile this. I know that you can use gradlew build but i am unsure how to correctly use the sodium source code with your code

**Comment by ImperatorStorm** [comment]
all you need to do is run `gradlew build` if on windows or `./gradlew build` on mac/linux

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> i am unsure how to correctly use the sodium source code with your code

sodium and this mod are separate mods

you just need to compile the 1.16.x/next branch of sodium (the stable branch/releases won't be enough) and compile this mod seperately, then put both .jar files in your mods folder

**Comment by MacKinzee** [comment]
where is the location of the compiled .jar?

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> where is the location of the compiled .jar?

`build/libs`

**Comment by BobbyGBs** [comment]
Ok I am monkey brain. Is there any way that someone can just send me the jar?

**Comment by comp500** [comment]
Precompiled builds of Indium are available from [Github Actions](https://github.com/comp500/Indium/actions) - just click the latest run then download and extract the build-artifacts file.

**Comment by Minecatr** [comment]
BUILD FAILED in 4s

**Comment by DragonEggBedrockBreaking** [comment]
> BUILD FAILED in 4s

Firstly, this is not specific, and we cannot have any idea what has gone wrong. Many things could have gone wrong, most notably that you need to install a JDK, and that the command is different if you use Windows, or if you use a UNIX-based system (e.g. Linux or MacOS). Secondly, if you do not know how to compile, you can use GitHub Actions.
