### ISSUE TITLE
Crash when joining singleplay / multiplayer world with Physics mod

### ISSUE THREAD

**Issue by hades3729** [comp500/Indium#182]
I want to play with the Physics mod but some other mods require Indium, but when both are enabled at the same time I can't join any world without my game crashing. I reached Physics mod's dev and he told my the issue is coming from Indium, so here I am with the crash report!
[crash-2023-03-19_18.27.28-client.txt](https://github.com/comp500/Indium/files/11011814/crash-2023-03-19_18.27.28-client.txt)

**Comment by comp500** [comment]
You seem to be using an unreleased version of Sodium, that I don't think is compatible with Indium. Only the [official releases](https://modrinth.com/mod/sodium/versions) of Sodium are supported.

**Comment by hades3729** [comment]
Unfortunately the latest version of Physics mod doesn't support Sodium's latest release. Any workaround?

**Comment by comp500** [comment]
I only support released versions of Sodium, you'll have to wait for Physics mod to update.
