### ISSUE TITLE
Crashes when I launch the game

### ISSUE THREAD

**Issue by Solarissss** [comp500/Indium#184]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'indium'!

**Comment by comp500** [comment]
This doesn't tell me anything about why it crashed. Please send the full `logs/latest.log` file or the crash report in the `crash-reports` folder.

**Comment by Solarissss** [comment]
Oh, sorry, here's the crash report:
[crash-2023-03-30_21.40.39-client.txt](https://github.com/comp500/Indium/files/11118207/crash-2023-03-30_21.40.39-client.txt)

**Comment by Solarissss** [comment]
Oh sorry, heres the crash report

[crash-2023-03-30_21.40.39-client.txt](https://github.com/comp500/Indium/files/11118213/crash-2023-03-30_21.40.39-client.txt)

**Comment by comp500** [comment]
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for #citresewn-defaults:citresewn-defaults.mixins.json:types.item.ItemRendererMixin from mod citresewn-defaults

Update CIT Resewn to the latest version for 1.19.4, you're using the 1.19.3 version.

**Comment by Solarissss** [comment]
thank you so much!
