### ISSUE TITLE
BufferBuilder not started (GUI crash / FTB Quests)

### ISSUE THREAD

**Issue by chorbintime** [comp500/Indium#186]
Crash while adding new quests to FTBQuests. No concrete steps to reproduce the issue. Seems to happen when the screen to add an item as a task is opening, but it doesn't happen every time.
https://mclo.gs/rISII5Z
https://mclo.gs/0BptwM1

**Comment by comp500** [comment]
Likely to be the same issue as #166

**Comment by comp500** [comment]
Duplicate of https://github.com/comp500/Indium/issues/166
