### ISSUE TITLE
crashes when opening from launcher

### ISSUE THREAD

**Issue by Solarissss** [comp500/Indium#187]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'indium'!

[crash-2023-04-14_18.45.17-client.txt](https://github.com/comp500/Indium/files/11238032/crash-2023-04-14_18.45.17-client.txt)

**Comment by comp500** [comment]
> Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#eatinganimationid:eatinganimation.mixins.json:ItemRendererMixin from mod eatinganimationid] from phase [DEFAULT] in config [#eatinganimationid:eatinganimation.mixins.json] FAILED during APPLY

Update your version of Eating Animation, the version you currently have installed is not compatible with 1.19.4.

**Comment by Solarissss** [comment]
I did that, now when I open a world it crashes. Is this related?

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null

[crash-2023-04-16_13.17.13-client.txt](https://github.com/comp500/Indium/files/11243309/crash-2023-04-16_13.17.13-client.txt)

**Comment by comp500** [comment]
I don't know, there are too many mods involved in this crash for me to pin down what the issue is. I don't think it's being caused by Indium anyway, try removing some mods.

**Comment by Solarissss** [comment]
Alright, thanks so much

**Comment by comp500** [comment]
Your second crash is likely to be an issue with Cull Leaves, version 3.0.2 is incompatible with Sodium 0.4.9 and newer.
