### ISSUE TITLE
1-0-17 MC1.19.4 Incompat with Physics Mod

### ISSUE THREAD

**Issue by EduardoJauch** [comp500/Indium#191]
Indium keep rendering the "original" block models while Physics Model adds "new".
It looks like you have two blocks one over the other.
E.G. When you open a door, the default model and behaviour happens, but also the Physics Mod model and behavior.

**Comment by comp500** [comment]
Which version of Physics Mod are you using? 3.0.4 added support for Sodium 0.4.11.

**Comment by comp500** [comment]
Please downgrade to Sodium 0.4.10 and Indium 1.0.15.
