### ISSUE TITLE
Sodium 0.4.11 support

### ISSUE THREAD

**Issue by Eianex** [comp500/Indium#192]
Is there a plan to release an Indium version compatible with MC 1.19.4, Sodium 0.4.11, and Iris 1.6.2? It would enable compatibility with mods like continuity, lambda better grass, and the latest physics mod update that fixes snow shadow flickering in complementary reimagined shaders 2.1.

**Comment by comp500** [comment]
Sodium 0.4.11 has been taken down due to various issues, so the corresponding Indium builds have also been taken down. Please downgrade to the previous versions of Sodium; if you absolutely need Indium for this version of Sodium you can compile from source.
