### ISSUE TITLE
Need help building the mod

### ISSUE THREAD

**Issue by Pdam67** [comp500/Indium#198]
I am quite new to minecraft modding so I need help trying to build the mod because it requires sodium.pom or something along those lines.

**Comment by comp500** [comment]
Why do you need to build the mod? If you just want to use Indium, download it from Modrinth: https://modrinth.com/mod/indium

**Comment by Pdam67** [comment]
I just want to access the version of indium for sodium 0.4.11 also it's good to know for other mods aswell.

**Comment by comp500** [comment]
Sodium 0.4.11 and the corresponding Indium release has been taken down due to numerous issues, please downgrade to Sodium 0.4.10 (and versions of mods that support it).

**Comment by Pdam67** [comment]
Thanks for the help
