### ISSUE TITLE
Continuity incompatible with Fabric API 0.81.0+ (Indium 1.0.18+)

### ISSUE THREAD

**Issue by TH3N3WN00B** [comp500/Indium#199]
After updating to latest Indium 1.0.18, some chunks and subchunks started to unload or not fully load all layers

Proofs:

![2023-06-04_08 47 29](https://github.com/comp500/Indium/assets/10799738/a543db24-2c9c-4937-8f67-8e038056432c)
![2023-06-04_08 47 38](https://github.com/comp500/Indium/assets/10799738/689e4f7f-2ee0-4469-9159-7466d0f9150b)

Mod List: (With Fabric Loader 0.14.21)
![image](https://github.com/comp500/Indium/assets/10799738/c27bea54-4eb1-4e03-b532-9a8355536db2)
![image](https://github.com/comp500/Indium/assets/10799738/e40e96db-4bb5-40c0-9cd1-e6befd636afb)

**Comment by comp500** [comment]
Can you send your `latest.log` file from when these errors occurred?

**Comment by TH3N3WN00B** [comment]
> Can you send your `latest.log` file from when these errors occurred?

Sure thing! 

https://paste.gg/p/anonymous/d48c761b58a64c8f831289471e3c24a1

**Comment by comp500** [comment]
This is a problem with Continuity, see https://github.com/PepperCode1/Continuity/issues/253

**Comment by PepperCode1** [comment]
I have just released Continuity 3.0.0-beta.3 for 1.19.3, 1.19.4, and 1.20.1 that have fixed this incompatibility. Note that the 1.19.4 and 1.20.1 versions require Fabric API >=0.86.0, which is currently the latest version.
