### ISSUE TITLE
Crashes upon loading a world when used with sodium and fabric api

### ISSUE THREAD

**Issue by MacKinzee** [comp500/Indium#20]
Gives [this](https://pastebin.com/byycnhsY) error upon crash on Minecraft version 1.16.3. I'm using the precompiled Sodium available on CurseForge and a copy of Iridium I compiled using the source code.

**Comment by Riteo** [comment]
The README says that you should use the latest version of the next branch compiled from source. Have you tried that?

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> The README says that you should use the latest version of the next branch compiled from source. Have you tried that?

They mentioned the precompiled sodium from curseforge, which is *not* the sodium next branch, so you are correct that they need to try that.

**Comment by MacKinzee** [comment]
Success! Mostly... I used the next branch of sodium and the game worked. Unfortunately, it didn't fix why I wanted to use Indium in the first place! Connected textures still don't work with the ctm-for-fabric mod. I'm testing compiling the Connected Block Textures mod right now. As of right now, I'd say this issue is fixed and has turned into a new one for myself.

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> Success! Mostly... I used the next branch of sodium and the game worked. Unfortunately, it didn't fix why I wanted to use Indium in the first place! Connected textures still don't work with the ctm-for-fabric mod. I'm testing compiling the Connected Block Textures mod right now. As of right now, I'd say this issue is fixed and has turned into a new one for myself.

I use CBT and it works fine. ctm-for-fabric requires you to enable smth in-built, but it didnt work for me, but i can confirm that CBT works with indium

**Comment by MacKinzee** [comment]
> I use CBT and it works fine. ctm-for-fabric requires you to enable smth in-built, but it didnt work for me, but i can confirm that CBT works with indium

Yep! It works with cbt. I guess this issue should be closed. For anyone who reads this in the future looking for a solution: READ THE README. Please. And compile it yourself.

**Comment by LafayetteM** [comment]
I've tried this but it doesn't work for me..... Can you please sent me your mod folder so I can try it?
