### ISSUE TITLE
Mod detected as Malware by Windows Security

### ISSUE THREAD

**Issue by RMEngelbrecht** [comp500/Indium#200]
As title says, gave me quite the scare.

This is the latest version I got from Modrinth 

![image](https://github.com/comp500/Indium/assets/5603056/428ba6c9-036f-4eae-8d3a-cb83b3a323cc)

I'm assuming this is just a false positive, but probably worth looking into.

**Comment by CogentRedTester** [comment]
If you're not aware of this yet, might be worth a read: https://github.com/fractureiser-investigation/fractureiser

TLDR: a very dangerous virus has recently been found spreading through minecraft mods, infecting other jars on the system and stealing credentials.

**Comment by comp500** [comment]
This is a false positive - Indium is not infected with the fractureiser virus or any other, and as far as I know Windows Defender is not able to detect fractureiser yet.
