### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'indium'!

### ISSUE THREAD

**Issue by HelpMeFixProblems** [comp500/Indium#203]
I have done everything I could think of to fix this. Here is the Crash Report: 
[crash-2023-06-24_00.19.36-client.txt](https://github.com/comp500/Indium/files/11854591/crash-2023-06-24_00.19.36-client.txt)
Btw I am trying to use 1.20 with these mods.

**Comment by comp500** [comment]
Looks like an issue with MidnightControls, see https://github.com/TeamMidnightDust/MidnightControls/issues/212

**Comment by HelpMeFixProblems** [comment]
I'm not sure what this means. Are there steps I can take to figure this out or fix it?

**Comment by comp500** [comment]
Uh, either remove MidnightControls or wait for the author to fix the issue with it?

**Comment by HelpMeFixProblems** [comment]
Sounds Good, thank you Comp.
