### ISSUE TITLE
Crashing/Random freezing

### ISSUE THREAD

**Issue by majklosik** [comp500/Indium#212]
So i recently updated all my mods to 1.19.4 and now it randomly crashes or freezes while im playing and placing blocks or sum
Error: java.util.concurrent.CompletionException: net.minecraft.class_148: Tessellating block in world - Indium Renderer
Crash report: Pinned
[Crash.txt](https://github.com/comp500/Indium/files/12114578/Crash.txt)
Latest log: Pinned
[latest.log](https://github.com/comp500/Indium/files/12114580/latest.log)

**Comment by majklosik** [comment]
I tried deleting indium i couldnt launch minecraft without it and then i tried to delete c2me and still happening

**Comment by majklosik** [comment]
I just found out that there is already someone who had the same bug about month ago and u said it will be fixed but it still isnt do you know when will u guys fix it ?

**Comment by majklosik** [comment]
And even tho i have about 400 fps atleast the game still lags sometimes. Idk if its the same problem

**Comment by comp500** [comment]
This is not an issue in Indium. See https://github.com/comp500/Indium/issues/199.
