### ISSUE TITLE
Indium doesnt work with quilt

### ISSUE THREAD

**Issue by serfot123** [comp500/Indium#213]
I download quilt, sodium and quilted fanric api and i have error (look at the screenshot) i play in 1 19 4 
![Снимок экрана 2023-07-23 162937](https://github.com/comp500/Indium/assets/140325422/9c13cd20-c481-4ef5-9fc1-2cb82e0925bf)

**Comment by comp500** [comment]
Update your version of Quilted Fabric API / QSL.

**Comment by chrrybmb64** [comment]
I'm having the same problem and I'm already using the latest version of Quilted Fabric API / QSL. The latest version which supports 1.19.4 is QFAPI 6.0.0 Beta 9  / QSL 5.0.0 Beta 10. Every version after that supports 1.20 only.

**Comment by comp500** [comment]
Ah, the problem there is that Fabric API 0.84+ hasn't been released in QFAPI for 1.19.4.

Downgrade Indium to a version that doesn't require Fabric API 0.84, or ask the Quilt devs to backport the newer API changes to 1.19.4.
