### ISSUE TITLE
indium makes vignette stronger

### ISSUE THREAD

**Issue by lucy** [comp500/Indium#214]
With only sodium and fabric api:
![](https://github.com/comp500/Indium/assets/1666345/6e507ba6-962a-40ac-8a10-996f6ab53286)
Adding indium:
![](https://github.com/comp500/Indium/assets/1666345/85f1449c-c2a8-4d76-bac5-5b5000753eeb)

**Comment by comp500** [comment]
I don't see how this would be possible, Indium doesn't touch vignette rendering. Are you absolutely sure there are no differences other than Indium between the instances you took those screenshots in? Could you send the `options.txt` file after running the game each time?

**Comment by lucy** [comment]
It's the exact same fresh default settings instance for each screenshot with no other mods than those listed. `options.txt` is identical after each test run as well. It looks a bit like the vignette texture is being applied twice with indium enabled.

**Comment by comp500** [comment]
The vignette in vanilla takes ~10 seconds to adjust to the environment you're in, so if you'd only just loaded into the world it might not have had time to reset (it starts at full vignette when you load the game).
