### ISSUE TITLE
Smooth Lighting not working with new Sodium

### ISSUE THREAD

**Issue by rainaku** [comp500/Indium#220]
![image](https://github.com/comp500/Indium/assets/129401103/17ca6e06-ad14-481b-bde4-a58ceb0b34bc)

**Comment by iblowmymind** [comment]
Can confirm, was just looking into this. Well, there *is* smooth lighting, but for some reason it's only applied in lines on the X axis and not both horizontal and verically.

**Comment by comp500** [comment]
There were a couple mistakes in porting the ambient occlusion code; this should be fixed fairly soon.
