### ISSUE TITLE
Glowing Ores Texture Glitch

### ISSUE THREAD

**Issue by ItsSunnyMonster** [comp500/Indium#225]
Apologies if this is not the right place to report this issue. 

# To Reproduce
* Install Minecraft 1.20.1, Fabric 0.14.22 (latest at time of writing) and these mods below: (continuity is the mod that is not working properly, but I can confirm that the issue cannot be reproduced when Indium and Sodium are not installed)
<img width="572" alt="image" src="https://github.com/comp500/Indium/assets/100400733/46cd8106-285f-42ac-9068-632e07d17db2">

* Install [this](https://modrinth.com/resourcepack/new-glowing-ores) or [this](https://www.curseforge.com/minecraft/texture-packs/visible-ores) resource pack (there are possibly more that break but these are the only ones I have tested)
* Generate a world and set the time to night time (time does not matter but night time makes the issue easier to see)
* Place ore blocks in this pattern: (there are more orientations that cause this issue)
![image](https://github.com/comp500/Indium/assets/100400733/82afbe87-ce83-4f35-9944-6868a9b99edd)
* Move the camera

## Results
The textures are very glitchy. **This does not happen when sodium and indium are not installed.**

# Extra information
**System:** Macbook Pro M1 with 8-core CPU and 14-core GPU
Please let me know if extra information is needed.

**Comment by comp500** [comment]
Looks like this is https://github.com/PepperCode1/Continuity/issues/292 (not a problem with Indium)
