### ISSUE TITLE
Render distance 1 sub chunck

### ISSUE THREAD

**Issue by PhazeDrop** [comp500/Indium#226]
![image](https://github.com/comp500/Indium/assets/137955267/a5c8a387-a8d7-4009-86a8-b12b0d48c999)

**Comment by PhazeDrop** [comment]
shaders fix it
![](https://cdn.discordapp.com/attachments/929894868854132848/1141101871986122882/image.png)

**Comment by comp500** [comment]
I believe this is a Sodium issue, see https://github.com/CaffeineMC/sodium-fabric/issues/2006
