### ISSUE TITLE
"Tessellating block in world - Indium Renderer" crash when using patrix 32x.

### ISSUE THREAD

**Issue by GamingWithDudeAlt** [comp500/Indium#227]
**Describe the bug**
Basically, the game crashes with the issue "Tessellating block in world - Indium Renderer". This happened when I first placed some black concrete down, and now it's happening when joining the world. I removed Vanadium which fixed it, and I've already reported it to them, but I'm reporting it here too incase it's an issue with Indium instead.

**To Reproduce**
1. Download Patrix 32x resource pack with this mod and vanadium installed.
2. Place some black concrete down (But this could happen with any color of concrete/wool/carpet/terracotta/concrete powder too).
3. Game should crash with "Tessellating block in world - Indium Renderer" in the crash report.

**Expected behavior**
Game wouldn't crash and would be perfectly fine.

**Screenshots**
Screenshots can't describe it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version: 1.20.1
 - Mod Version: 0.1.625

**Additional context**
Crash Report: [crash-2023-09-16_17.20.38-client.txt](https://github.com/theomenden/TheOmenDen.Vanadium/files/12641662/crash-2023-09-16_17.20.38-client.txt)
n/TheOmenDen.Vanadium/files/12641655/latest.log)
txt)
latest.log: [latest.log](https://github.com/theomenden/TheOmenDen.Vanadium/files/12641655/latest.log)
txt)

**Comment by James103** [comment]
See also https://github.com/theomenden/TheOmenDen.Vanadium/issues/39.

**Comment by GamingWithDudeAlt** [comment]
> See also [theomenden/TheOmenDen.Vanadium#39](https://github.com/theomenden/TheOmenDen.Vanadium/issues/39).

Yes that's the one that i reported to them

**Comment by GamingWithDudeAlt** [comment]
> > See also [theomenden/TheOmenDen.Vanadium#39](https://github.com/theomenden/TheOmenDen.Vanadium/issues/39).
> 
> Yes that's the one that i reported to them

Although turns out it's just an issue with vanadium

**Comment by comp500** [comment]
Looks like this isn't a bug in Indium, only Vanadium.
