### ISSUE TITLE
Sodium 0.5.3 support

### ISSUE THREAD

**Issue by vocaloidkiss** [comp500/Indium#228]
Sodium 0.5.3 support

**Comment by NolanHewitt** [comment]
Bro waited 30 mins after Sodium 0.5.3 released and had to post an issue on github.

They supported previous sodium versions same-day, just give them some time, they might be sleeping.

**Comment by vocaloidkiss** [comment]
i am so sorry，my area use GMT+8

**Comment by Zorklis** [comment]
IRIS put out their supported version in an hour (they monitor Sodium's Discord), plus Indium also has big request rate like Iris

**Comment by NoltoxGit** [comment]
Hello @vocaloidkiss,
You can download this [here](https://github.com/NoltoxGit/Indium/releases/download/1.0.26%2Bmc1.20.1/indium-1.0.26+mc1.20.1.jar) !

**Comment by Zorklis** [comment]
@NoltoxGit starts into main menu, crashes loading world
EDIT: Compatible and works with with older version of Fabric API 0.88.1+1.20.1
Crashed because of new (current) version of Fabric API 0.89.0+1.20.1

**Comment by itsarian** [comment]
> Hello @vocaloidkiss, You can download this [here](https://github.com/NoltoxGit/Indium/releases/download/1.0.26%2Bmc1.20.1/indium-1.0.26+mc1.20.1.jar) !

wheres the modrinth release

**Comment by Zorklis** [comment]
> wheres the modrinth release

It's still a PR commit, it hasn't been merged or even approved

**Comment by mindryder** [comment]
**Sodium release 4 days ago**
![Qx320LGCdM](https://github.com/comp500/Indium/assets/66848160/2705e849-9dab-41fd-9cd2-814524d4ba97)
