### ISSUE TITLE
Fabric API 0.89.0+ TerrainRenderContext.hasTransform crash

### ISSUE THREAD

**Issue by Vythal** [comp500/Indium#232]
Bug description: Game crashes whenever trying to render a signpost from Supplementaries.

To reproduce: Use Indium 1.0.25 with Moonlight 2.8.25 and Supplementaries 2.6.1, just load into a world and see how long it takes for it to try and render a signpost, then crash.

Expected behavior: Game not crashing, running fine.

Screenshots: N/A

Desktop OS: Windows 10

Additional context: 
Crash Report: [crash-2023-09-18_14.59.41-client.txt](https://github.com/comp500/Indium/files/12652379/crash-2023-09-18_14.59.41-client.txt)
Latest.log: [latest.log](https://github.com/comp500/Indium/files/12652387/latest.log)

**Comment by 909oce** [comment]
i have the same crash, do you know what caused this? i accidentally pressed update all in my modrinth client without checking which mods had an update. i downgraded sodium/iris back to version that supports indium so it cant be those.

**Comment by 909oce** [comment]
> i have the same crash, do you know what caused this? i accidentally pressed update all in my modrinth client without checking which mods had an update. i downgraded sodium/iris back to version that supports indium so it cant be those.

Update: It's the new Fabric API update causing this crash

**Comment by Cr4fTJuNkiE** [comment]
Was just gonna report the same crash. Mine stalled tesselating a stone block. Was wondering if it was FRAPI.

**Comment by NoltoxGit** [comment]
Hello @Vythal, @909oce & @Cr4fTJuNkiE !

You can download the latest version of Indium compatible with Fabric API `0.89.0` [here](https://github.com/NoltoxGit/Indium/releases/download/1.0.26.1%2Bmc1.20.1/indium-1.0.26-dev+mc1.20.1.jar).
