### ISSUE TITLE
World crashes with a white screen

### ISSUE THREAD

**Issue by lukas27892** [comp500/Indium#234]
https://mclo.gs/Nji4rCI
using 1.20.1
sodium 0.5.2
iris
and indium (obviously)

**Comment by iofloodMichael** [comment]
looks like the exact same issue (and versions) for me as well :(

**Comment by MeeniMc** [comment]
Try downgrading Fabric API from 0.89 to 0.88

**Comment by NoltoxGit** [comment]
Hello @lukas27892 & @iofloodMichael,

You can download the latest version of Indium compatible with Fabric API `0.89.0` [here](https://github.com/NoltoxGit/Indium/releases/download/1.0.26.1%2Bmc1.20.1/indium-1.0.26-dev+mc1.20.1.jar) !

**Comment by comp500** [comment]
Duplicate of #232
