### ISSUE TITLE
Doesn't work on sodium 0.5.3

### ISSUE THREAD

**Issue by anoi1** [comp500/Indium#235]
Doesn't work on sodium 0.5.3 +

**Comment by SorkoPiko** [comment]
Same issue. Hope you will fix soon!

**Comment by mindryder** [comment]
![Qx320LGCdM](https://github.com/comp500/Indium/assets/66848160/8b7f94ab-4508-4001-95b9-cd816d48dfa1)

**Comment by NoltoxGit** [comment]
Hello @anoi1, @SorkoPiko & @mindryder !

You can download the latest version of Indium compatible with Fabric API `0.89.0` [here](https://github.com/NoltoxGit/Indium/releases/download/1.0.26.1%2Bmc1.20.1/indium-1.0.26-dev+mc1.20.1.jar) !

**Comment by BrycensRanch** [comment]
thanks bro u a real one

**Comment by SorkoPiko** [comment]
thanks!
also mods please close :)

**Comment by NoltoxGit** [comment]
> thanks! also mods please close :)

It will be closed when the pull requests are accepted by the developer :)

**Comment by SorkoPiko** [comment]
Didn't realise it hasn't been merged yet, sorry!

**Comment by comp500** [comment]
Duplicate of #228
