### ISSUE TITLE
make version for sodium 0.5.3

### ISSUE THREAD

**Issue by Federkakato** [comp500/Indium#238]
yeah thats it i didnt know where else to put it

**Comment by lolka4toli** [comment]
@Federkakato, have you seen https://github.com/comp500/Indium/pull/231?

**Comment by NoltoxGit** [comment]
Hello @Federkakato !

You can download the latest version of Indium compatible with Fabric API `0.89.0` [here](https://github.com/NoltoxGit/Indium/releases/download/1.0.26.1%2Bmc1.20.1/indium-1.0.26-dev+mc1.20.1.jar) !

**Comment by comp500** [comment]
Duplicate of #228
