### ISSUE TITLE
Crash Whit Sodium 4.10

### ISSUE THREAD

**Issue by ghost** [comp500/Indium#240]
i use the latest version of indium that supports 4.10 here is the mod list 
![image](https://github.com/comp500/Indium/assets/109978642/779f8b32-3908-4551-9828-71ca73493cd8)
here is the crash log
[crash-2023-09-23_12.38.07-client.txt](https://github.com/comp500/Indium/files/12706107/crash-2023-09-23_12.38.07-client.txt)

**Comment by ghost** [comment]
oh also i got xearos minimap 8.1

**Comment by ghost** [comment]
this happens when i log on to server

**Comment by comp500** [comment]
Either downgrade your version of Fabric API (I think 0.88 will work?), or update to the latest versions of Indium and Sodium.

**Comment by ghost** [comment]
> Either downgrade your version of Fabric API (I think 0.88 will work?), or update to the latest versions of Indium and Sodium.

I would upgrade sodium but i cant bc els create fabric would broke but ill downcrade fabric-api
