### ISSUE TITLE
Crash Supplementaries?

### ISSUE THREAD

**Issue by DonorKrovi** [comp500/Indium#241]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-09-23 22:30:26
Description: Tessellating block in world - Indium Renderer

java.lang.IllegalAccessError: 'boolean link.infra.indium.renderer.render.TerrainRenderContext.hasTransform()'
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:54)
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:97)
	at net.mehvahdjukaar.moonlight.api.client.model.CustomBakedModel.emitBlockQuads(CustomBakedModel.java:539)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$bnc000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)

-- Block being tessellated --
Details:
	Block: Block{supplementaries:sign_post}[waterlogged=false]
	Block location: World: (1253,69,2155), Section: (at 5,5,11 in 78,4,134; chunk contains blocks 1248,-64,2144 to 1263,319,2159), Region: (2,4; contains chunks 64,128 to 95,159, blocks 1024,-64,2048 to 1535,319,2559)
Stacktrace:
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$bnc000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Unknown Source)

-- Block being rendered --
Details:
	Block: Block{supplementaries:sign_post}[waterlogged=false]
	Block location: World: (1253,69,2155), Section: (at 5,5,11 in 78,4,134; chunk contains blocks 1248,-64,2144 to 1263,319,2159), Region: (2,4; contains chunks 64,128 to 95,159, blocks 1024,-64,2048 to 1535,319,2559)
	Chunk section: RenderSection at chunk (78, 4, 134) from (1248, 64, 2144) to (1263, 79, 2159)
	Render context volume: class_3341{minX=1246, minY=62, minZ=2142, maxX=1265, maxY=81, maxZ=2161}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Unknown Source)

-- Affected level --
Details:
	All players: 1 total; [class_746['DeZoWaRe'/2303, l='ClientLevel', x=1054.55, y=65.00, z=2034.59]]
	Chunk stats: 862, 862
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,113,-48), Section: (at 0,1,0 in 1,7,-3; chunk contains blocks 16,-64,-48 to 31,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 137184 game time, 137184 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at pro.gravit.launcher.BAtWoRlDststm3.BATwOrlds3vokC(Unknown Source)
	at pro.gravit.launcher.BAtWoRlDststm3.main(Unknown Source)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Moonlight Mods Dynamic Assets

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.6, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), BellSoft
	Memory: 651507064 bytes (621 MiB) / 2506096640 bytes (2390 MiB) up to 4265607168 bytes (4068 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f91
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3734
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3e9b
	Graphics card #1 versionInfo: DriverVersion=27.20.100.8729
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 40840.24
	Virtual memory used (MB): 17011.88
	Swap memory total (MB): 24576.00
	Swap memory used (MB): 559.28
	JVM Flags: 1 total; -XX:+DisableAttachMechanism
	Fabric Mods: 
		appleskin: AppleSkin 2.5.0+mc1.20
			cloth-config: Cloth Config v11 11.0.99
				cloth-basic-math: cloth-basic-math 0.6.1
		architectury: Architectury 9.1.12
		bclib: BCLib 3.0.13
			wunderlib: WunderLib 1.1.5
		betterend: Better End 4.0.10
		betternether: Better Nether 9.0.9
		blockus: Blockus 2.7.6+1.20.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		camerautils: Camera Utils 1.20.1-1.0.5
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da82
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		chat_heads: Chat Heads 0.10.21
		cobblemon: Cobblemon 1.4.0+1.20.1-SNAPSHOT
		cobblemon_tasks: Cobblemon Tasks 1.1.0
		connectivity: Connectivity Mod 1.20.1-4.5
		cosmetic-armor: Cosmetic Armor 1.6.0
		cupboard: cupboard 1.20.1-2.0
		fabric-api: Fabric API 0.89.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.0+0883a8d477
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.22+local
		factions: Factions Mod 2.5.1
		fancymenu: FancyMenu 2.14.9
		farmersdelight: Farmer's Delight 1.20.1-1.4.2
		farsight: Farsight Mod 1.20.1-4.1
			org_jctools_jctools-core: jctools-core 4.0.1
		fdjei: Just Enough Farmer's Recipes 1.0.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		ftblibrary: FTB Library 2001.1.3
		ftbquests: FTB Quests 2001.1.4
			team_reborn_energy: Energy 3.0.0
		ftbteams: FTB Teams 2001.1.4
		ftbxmodcompat: FTB XMod Compat 2.0.1
		gpumemleakfix: Gpu memory leak fix mod 1.20.1-1.7
		hdskinsupport: HD Skins Support 1.0.0
		immersive_paintings: Immersive Paintings 0.6.6+1.20.1
		indium: Indium 1.0.25+mc1.20.1
		iris: Iris 1.6.8
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemfilters: Item Filters 2001.1.0-build.55
		jade: Jade 11.6.0
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.27
		konkrete: Konkrete 1.6.1
		lazydfu: LazyDFU 0.1.3
		litematica: Litematica 0.15.3
		malilib: MaLiLib 0.16.2
		mca: Minecraft Comes Alive 7.5.8+1.20.1
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.7.2+mc1.20.1
		moonlight: Moonlight 1.20-2.8.28
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-rc.3
		openpartiesandclaims: Open Parties and Claims 0.19.3
		recipeessentials: recipeessentials Mod 1.20.1-2.0
		regions_unexplored: Regions Unexplored 0.5.2+1.20.1
			completeconfig-base: completeconfig-base 2.4.1
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.4.1
		sodium: Sodium 0.5.2
		supplementaries: Supplementaries 1.20-2.6.2
		terrablender: TerraBlender 3.0.0.169
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		toms_storage: Tom's Simple Storage Mod 1.6.4
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.4
		trinkets: Trinkets 3.7.1
		xaerominimap: Xaero's Minimap 23.8.0
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 537.34, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, Moonlight Mods Dynamic Assets
	Current Language: ru_ru
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz

**Comment by comp500** [comment]
Update to the latest version of Indium.
