### ISSUE TITLE
Quilt Error

### ISSUE THREAD

**Issue by SorkoPiko** [comp500/Indium#242]
![image](https://github.com/comp500/Indium/assets/36188446/96c779cb-0efa-4467-84ef-c436e8f95e54)
I'm getting this error when launching on Quilt. Does QFAPI need to update, or is this an Indium issue?

**Comment by a-fan9823** [comment]
Same issue

**Comment by a-fan9823** [comment]
pretty sure its QFAPI that needs to update cus its an outdated rendering dependency

**Comment by comp500** [comment]
QFAPI needs to be updated to incorporate the changes from Fabric API 0.89.0.

**Comment by a-fan9823** [comment]
https://github.com/comp500/Indium/releases/tag/1.0.27%2Bmc1.20.1

**Comment by a-fan9823** [comment]
he just pushed an update

**Comment by a-fan9823** [comment]
the only problem is its not on modrinth yet but thats modrinths problem

**Comment by a-fan9823** [comment]
annnd it still decides to not work, I'm gonna go out and say this is quilt's problem here

**Comment by a-fan9823** [comment]
![image](https://github.com/comp500/Indium/assets/137985347/b102ea01-6acc-458e-aa0e-a9dab7015efb)

**Comment by Omay238** [comment]
The PR was merged last night. You can download it from the actions tab, or go to [this](https://github.com/QuiltMC/quilted-fabric-api/suites/16496602619/artifacts/942494108) url. It is a zip, so go into `/build/libs/quilted-fabric-api-7.2.2+0.89.0-1.20.1` after extracting. It hasn't been uploaded to Modrinth yet, but it should be soon.

**Comment by Poopooracoocoo** [comment]
Official release is here! 
[[1.20.1] QFAPI 7.3.0 and QSL 6.1.2](https://modrinth.com/mod/qsl/version/Ycmh3qg8)
