### ISSUE TITLE
Crashes when loading create blocks

### ISSUE THREAD

**Issue by cootshk** [comp500/Indium#243]
https://mclo.gs/kL42jPZ crash report
i made a creative world, placed an andesite casing, and it crashed

**Comment by cootshk** [comment]
using the latest version for sodium v4, v5 is incompatible with create

**Comment by Poopooracoocoo** [comment]
Does downgrading to [Fabric API 0.88.1](https://modrinth.com/mod/fabric-api/version/0.88.1+1.20.1) fix this?

**Comment by markusonnela** [comment]
Downgrading to Fabric API 0.88.1 worked for me.
Had the same problem, many transparent Create blocks (glass trapdoor, copycat panel...) would crash the game.

Current versions in use:
Fabric API 0.88.1
Create 0.5.1.d
Sodium 0.4.10
Indium 1.0.21

**Comment by comp500** [comment]
Closing (Indium 1.0.21 is incompatible with Fabric API 0.89+)
