### ISSUE TITLE
Edit title and changelog of Indium 1.0.21 release on Modrinth and CurseForge to show FAPI 0.88.1 requirement

### ISSUE THREAD

**Issue by Poopooracoocoo** [comp500/Indium#247]
I'd appreciate it if you could edit the changelog and title of the Indium 1.0.21 for Minecraft 1.20.1 release on Modrinth and CurseForge to tell users that it requires Fabric API 0.88.1. 

Just edit the title "Indium 1.0.21 for Minecraft 1.20.1/Sodium 0.4.10" to "Indium 1.0.21 for Minecraft 1.20.1/Sodium 0.4.10/Fabric API 0.88.1"

A lot of people still use Sodium 0.4.10 because quite a few mods have not updated to support Sodium 0.5.x. Such mods include Create and Valkyrien Skies. 

I understand that reuploading an Indium version is messy. I also understand that creating a new version for Sodium 0.4.10 that breaks when FAPI > 0.88.1 is also messy. That's why I came to this compromise of a suggestion.

**Comment by comp500** [comment]
![image](https://github.com/comp500/Indium/assets/1138417/6bba46c0-6d11-4c8d-84b0-68a29b816a16)
Adding `Fabric API 0.88.1` is too long, I had to make it `Fabric API 0.88+` which is hopefully clear enough :)

**Comment by Poopooracoocoo** [comment]
Darn. So nothing can be done for Indium 1.0.21? Thanks anyway. 

Edit: perhaps "FAPI 0.88.1" would work

**Comment by comp500** [comment]
Oops, just realised I got it the wrong way round.. both 1.0.27 and 1.0.21 should specify the Fabric API versions they want now.

**Comment by Poopooracoocoo** [comment]
Awesome thank you!
