### ISSUE TITLE
[Quilt 1.20.1] Indium requires at least version 3.2.0 or any newer version of fabric-renderer-api-v1, but only a different version is present: 3.1.2

### ISSUE THREAD

**Issue by misu9** [comp500/Indium#248]
![Снимок](https://github.com/comp500/Indium/assets/130816847/c8ffab46-e051-4740-9b47-2869f32aeb33)

Crash Report:
[crash-2023-10-07_12.59.03.6222-quilt_loader.txt](https://github.com/comp500/Indium/files/12837431/crash-2023-10-07_12.59.03.6222-quilt_loader.txt)

**Comment by comp500** [comment]
You need to install a recent version of [Quilt Standard Libraries / Quilted Fabric API](https://modrinth.com/mod/qsl).
