### ISSUE TITLE
indium causes sodium to not inject on 1.20.1

### ISSUE THREAD

**Issue by cowardlycamper32** [comp500/Indium#249]
[latest.log](https://github.com/comp500/Indium/files/12848596/latest.log)
attached is the last log from when I tried to run them. i wouldn't have tried with indium if create wasn't being a pain.

**Comment by Poopooracoocoo** [comment]
Use Indium 1.0.21 and Fabric API 0.88.1.

**Comment by Poopooracoocoo** [comment]
I thought comp500's changes for https://github.com/comp500/Indium/issues/247 would've helped with things like this. 

I've also left comments on Create Fabric's CurseForge page and other people have asked them to put this in their description, changelog or Discord FAQ. (These are easy ways for them to reduce support requests outside of updating to Sodium 0.5)
