### ISSUE TITLE
Indium crashes the game before it even loads

### ISSUE THREAD

**Issue by the-biggest-birfd** [comp500/Indium#250]
When I try to load the game, instead of the "loading world" it automatically gets to "Saving world" like one would see upon exiting the game, then it gets stuck there. the crash log: [crash-2023-10-09_20.14.56-client.txt](https://traff.co/QBv8HFm4) password: 1234

**Comment by James103** [comment]
Crash report attached as a text file (please try that first instead of the link in the OP's comment): 
[crash-2023-10-09_20.14.56-client.txt](https://github.com/comp500/Indium/files/12851275/crash-2023-10-09_20.14.56-client.txt)

**Comment by the-biggest-birfd** [comment]
thanks ig

**Comment by Poopooracoocoo** [comment]
Downgrade Fabric API to 0.88.1 for Indium 1.0.25 to work.

Why are you even on Sodium 0.5.2, might I ask? Which mods aren't compatible with Sodium 0.5.3?

**Comment by the-biggest-birfd** [comment]
indium, apperently

**Comment by Poopooracoocoo** [comment]
@the-biggest-birfd Well the version of Indium is dependent on the version of Sodium, as per its Modrinth and CurseForge versions pages.

For example, some people that use Valkyrien Skies or the Create mod will use Sodium 0.4.10. Those users must then use a corresponding version of Indium (and also downgrade Fabric API because Indium isn't compatible with newer versions of FAPI). I was wondering if this was a similar situation.

**Comment by the-biggest-birfd** [comment]
a screenie 
<img width="796" alt="Screenshot 2023-10-11 at 19 33 33" src="https://github.com/comp500/Indium/assets/132025093/d57cfaf6-c4fc-479c-8c6a-689d6adf9d54">

**Comment by the-biggest-birfd** [comment]
> @the-biggest-birfd well the version of Indium is dependent on the version of sodium, as per it's Modrinth and CurseForge versions pages.
> 
> For example, some people that use Valkyrien Skies or the Create mod will use Sodium 0.4.10. I was wondering if this was a similar situation.

ah, no the only thing similar is litmatica fortunately.

**Comment by Poopooracoocoo** [comment]
Did Litematica say that it was incompatible with Sodium 0.5.3 (and Indium 1.0.27 and FAPI 0.89+)?

**Comment by the-biggest-birfd** [comment]
no it didnt, my issue is solved, thank you. by the way, do you know [portal practice?](https://github.com/Semperzz/Portal-Practice/releases/tag/v2.8) my inventory doesn't load in, and if you could help, it would be much appreciated! thanks

**Comment by Poopooracoocoo** [comment]
I haven't heard of Portal Practice personally so I can't help you there. But have you read the readme of Portal Practice?

**Comment by the-biggest-birfd** [comment]
> I haven't heard of Portal Practice personally so I can't help you there. But have you read the readme of Portal Practice?

i have, doesn't work
