### ISSUE TITLE
Tessellating block in world 

### ISSUE THREAD

**Issue by 0owiwo0** [comp500/Indium#251]
Theres an major incompatiblility with another mod "regions unexplored" where the chunks generated/modified by that mod with cause indium to almost always not render correctly

[latest.log](https://github.com/comp500/Indium/files/12887716/latest.log)
![YMGN{1R0N765IG[latest.log](https://github.com/comp500/Indium/files/12887716/latest.log)
WD)6DG8](https://github.com/comp500/Indium/assets/109881670/2438c639-4852-4a3a-9d8f-3d0be43399c7)

**Comment by Poopooracoocoo** [comment]
I'm not seeing Indium in your log

**Comment by comp500** [comment]
As mentioned, your log doesn't have Indium
