### ISSUE TITLE
problem with ae2 with me drive tray block causes screen to go black and crash game (fixed)

### ISSUE THREAD

**Issue by charliegoodge** [comp500/Indium#252]
[latest.log](https://github.com/comp500/Indium/files/12892291/latest.log)

**Comment by Poopooracoocoo** [comment]
Downgrade Fabric API to 0.88.1

You could alternatively update Sodium to 0.5.3 and Indium to 1.0.27 and update other mods in order to use newer versions of Fabric API

**Comment by charliegoodge** [comment]
cheers
