### ISSUE TITLE
Tessellating block in world - Indium Renderer

### ISSUE THREAD

**Issue by pinkangel725** [comp500/Indium#253]
The game loads up until right after 100%, I hear campfires and footsteps from the villagers around my base, then it says "Saving World" and crashes the game.

Trying to read this log is giving me a bit of a headache
https://gist.github.com/pinkangel725/d9c83631f69eaf4fc4cb2821adef64a9#file-crashreport-txt

Would appreciate some help on this, as google searches haven't helped me much

**Comment by Poopooracoocoo** [comment]
Use [Fabric API 0.88.1](https://modrinth.com/mod/fabric-api/version/0.88.1+1.20.1) to make Indium 1.0.25 work.

Or upgrade [Sodium to 0.5.3](https://modrinth.com/mod/sodium/version/mc1.20.1-0.5.3) and [Indium to 1.0.27](https://modrinth.com/mod/indium/version/1.0.27+mc1.20.1).
