### ISSUE TITLE
Circumstantial crash with Supplementaries

### ISSUE THREAD

**Issue by GJdude** [comp500/Indium#256]
Indium version: indium-1.0.21+mc1.20.1
Supplementaries version: supplementaries-1.20-2.6.17-fabric

Supplementaries adds a feature to place down books and books and quills, but placing either causes a crash when running Indium.
The world/server can be reloaded and the book destroyed, but the chunk it's in won't render until refreshed.
I filed a bug report with the Supplementaries team and they confirmed it's something on Lithium's end.

Crash report:
[crash-2023-10-29_14.21.13-client.txt](https://github.com/comp500/Indium/files/13198711/crash-2023-10-29_14.21.13-client.txt)

**Comment by comp500** [comment]
This is a Sodium issue (see https://github.com/CaffeineMC/sodium-fabric/issues/1676), fixed in https://github.com/CaffeineMC/sodium-fabric/commit/5b574194b83ea970a72a883fee7a3b938e1ac062 - you need Sodium 0.5 or newer to fix this issue.

**Comment by GJdude** [comment]
nice to know that once Create Fabric is updated for newer versions of Sodium this'll get a fix out the box
