### ISSUE TITLE
crash when join in a new world

### ISSUE THREAD

**Issue by vocaloidkiss** [comp500/Indium#258]
[Uploading 错误报告-2023-11-19_5.18.25.zip…]()

**Comment by vocaloidkiss** [comment]
[错误报告-2023-11-19_5.18.25.zip](https://github.com/comp500/Indium/files/13401520/-2023-11-19_5.18.25.zip)

**Comment by Poopooracoocoo** [comment]
>indium: Indium 1.0.26+mc1.20.1

Where did you download this from?

**Comment by vocaloidkiss** [comment]
i am so sorry，i do not check the update before open issues.
crash has fixed in 1.0.27+
