### ISSUE TITLE
Compatiblility issue with Supplimentaries.

### ISSUE THREAD

**Issue by vitaluxdev** [comp500/Indium#259]
I have Supplementaries and a bunch of other mods (mod list here: https://imgur.com/a/tJC9WBS), and I have this really weird thing going on with this sign post structure, I don't even know how to describe it, here is a video of it happening: https://streamable.com/3k86l1. Here is the crash log: https://mclo.gs/OFZQkYE. I've determined that it is an issue with compatibility between indium and Supplimentaries. Edit: I tried going into the indigo renderer config and setting "always tessellate blocks" to false, and It just made it worse. https://imgur.com/a/NCatbrp

**Comment by Poopooracoocoo** [comment]
You've got FAPI 0.88.1 but your crash log has a different version. Perhaps you meant to post your latest.log from your logs folder? Also seems more related to Create than to Supplementaries, judging by the mods in the stacktrace.

**Comment by zelcion** [comment]
This is happening the same to me (Minecraft version 1.20.1). The death combo is:

- Sodium 0.4.10
- Indium 1.8.18
- Fabric API 0.88.1
- Supplementaries 2.7.13 (+ Moonlight 2.8.70)

Its reproducible by entering a world with those mods, putting a fence down, and then putting a sign post on it -> Instant crash for me. [Crash Logs](https://mclo.gs/6SJ5VJo)

Perhaps important - Both me and @StickOdyssey have AMD GPUs of the 5000 series (even though i'm running linux so there are different drivers)

Is there any way I can help out on this issue?

**Comment by comp500** [comment]
Closing issue: I'm not supporting Sodium 0.4 / Fabric API 0.88 or older anymore
