### ISSUE TITLE
Game crashes after trying to load my game with Indium

### ISSUE THREAD

**Issue by Sankariliemi** [comp500/Indium#260]
I wanted to use connected glass with sodium and i needed Indium. Now when i try to play singleplayer the game crashes. 
[crash-2023-11-25_14.06.23-client.txt](https://github.com/comp500/Indium/files/13464072/crash-2023-11-25_14.06.23-client.txt)

**Comment by Poopooracoocoo** [comment]
Update Sodium and Indium. Indium 1.0.27 added support for Fabric API 0.89+ but you have Indium 1.0.22.

**Comment by Sankariliemi** [comment]
Thanks it fixed it!
