### ISSUE TITLE
Indium v1.0.27 incompatible with Sodium 0.5.5

### ISSUE THREAD

**Issue by GODLIKE-ro** [comp500/Indium#263]
Game wont launch because indium is incompatible with the latest sodium update. Please fix this.

**Comment by Vaskyy** [comment]
https://github.com/comp500/Indium/pull/262

**Comment by D-argon** [comment]
either downgrade or calm down
sodiums upgraded has not been a week

**Comment by greenollie123** [comment]
But we need it to work with 0.5.5

**Comment by D-argon** [comment]
> But we need it to work with 0.5.5

the simplest answer would be:

make it work then

because if you're not contributing to the development you shouldn't be rushing it.
gladly, somebody already has made it work
( if you don't mind checking, the previously linked, [#262](https://github.com/comp500/Indium/pull/262) )

else

either downgrade and calm down 
or
disable indium and calm down

**Comment by devjta** [comment]
Should that version also work for 1.20.4?

**Comment by D-argon** [comment]
> Should that version also work for 1.20.4?

if I understood your question right,
it does run on 1.20.4,
with the only issue, at the moment, being bad rendering of glass blocks underwater

**Comment by Poopooracoocoo** [comment]
@D-argon 
>with the only issue, at the moment, being bad rendering of glass blocks underwater

Are you sure that can't be reproduced without Indium and just Sodium? Mind taking some screenshots with and without the Indium fork?

**Comment by D-argon** [comment]
@Poopooracoocoo 
> Are you sure that can be reproduced without Indium and just Sodium? Mind taking some screenshots with and without the Indium fork?

it wasn't me that found that, it's in the #262 thread
they didn't gave any details except from the problem so idk how to reproduce it (or if its true)

but the similar issue I found occurs with/without sodium or indium
![2023-12-18_08 16 05](https://github.com/comp500/Indium/assets/130792776/49f86944-6d95-4172-84d7-71ecbd63bb63)
![2023-12-18_08 14 12](https://github.com/comp500/Indium/assets/130792776/81163a74-fe9f-4bb2-b29e-3bb766bc221c)

**Comment by MeeniMc** [comment]
you can remove the version lock of the 1.0.27 .jar yourself: open the jar as a zip file, open fabric.mod.json, change the values for the minecraft version (hint, adding >= in front of the number), save the file back in the jar.
