### ISSUE TITLE
Tessellating block in world - Indium Renderer

### ISSUE THREAD

**Issue by lucagiolu** [comp500/Indium#267]
Reproduction Steps:
1. Go into a snowy biome
2. Game Crashes

Apparently, there is some incompatibility between indium, snow! real magic! and continuity.
I can't really figure it out, but removing continuity from the modfolder solves the issue.

Crash-File: https://mclo.gs/1Dbyeuy

**Comment by Poopooracoocoo** [comment]
Update _Snow! Real Magic!_

**Comment by comp500** [comment]
Closing: likely to be an issue with another mod?

**Comment by xAhwi** [comment]
Thanks man i was lost trying to find help to fix my world not opening and i randomly found this post, after deleting continuity the problem was solved, greetings from argentina <3

**Comment by alexia8225** [comment]
> Update _Snow! Real Magic!_

So I randomly couldn't load into my modded survival world and I was was searching for quite a while on the internet for the cause, and deleting this mod seemed to fix it thank you <3
