### ISSUE TITLE
Tessellating Block in World

### ISSUE THREAD

**Issue by TheSnipps** [comp500/Indium#268]
[crash-2024-01-22_12.32.51-client.txt](https://github.com/comp500/Indium/files/14015383/crash-2024-01-22_12.32.51-client.txt)

Rendering some chunks or certain parts in the chunks are invisible and it's unplayable.
![2024-01-22_12 46 55](https://github.com/comp500/Indium/assets/99994025/a6cd5085-e38b-4649-8ee1-530e3e31c2df)
![2024-01-22_12 47 15](https://github.com/comp500/Indium/assets/99994025/93b24e8a-3fe3-4159-bf9c-40fa9bdcef9e)
![2024-01-22_12 47 25](https://github.com/comp500/Indium/assets/99994025/314ea0c0-3383-417a-adfb-ea1f3a017aa5)
![2024-01-22_12 48 09](https://github.com/comp500/Indium/assets/99994025/1cf7a47d-70f7-4e35-be3b-9f9a6419e4f7)

**Comment by Poopooracoocoo** [comment]
You need to use Fabric API 0.88.1 for Indium 1.0.21. 
https://modrinth.com/mod/qsl/version/7.2.2+0.88.1-1.20.1

**Comment by comp500** [comment]
Closing issue: use the suggested version of Fabric API
