### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TheDivineCombos** [comp500/Indium#270]
After adding indium along with connected glass mods, it doesn't give me any option to toggle connected glass or any of the other options

**Comment by TheDivineCombos** [comment]
For reference, I'm using Connectedglass-1.1.11-fabric-mc1.20.1.jar   sodium-fabric-mc1.20.1-0.5.3.jar   and    indium-1.0.27+mc1.20.1.jar

**Comment by Poopooracoocoo** [comment]
Do you only see this with Indium and Sodium? It sounds like you've misunderstood what [Connected Glass](https://modrinth.com/mod/connected-glass) does. It adds new types of glass. It does not modify existing glass like [Continuity](https://modrinth.com/mod/continuity), [Athena](https://modrinth.com/mod/athena-ctm) and [Fusion](https://modrinth.com/mod/fusion-connected-textures) do.

**Comment by comp500** [comment]
This doesn't sound like an issue with Indium, please report the issue to the authors of the connected glass mods you're using (or maybe you've misunderstood what the mods do?)
