### ISSUE TITLE
Not Compatible with Sodium Versions 0.5.6 and newer

### ISSUE THREAD

**Issue by Mine181** [comp500/Indium#271]
Sodium 0.5.6 released 12 hours ago as of this issue, want to notify if you didn't know.

**Comment by Tapacywka** [comment]
You can use this file to run a previous version of Indium with Sodium 0.5.6 until the developer fixes it themselves.
Just place this file in a folder that contains configs of other mods (.minecraft/config) and Indium will work.
All I did was change the requirement of version 0.5.5 to a version that is equal to or greater than 0.5.6.
[fabric_loader_dependencies.json](https://github.com/comp500/Indium/files/14076105/fabric_loader_dependencies.json)

**Comment by Jasraj11** [comment]
Same here

**Comment by vico93** [comment]
comp500 this very moment with such kind of issues:

![image](https://media1.tenor.com/m/GSB-EMGFVQsAAAAd/didi-didi-abrindo-a-boca-com-am%C3%A3o.gif)

**Comment by TheFaik** [comment]
Same here

**Comment by Mine181** [comment]
Oops! Now we got 0.5.7 :v

**Comment by DroidZed** [comment]
life's hard....time to touch some grass folks until this gets fixed

**Comment by SettingDust** [comment]
https://fabricmc.net/wiki/tutorial:dependency_overrides
Override it. It seems to work. But there are some glitches. Nvidium won't work
For reference:
```json
"nvidium": {
  "-depends": {
    "sodium": "IGNORED"
  }
},
"indium": {
  "-depends": {
    "sodium": "IGNORED"
  }
},
"sodium": {
  "-breaks": {
    "indium": "IGNORED"
  }
}
```

**Comment by DroidZed** [comment]
I don't recommend this. Some glitches would hurt players with huge mod lists.

**Comment by Crystal-Spider** [comment]
Sodium version 0.5.7 fixed a critical issue for my modpack, it would be awesome to get Indium updated soon as I'd need to publish my modpack asap ahah

**Comment by skxlor** [comment]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.7+mc1.20.1 with version 0.5.7 or version 0.5.8 that is compatible with:
		 - indium, any version
	 - Replace mod 'Indium' (indium) 1.0.27+mc1.20.1 with any version that is compatible with:
		 - sodium, version 0.5.7 or version 0.5.8
More details:
	 - Mod 'Indium' (indium) 1.0.27+mc1.20.1 requires version 0.5.3 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.7+mc1.20.1!
	 - Mod 'Sodium' (sodium) 0.5.7+mc1.20.1 is incompatible with version 1.0.27 or earlier of mod 'Indium' (indium), but a matching version is present: 1.0.27+mc1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


Its one error for the other error. Changing as the details suggest makes other stuff break

**Comment by shoo-p** [comment]
Sodium is adding support for FRAPI in 0.6 release 
https://github.com/CaffeineMC/sodium-fabric/pull/1851 
https://github.com/CaffeineMC/sodium-fabric/milestone/5

**Comment by Tapacywka** [comment]
[fabric_loader_dependencies.json](https://github.com/comp500/Indium/files/14121903/fabric_loader_dependencies.json)
Use this file to get Indium working with Sodium version 0.5.8.
Just place it in the folder with the configs of other mods (by default this is .minecraft/config)

**Comment by vico93** [comment]
> [fabric_loader_dependencies.json](https://github.com/comp500/Indium/files/14121903/fabric_loader_dependencies.json) Use this file to get Indium working with Sodium version 0.5.7. Just place it in the folder with the configs of other mods (by default this is .minecraft/config)

Is this part of the fabric_loader_dependencies necessary?
```json
        "fabricloader": {
            "+depends": {
                "fabricloader": ">=0.15.6"
            }
        },

**Comment by Tapacywka** [comment]
> > [fabric_loader_dependencies.json](https://github.com/comp500/Indium/files/14121903/fabric_loader_dependencies.json) Use this file to get Indium working with Sodium version 0.5.7. Just place it in the folder with the configs of other mods (by default this is .minecraft/config)
> 
> Is this part of the fabric_loader_dependencies necessary?
> 
> ```json
>         "fabricloader": {
>             "+depends": {
>                 "fabricloader": ">=0.15.6"
>             }
>         },
> ```

idk, it's from FO modpack.

**Comment by Poopooracoocoo** [comment]
>Is this part of the fabric_loader_dependencies necessary?

No.

**Comment by Naidrox** [comment]
5.8 now gamers

**Comment by krafg** [comment]
@Tapacywka Thx, it worked!

**Comment by tatsumara** [comment]
can confirm the dependency override by @Tapacywka works and doesnt require the fabricloader part (:

**Comment by R00tB33rMan** [comment]
Change the Indium dependency inside of Sodium to an older version than the latest released Indium for proper compatibility. This can be done via WinRAR. I have yet to identify any issues with Indium and Sodium 0.5.8.

**Comment by szunakabeats** [comment]
yea or just use sodium 0.5.3 and the newest indium i guess... works fine for me

**Comment by giopalma** [comment]
> yea or just use sodium 0.5.3 and the newest indium i guess... works fine for me

Latest Indium support sodium 0.5.5
But many other mods need sodium 0.5.7 or higher

**Comment by Niko-n-DEV** [comment]
It is better not to change the sodium/indium dependencies so that there are no errors with mods. Emotecraft does not work correctly with it and a number of others, reaching the wrong display of player skins with endless errors in the logs.

**Comment by Tapacywka** [comment]
> [fabric_loader_dependencies.json](https://github.com/comp500/Indium/files/14121903/fabric_loader_dependencies.json) Use this file to get Indium working with Sodium version 0.5.8. Just place it in the folder with the configs of other mods (by default this is .minecraft/config)

This is the only more or less adequate option to use 0.5.8 Sodium together with Indium. Please do not change anything inside the .jar files of the mods themselves.  You may break compatibility with other mods or cause unpredicable errors.
