### ISSUE TITLE
Minecraft Crashing

### ISSUE THREAD

**Issue by Vassista** [comp500/Indium#274]
Someone help me how to fix the crash? here are the logs
https://mclo.gs/qmM9y1e

**Comment by D-argon** [comment]
"[19:00:55] [main/WARN]: Warnings were found!
 - 'Minecraft' (minecraft) 1.20.1 recommends any version after 5.3.3 of Fabulously Optimized, which is missing!
	 - You should install any version after 5.3.3 of Fabulously Optimized for the optimal experience.
 - Mod 'Wakes' (wakes) 0.2.3 recommends version 3.2.0 or later of yacl, which is missing!
	 - You should install version 3.2.0 or later of yacl for the optimal experience."

**Comment by comp500** [comment]
```
Caused by: java.lang.RuntimeException: Failed to load Indium: Indium is not currently compatible with FREX 6.x, as it provides an incompatible implementation of the Fabric Rendering API; the FREX API may be directly supported in future.
  FREX is bundled as part of JSON Model Extensions
```
Remove JSON Model Extensions (JMX) as it isn't compatible, see https://github.com/comp500/Indium/issues/97

**Comment by Vassista** [comment]
> ```
> Caused by: java.lang.RuntimeException: Failed to load Indium: Indium is not currently compatible with FREX 6.x, as it provides an incompatible implementation of the Fabric Rendering API; the FREX API may be directly supported in future.
>   FREX is bundled as part of JSON Model Extensions
> ```
> 
> Remove JSON Model Extensions (JMX) as it isn't compatible, see #97

thanks now its working
