### ISSUE TITLE
Wrong Version Choosing

### ISSUE THREAD

**Issue by yunus-cakir** [comp500/Indium#275]
Hi! I just wanted to say that the version chosing is wrong!

![image](https://github.com/comp500/Indium/assets/83448525/d9429eb7-c477-45d1-8b4e-63d9228faf3b)

**Comment by comp500** [comment]
I used 1.20.x because 1.20.2-1.20.4 is somewhat too verbose for the version name, and I assumed people had stopped using 1.20.1 so it doesn't really matter anyway? Fixed now as 1.20.1 is supported anyway.
