### ISSUE TITLE
Versions 1.0.29 and 1.0.30 say they are compatible with version 1.20.2, but the required Sodium version isn't

### ISSUE THREAD

**Issue by IJuanTM** [comp500/Indium#278]
Hi,

I have been having this issue where I got this error today when launching my game through Modrinth:
![image](https://github.com/comp500/Indium/assets/43535731/481864ad-8384-4cb8-964a-7e2585d75143)

This happens because I updated my mods today before playing and the latest version of Indium requires a newer version of Sodium (5.5.8). The issue is that the version that is required by Indium is not available for version 1.20.2, but Indium is listed as being compatible with this version in Modrinth.

Because of the fact that Indium requires Sodium to function I think it is better to remove support for the older MC versions because version 5.5.8 of Sodium isn't available for those anyway. That way mod managers like Modrinth won't try to install it.

I now fixed it by manually changing the version of Indium back to 1.28.0, but ever time I run the auto update in Monrinth I have to change this again to fix the error.

Hope to see a response as to what your idea is on this.

**Comment by giopalma** [comment]
Version 1.0.28 is compatible with 1.20.2 and Sodium 0.5.5 (latest sodium version compatible with 1.20.2)

**Comment by IJuanTM** [comment]
>Version 1.0.28 is compatible with 1.20.2 and Sodium 0.5.5 (latest sodium version compatible with 1.20.2)

Yes I know it is, that is not the issue. The issue is that versions .29 and .30 are also listed as being compatible with 1.20.2, while at the same time requiring a newer Sodium version which isn't compatible with 1.20.2.

So my suggestion was to remove the listed support for 1.20.2 for newer versions so that mod managers won't try and automatically update Indium and cause the error, which than has to be fixed manually each time.

**Comment by comp500** [comment]
Done! Sorry I left it like this for so long 🙃
