### ISSUE TITLE
Random crashing 

### ISSUE THREAD

**Issue by D3XGhxst** [comp500/Indium#280]
im playing in version 1.20.1 on fabric with a few mods and every time i place a block from the create mod it crashes

Mod list:
![image](https://github.com/comp500/Indium/assets/159766202/0b44ffb6-ea8f-4718-bf3f-9b5d31e8352a)
![image](https://github.com/comp500/Indium/assets/159766202/400f5db7-e0b9-4194-a281-f13c2a5c390e)
[crash-2024-02-12_09.01.03-client.txt](https://github.com/comp500/Indium/files/14236595/crash-2024-02-12_09.01.03-client.txt)

**Comment by Poopooracoocoo** [comment]
You need to use Indium 1.0.21 and Fabric API 0.88.1

**Comment by comp500** [comment]
Closing issue: use the suggested versions of Fabric API and Indium.
