### ISSUE TITLE
Indium asks to grab Sodium 5.8 even though I already have it

### ISSUE THREAD

**Issue by PrinceJaxonHellsing** [comp500/Indium#281]
Hello! I'm having a very odd issue where When I have the latest version of indium it says to get sodium 5.8 (which I already have) and says I have 5.3 which is really weird. I then deleted sodium 5.8 and launched the game and it gave me the same issue. I don't even have sodium at all in my minecraft folder anymore. I just tested if it gives the same message from the Indium 1.0.25 for Minecraft 1.20.1/Sodium 0.5.2 version, I still get the same issue but this time with it saying 5.2. I have no clue why indium is doing this with any version for me.

**Comment by Poopooracoocoo** [comment]
Screenshot of message and of mods folder?

**Comment by comp500** [comment]
Closing: insufficient information to diagnose issue
