### ISSUE TITLE
Version 1.0.30 incompatibility with mc 1.20.1

### ISSUE THREAD

**Issue by nicofighter45** [comp500/Indium#283]
# Config
Indium_version = 1.0.30+mc1.20.4
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.7
Sodium_version = mc1.20.1-0.5.8
FabricAPI_version= 0.92.0+1.20.1
Java_jdk = 18.0.2

# The error :
[main/WARN] (FabricLoader/Resolution) Mod resolution failed
[main/INFO] (FabricLoader/Resolution) Immediate reason: [HARD_DEP_NO_CANDIDATE indium 1.0.30+mc1.20.4 {depends fabric-renderer-api-v1 @ [>=3.2.0]}, ROOT_FORCELOAD_SINGLE indium 1.0.30+mc1.20.4]
[main/INFO] (FabricLoader/Resolution) Reason: [HARD_DEP indium 1.0.30+mc1.20.4 {depends fabric-renderer-api-v1 @ [>=3.2.0]}]
[main/INFO] (FabricLoader/Resolution) Fix: add [], remove [], replace [[fabric-renderer-api-v1 3.0.1+b3afc78b27] -> add:fabric-renderer-api-v1 3.2.0 ([[3.2.0,∞)])]
[main/ERROR] (FabricLoader) Incompatible mods found!
 net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1) 3.0.1+b3afc78b27 with version 3.2.0 or later.
More details:
	 - Mod 'Indium' (indium) 1.0.30+mc1.20.4 requires version 3.2.0 or later of mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1), but only the wrong version is present: 3.0.1+b3afc78b27!

**Comment by Poopooracoocoo** [comment]
Fabric API 0.92.0+1.20.1 definitely comes with Fabric Renderer API v1 3.2.1+1802ada577 and it works in prod
