### ISSUE TITLE
Tessellating block in world - with Let's Do Vinery 1.4.12-1

### ISSUE THREAD

**Issue by SageofTurtles** [comp500/Indium#285]
Seeing a lot of issues posted with this error message, but wanted to include this as a separate post since some of those have been given different responses, so I'm not sure how specific this problem is.  I'm getting a game crash each time my client tries to render a specific block (only found one so far, so it's possible that something else could cause this as well).  Crash report including full mods list is attached.  Please let me know if there's any solution for this we can attempt for our server's modpack!

[crash-2024-04-12_17.24.19-client.txt](https://github.com/comp500/Indium/files/14964199/crash-2024-04-12_17.24.19-client.txt)

**Comment by lpjn** [comment]
I have the same issue, same crash. Thanks!

Removing lets do vinery stopped the crashes

**Comment by SageofTurtles** [comment]
> I have the same issue, same crash. Thanks!
> 
> Removing lets do vinery stopped the crashes

I actually found a solution for this last night! I was using Vinery 1.4.12-1. Updating to 1.4.14 fixed this bug for me.
