### ISSUE TITLE
Indium crashing Fabric modpack 

### ISSUE THREAD

**Issue by pintaku** [comp500/Indium#286]
My modpack was working perfectly fine until I added Indium to work with Distant Horizons. I'm not sure whats going on, I'm rather inexperienced with this. Any help is appreciated, thank you.

[crash-2024-04-14_16.39.09-client.txt](https://github.com/comp500/Indium/files/14972546/crash-2024-04-14_16.39.09-client.txt)

**Comment by pintaku** [comment]
Upon further testing, the modpack that had Indium still crashes even after its removed. No changes to other mods (including removing all of them) fixes this.

**Comment by Poopooracoocoo** [comment]
Could you also share the `latest.log` file from your logs folder?

**Comment by comp500** [comment]
This doesn't look to be an Indium issue, closing.
