### ISSUE TITLE
Indium rendering error

### ISSUE THREAD

**Issue by ptrnd** [comp500/Indium#287]
My game suddenly crashes when I go to the lava farm and lectern with a book on top of it (the book pile in the Supplementaries mod). Never been like this yesterday or before.

The Minecraft version I use is Fabric 1.20.1.

This is the latest log and crash report.
[latest.log](https://github.com/comp500/Indium/files/14972532/latest.log)
[crash-2024-04-15_06.22.34-client.txt](https://github.com/comp500/Indium/files/14972533/crash-2024-04-15_06.22.34-client.txt)

**Comment by Poopooracoocoo** [comment]
Why are you using Sodium 0.5.2? If you update Sodium to 0.5.3, then you can update Indium to 1.0.27 which supports Fabric API 0.89.0 and above.

It'd be best to use Sodium 0.5.8 and Indium 1.0.30.

**Comment by comp500** [comment]
Closing issue: use the suggested versions of Fabric API and Indium.
