### ISSUE TITLE
Use newer Gradle version.

### ISSUE THREAD

**Issue by RDKRACZ** [comp500/Indium#29]
The version used when building is 6.5.1 from Jun 30, 2020. The current stable is 6.8.3 from Feb 22, 2021.

**Comment by The-Fireplace** [comment]
Is there a good reason to do so? Generally upgrading for the sake of having the latest is not a great practice, since new versions can potentially introduce issues, so unless there's something in the new version that is beneficial to this project, why bother?

**Comment by eutro** [comment]
With rolling release systems it's best to keep on top of updates, so you can get the latest bug fixes and features as soon as they come out. This is why you should take care to update immediately when you see a new version come out, lest you run into a bug that has already been fixed. btw I use Arch

**Comment by comp500** [comment]
I don't see why I should spend time keeping Gradle updated to the latest version on all of my projects when there are very few benefits to doing so, as most of the features added are not relevant to Minecraft modding, or are just very small improvements.

For major releases it might make sense, but in the end it's just a build system; if it works, why change it? It doesn't affect the final mod jar at all, and as @The-Fireplace mentioned, updating Gradle can break the build process. Gradle also updates very frequently, so even if I set up some system to automatically update it I'm likely to waste more time fixing the build when the updates break it than would be saved by having it up to date. Making issues about updating Gradle is just a waste of time for developers - if there are useful features added in newer versions they can just update themselves.

(as I see the nuance was lost on you, @eutro's comment was a joke)
