### ISSUE TITLE
Latest Indium release incompatible with 1.20.6

### ISSUE THREAD

**Issue by TSwany-the-Real** [comp500/Indium#292]
I am attempting to run the latest release of Indium with Fabric for 1.20.6 and the game is repeatedly crashing with the following report:
[crash-2024-04-29_16.00.19-client.txt](https://github.com/comp500/Indium/files/15253159/crash-2024-04-29_16.00.19-client.txt)

Any ideas what is causing this? I need Indium for a mod I basically can't run the game at acceptable performance levels without.

**Comment by Poopooracoocoo** [comment]
That crash report doesn't even have Indium in it. It only points to resolutioncontrol which is not yet available for 1.20.6.

**Comment by Synthyan** [comment]
I had the same issue with the latest release not working with 1.20.6
