### ISSUE TITLE
Conflicting HashMap changes

### ISSUE THREAD

**Issue by xbxct** [comp500/Indium#293]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-06-03 00:11:45
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1229)
	at net.minecraft.class_3533.method_24246(class_3533.java:151)
	at net.minecraft.class_3533.method_15407(class_3533.java:123)
	at net.minecraft.class_310.handler$dab008$iris$onTick(class_310.java:16514)
	at net.minecraft.class_310.method_1574(class_310.java:1957)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1229)
	at net.minecraft.class_3533.method_24246(class_3533.java:151)
	at net.minecraft.class_3533.method_15407(class_3533.java:123)
	at net.minecraft.class_310.handler$dab008$iris$onTick(class_310.java:16514)

-- Affected level --
Details:
	All players: 1 total; [class_746['XBOCT'/1, l='ClientLevel', x=-4268.90, y=-60.00, z=1338.18]]
	Chunk stats: 169, 77
	Level dimension: minecraft:overworld
	Level spawn location: World: (-4256,-58,1327), Section: (at 0,6,15 in -266,-4,82; chunk contains blocks -4256,-64,1312 to -4241,319,1327), Region: (-9,2; contains chunks -288,64 to -257,95, blocks -4608,-64,1024 to -4097,319,1535)
	Level time: 4893829 game time, 754414 day time
	Server brand: quilt
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/ItsKoffis-Compressed-Textures_1.zip, fabric, file/Optimized Models.zip, simply-no-shading:simply_no_entity_like_shading, file/Fast Better Grass.zip, file/SodiumTranslations.zip, file/nomoreui.zip, file/2d_tems_v2_upto_1.12.zip, file/Inventory Flat Pack.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (aarch64) version Android-13
	Java Version: 21.0.4, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 492679832 bytes (469 MiB) / 805306368 bytes (768 MiB) up to 805306368 bytes (768 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: AArch64 Processor rev 0 (aarch64)
	Identifier: 0x41 Family 8 Model 0xd09 Stepping r10p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 2
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4394.25
	Virtual memory used (MB): 4359.73
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 2098.69
	JVM Flags: 31 total; -XX:-UsePerfData -XX:-DontCompileHugeMethods -XX:+AlwaysActAsServerClassMachine -XX:+UnlockExperimentalVMOptions -XX:+UseCompressedOops -XX:+UseInlineCaches -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+UseVectorCmov -XX:+UseTLAB -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -XX:+AlwaysPreTouch -XX:+DoEscapeAnalysis -XX:+EliminateLocks -XX:+EliminateAutoBox -XX:+OptimizeFill -XX:+DisableAttachMechanism -XX:+PerfDisableSharedMem -XX:+DisableExplicitGC -XX:+UseG1GC -XX:+UseSuperWord -XX:InitialCodeCacheSize=64M -XX:ReservedCodeCacheSize=256M -XX:AutoBoxCacheMax=500 -XX:MaxTenuringThreshold=1 -XX:MaxGCPauseMillis=50 -Xnoclassgc -Xms768M -Xmx768M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.firefly/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.firefly/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Loaded Shaderpack: (off)
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.2.1
		async-pack-scan: Async Pack Scan 0.2.0
		asynclocator: Async Locator 1.3.0
		autohud: Auto HUD 6.3.5+1.20.1
			yaclx: YetAnotherConfigLibExtensions 1.6+1.20
		badoptimizations: BadOptimizations 2.1.1
		betterbiomeblend: Better Biome ReBlend 1.4.2
		betterchunkloading: Better chunk loading mod 1.20.1-4.2
		betterclouds: Better Clouds 1.3.17+1.20.1
		betterf3: BetterF3 7.0.2
		betterfpsdist: Better FPS distance Mod 1.20.1-4.3
		blanket-client-tweaks: Blanket Client-tweaks 1.1.4
		bridgingmod: Bridging Mod 2.3.0+1.20.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.5
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.5
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.5
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.5
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.5
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.5
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.5
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.5
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.5
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.5
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.5
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.5
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.5
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.5
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.5
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.5
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.5
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		clean-background: Clean Background 1.0.0
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-config: Cloth Config v11 11.1.118
		collective: Collective 7.61
		collisionfix: CollisionFix 1.0.1
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		coroutil: CoroUtil 1.20.1-1.3.7
		crunchy-crunchy-advancements: Crunchy Crunchy Advancements 1.6.3+1.19.3
			folk_sisby_kaleido-config: kaleido-config 0.1.1+1.1.0-beta.3
		cull-less-leaves: Cull Less Leaves 1.3.0
		cupboard: cupboard 1.20.1-2.2
		dashloader: DashLoader 5.0.0-beta.2+1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		debugify: Debugify 1.20.1+2.0
		doespotatotick: Does Potato Tick fabric-quilt-1.20.1-3.6.1
		embeddium: Embeddium 0.3.19+mc1.20.1
			indium: Indium 1.99.99
			sodium: Sodium 0.5.8
		entityculling: EntityCulling 1.6.5
		exordium: Exordium 1.2.1-mc1.20.1
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fadeless: Fadeless 1.0.1
		fastasyncworldsave: fastasyncworldsave Mod 1.20.1-1.2
		faster_entity_animations: FastAnim 1.6
		ferritecore: FerriteCore 6.0.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		fzzy_config: Fzzy Config 0.3.3+1.20.1
			blue_endless_jankson: jankson 1.2.3
			net_peanuuutz_tomlkt_tomlkt-jvm: tomlkt-jvm 0.3.7
		gamemenuremovegfarb: Game Menu Remove GFARB 2.1.2
		hidehands: Hide Hands 4.2
		icterine: Icterine 1.3.0
		iris: Iris 1.7.0+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 21
		lazydfu: LazyDFU 0.1.3
		libjf: LibJF 3.12.5
			libjf-base: LibJF Base 3.12.5
			libjf-config-commands-v1: LibJF Config Commands 3.12.5
			libjf-config-core-v1: LibJF Config 3.12.5
			libjf-config-ui-tiny-v1: LibJF Config UI: Tiny 3.12.5
			libjf-data-v0: LibJF Data 3.12.5
			libjf-translate-v1: LibJF Translate 3.12.5
			libjf-web-v0: LibJF Web 3.12.5
		lithium: Lithium 0.11.2
		magiclib: MagicLib 0.7.398+fe2125a-stable
			magiclib-1_20_1: MagicLib for 1.20.1 0.7.398+fe2125a-stable
		malilib: MaLiLib 0.16.3
		memoryleakfix: Memory Leak Fix 1.1.5
		memoryusagescreen: Memory Usage Screen 1.9.0
		minecraft: Minecraft 1.20.1
		mobtimizations: Mobtimizations 1.20.1-1.0.0
		modernfix: ModernFix 5.17.0+mc1.20.1
		modmenu: Mod Menu 7.2.2
		moreculling: More Culling 1.20.4-0.24.0
		mr_aesthetic_andperformant: aesthetic and performant 1.5
		noisium: Noisium 2.0.3+mc1.20-1.20.1
		particle_core: Particle Core 0.2.3+1.20.1
			conditional-mixin: conditional mixin 0.5.1
		potatoptimize: potatoptimize 0.0.1
			mixinextras: MixinExtras 0.3.5
			mixinsquared: MixinSquared 0.1.2-beta.5
		quilt_loader: Quilt Loader 0.25.0
		redirector: Redirector 1.20.1-4.4.0
		removehud: Remove Hud But Not Hand! 1.3b2
		resquake: re:squake 1.1.2+1.20.4
		ruok: RuOK Mod 1.5.2
		sciophobia: Sciophobia 1.0.2
		seamless_loading_screen: Seamless Loading Screen 2.0.3+1.20.1
		simplemenu: Simple Menu 1.1
		simply-no-shading: Simply No Shading 6.1.6-mc1.20.1
			spruceui: SpruceUI 5.0.2+1.20
		slyde: Slyde 1.7.1
		smoothchunk: Smooth chunk save Mod 1.20.1-3.2
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.4.2
		starlight: Starlight 1.1.2+fabric.dbc156f
		stepitup: StepItUp 2.0.1-1.20.1
		stutterfix: StutterFix mc1.20.1-0.2.0
		threatengl: ThreatenGL 1.3.2-beta.1
		tt: Transparent Tooltips 1.0.2+1.20.x
		tweakmyclient: Tweak My Client 3.6.401+38c9a34-stable
			tweakmyclient-1_20_1: Tweak My Client for 1.20.1 3.6.401+38c9a34-stable
		videotape: Video Tape 1.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.4.4+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: zink Vulkan 1.0(Turnip Adreno (TM) 610 (MESA_TURNIP)) GL version 4.6 (Compatibility Profile) Mesa 24.1.0 (git-e1e4254491), Mesa
	Window size: 1440x648
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'; Server brand changed to 'quilt'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, file/ItsKoffis-Compressed-Textures_1.zip (incompatible), fabric, file/Optimized Models.zip, simply-no-shading:simply_no_entity_like_shading, file/Fast Better Grass.zip, file/SodiumTranslations.zip, file/nomoreui.zip, file/2d_tems_v2_upto_1.12.zip (incompatible), file/Inventory Flat Pack.zip
	Current Language: ru_ru
	CPU: 8x AArch64 Processor rev 0 (aarch64)
	Server Running: true
	Player Count: 1 / 8; [class_3222['XBOCT'/1, l='ServerLevel[Новый мир]', x=-4268.90, y=-60.00, z=1338.18]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by xbxct** [comment]
Embeddium

**Comment by comp500** [comment]
Embeddium is not supported.
