### ISSUE TITLE
[Bug] Indium 1.0.29 & 1.0.30 for 1.20.x requires Sodium 0.5.8, but Sodium 0.5.8 is not available for 1.20.2

### ISSUE THREAD

**Issue by Boden-C** [comp500/Indium#297]
Indium 1.0.30 apparently supports all 1.20.x, including 1.20.2, and 1.0.29 supports 1.20.2-1.20.4, but the mod requires Sodium 0.5.8

However, Sodium 0.5.8 does not support 1.20.2, and therefore it is impossible for Indium 1.0.29 or 1.0.30 to actually run on 1.20.2

Sodium 0.5.8 doesn't seem to support 1.20.2 at all https://github.com/CaffeineMC/sodium-fabric/issues/2384

![image](https://github.com/comp500/Indium/assets/70297682/98c7b4fc-77dc-40fb-b0b7-f8ae02d991c6)

**Comment by RedrcknRbn** [comment]
Vouch, can we get a 1.20.2 build?
![image](https://github.com/comp500/Indium/assets/63996530/a6cefcb1-edee-4885-91ba-764bfce2e38b)

**Comment by comp500** [comment]
Duplicate of #278! @RedrcknRbn Use https://modrinth.com/mod/indium/version/1.0.28+mc1.20.4
