### ISSUE TITLE
Huge lag spiking 

### ISSUE THREAD

**Issue by itsbumble** [comp500/Indium#30]
My game seems to lag spike a lot of the time when using Indium. I'm using the sodium fork as well as indium. my game is lagging from 300 fps down to like 200 or occasionally down all the way to 70.

**Comment by comp500** [comment]
Do you get the same behaviour with just the Sodium fork, no Indium? Note that Indium doesn't require the fork, so if you aren't using LambdaBetterGrass you can most likely use normal Sodium 1.16.x/next, so it'd probably be worth trying that as well. Try a few things out, let me know what works!

**Comment by itsbumble** [comment]
I found the issue. The sodium fork seems to tank my fps when loading chunks. heres a helpful example video.

**Comment by itsbumble** [comment]
https://file.io/1TCHtVelAMYB

**Comment by comp500** [comment]
I've updated my fork to improve performance (though still slightly slower than upstream Sodium 1.16.x/next) as some changes are no longer necessary - but as I can see you aren't using LambdaBetterGrass, there's no reason to use the fork.

**Comment by itsbumble** [comment]
> I've updated my fork to improve performance (though still slightly slower than upstream Sodium 1.16.x/next) as some changes are no longer necessary - but as I can see you aren't using LambdaBetterGrass, there's no reason to use the fork. Let me know if you still get performance issues with upstream Sodium 1.16.x/next.

actually I am using bettergrass, either way thank you for updating it

**Comment by comp500** [comment]
Ah I see, in that case just test if my changes fix the performance issue :)

**Comment by itsbumble** [comment]
the performance seems to be a decent amount better and the game doesnt die when loading chunks! thanks for fixing it
