### ISSUE TITLE
compat with new version

### ISSUE THREAD

**Issue by Emil2010** [comp500/Indium#300]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.9+mc1.20.6 with version 0.5.8.
More details:
	 - Mod 'Indium' (indium) 1.0.31+mc1.20.4 requires version 0.5.8 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.9+mc1.20.6!
	 - Mod 'Nvidium' (nvidium) 0.2.7-beta requires version 0.5.8 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.9+mc1.20.6!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

iris shaders and sodium extra support new version of sodium
same issue has been posted to nvidium's issue tracker

**Comment by koyuawsmbrtn** [comment]
Same. We'll have to wait for 0.5.9 I guess :3

**Comment by comp500** [comment]
I am well aware that there's new versions of Sodium and Minecraft! Please be patient, I have a full time job and limited free time, which I would rather spend updating the mod than closing all 9 (!) of these issues 🙃
