### ISSUE TITLE
Update when

### ISSUE THREAD

**Issue by AVeryLittleGhost** [comp500/Indium#301]
update when

**Comment by NolanHewitt** [comment]
When you say sorry

**Comment by VadimFreeman** [comment]
yo i cant play with sodium

**Comment by Fyoncle** [comment]
Update whennn xD

**Comment by RU-B0** [comment]
stop posting these. The update came out a day ago. CHILL

**Comment by Fyoncle** [comment]
> stop posting these. The update came out a day ago. CHILL

Uhm... its actually 4 days ago xD and the last one came literally incompatible with sodium, also we just asking yk, theres nothing wrong with asking.

**Comment by NolanHewitt** [comment]
The update is being delayed by one month every-time someone asks.

**Comment by Fyoncle** [comment]
> The update is being delayed by one month every-time someone asks.

Nooo chill xD

**Comment by comp500** [comment]
I am well aware that there's new versions of Sodium and Minecraft! Please be patient, I have a full time job and limited free time (it has been 3 days!), which I would rather spend updating the mod than closing all 9 (!) of these issues 🙃
