### ISSUE TITLE
update when??????????????

### ISSUE THREAD

**Issue by carbage14** [comp500/Indium#304]
make indium compatible with sodium 0.5.9

(also there's a typo in the "do I need Indium if I don't use Sodium" portion of the mod description bc it says "indigo" instead of indium)

**Comment by AmadeoLives** [comment]
Same, the download page on Modrinth and CurseForge both say 1.20.6
But then I get this error:
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.9+mc1.20.6 with version 0.5.9 that is compatible with:
		 - indium, any version
	 - Replace mod 'Indium' (indium) 1.0.31+mc1.20.4 with any version that is compatible with:
		 - sodium, version 0.5.9
More details:
	 - Mod 'Indium' (indium) 1.0.31+mc1.20.4 requires version 0.5.8 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.9+mc1.20.6!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Astralneko** [comment]
The typo is not really there. Indium is a portmanteau of "Indigo" and "Sodium", as it essentially is compatibility between Fabric API's Indigo module and the mod Sodium. The _module_ Indigo does everything the _mod_ Indium does, as long as Sodium isn't present.

**Comment by carbage14** [comment]
ah ok

**Comment by carbage14** [comment]
ah ok

**Comment by comp500** [comment]
I am well aware that there's new versions of Sodium and Minecraft! Please be patient, I have a full time job and limited free time, which I would rather spend updating the mod than closing all 9 (!) of these issues 🙃
