### ISSUE TITLE
Indium is incompatible with Sodium 0.5.10 (Fabric-1.20.1)

### ISSUE THREAD

**Issue by Astralneko** [comp500/Indium#305]
The most up-to-date Indium version says it is compatible with 1.20.1, 1.20.3, and 1.20.4. I use 1.20.1, as I play with a Cobblemon mod pack. However, Indium is not compatible with 1.20.1's most up-to-date version of Sodium, 0.5.10. When I try to run with the most up to date versions of both Indium and Sodium, my game crashes, as Indium expects version 0.5.8 to be present. 0.5.10 _is_ only one day old, so I don't expect an update already, but as the update prior to the most recent one on Modrinth is from February, I'm posting this issue because I'm worried that it will take another 4 months for the next update, and want to make sure you know of this issue.

**Comment by iamsocool1234** [comment]
Yea I got the same issue, I want to use Distant Horizons and I fixed a bunch of other issues but this seems to be one I cannot pass. I am so confused.

**Comment by dev-kamran2001** [comment]
Same issue, [reference](https://github.com/comp500/Indium/issues/306#issuecomment-2169259952)

**Comment by Unknown671302** [comment]
I'm trying to play Create mod but i have to use Sodium and Indium to load the textures in, but it says i have to use 0.5.10 Sodium and Indium but there is no 0.5.10 Indium and that's the problem that i can't fix and if I dry to use 4.10 Sodium and Indium it says u need different Create, but if i use different Create it need different version of java and i have to install all the mods again and I don't want to to it.
Update: got it to work on 1.20.1

**Comment by shinyPy** [comment]
Got the same issues here

**Comment by comp500** [comment]
I am well aware that there's new versions of Sodium and Minecraft! Please be patient, I have a full time job and limited free time, which I would rather spend updating the mod than closing all 9 (!) of these issues 🙃
