### ISSUE TITLE
indium incompatible with sodium 0.5.10 (mc 1.20.1)

### ISSUE THREAD

**Issue by n6gget** [comp500/Indium#308]
can't use most mods like supplementaries and paladin's furniture cause they require indium, can't use indium cause it requires sodium, can't use embeddium in replacement of sodium cause iris needs sodium to work... and there's no alternative to iris for shaders on fabric lol

when's the indium update?? :(

**Comment by Pugmeisters** [comment]
same here

**Comment by Fyoncle** [comment]
> can't use most mods like supplementaries and paladin's furniture cause they require indium, can't use indium cause it requires sodium, can't use embeddium in replacement of sodium cause iris needs sodium to work... and there's no alternative to iris for shaders on fabric lol
> 
> when's the indium update?? :(

Wdym? theres Oculus for forge.

**Comment by n6gget** [comment]
> > can't use most mods like supplementaries and paladin's furniture cause they require indium, can't use indium cause it requires sodium, can't use embeddium in replacement of sodium cause iris needs sodium to work... and there's no alternative to iris for shaders on fabric lol
> > when's the indium update?? :(
> 
> Wdym? theres Oculus for forge.

i use fabric lol

**Comment by Fyoncle** [comment]
> > > can't use most mods like supplementaries and paladin's furniture cause they require indium, can't use indium cause it requires sodium, can't use embeddium in replacement of sodium cause iris needs sodium to work... and there's no alternative to iris for shaders on fabric lol
> > > when's the indium update?? :(
> > 
> > 
> > Wdym? theres Oculus for forge.
> 
> i use fabric lol

You said embeddium lol

**Comment by n6gget** [comment]
> > > > can't use most mods like supplementaries and paladin's furniture cause they require indium, can't use indium cause it requires sodium, can't use embeddium in replacement of sodium cause iris needs sodium to work... and there's no alternative to iris for shaders on fabric lol
> > > > when's the indium update?? :(
> > > 
> > > 
> > > Wdym? theres Oculus for forge.
> > 
> > 
> > i use fabric lol
> 
> You said embeddium lol

embeddium is on fabric

**Comment by prockksy** [comment]
SOLUTION (Until this is fixed by the indium developers) :
Open the Indium jar file using an explorer like WinRar and open the "fabric.mod.json" file. Scroll to the bottom. Where it says "depends" under "sodium", change the version from 0.5.8 to 0.5.10. This solution will cause no issues.
Don't forget to keep any modlaunchers like curseforge closed while doing this, and don't accidentally update indium through them again, until an update with the fix is released. 

Credit: u/Specific-Secret665

**Comment by Fyoncle** [comment]
> SOLUTION (Until this is fixed by the indium developers) : Open the Indium jar file using an explorer like WinRar and open the "fabric.mod.json" file. Scroll to the bottom. Where it says "depends" under "sodium", change the version from 0.5.8 to 0.5.10. This solution will cause no issues. Don't forget to keep any modlaunchers like curseforge closed while doing this, and don't accidentally update indium through them again, until an update with the fix is released.
> 
> Credit: u/Specific-Secret665

Either thats not right or the perfect solution.

**Comment by poenus** [comment]
You can either compile it yourself or wait for the dev. He released the 1.0.32 version 2 days ago.

**Comment by Fyoncle** [comment]
> You can either compile it yourself or wait for the dev. He released the 1.0.32 version 2 days ago.

Why would i need to change Indium's files when i can just open a config and mark sodium compatible with Indium by few lines, so this way it would be better and i wouldn't be getting involved in the mod's files.

**Comment by poenus** [comment]
> > You can either compile it yourself or wait for the dev. He released the 1.0.32 version 2 days ago.
> 
> Why would i need to change Indium's files when i can just open a config and mark sodium compatible with Indium by few lines, so this way it would be better and i wouldn't be getting involved in the mod's files.

I mean that's fine if it works for you 🤷‍♂️.

**Comment by Artem111A** [comment]
The funniest thing is that it requires sodium 5.8, but when you change sodium to that, it says that it now needs 5.10 apparently.

**Comment by Devintrainer** [comment]
Why are the developers so slow and lazy? EVERYBODY AND THEIR GRANDMA ARE SUFFERING!

**Comment by Skyyofficial** [comment]
> Why are the developers so slow and lazy? EVERYBODY AND THEIR GRANDMA ARE SUFFERING!

If they're so lazy why don't you make the update then? smh

**Comment by Fyoncle** [comment]
> Why are the developers so slow and lazy? EVERYBODY AND THEIR GRANDMA ARE SUFFERING!

Respect the developers, go develop the mod yourself for every version and fix the bugs if its so easy, i bet dev is not lifeless like probably YOU that commenting "devs are lazy and slow" they got a life to deal with, modding is not their life.

**Comment by Devintrainer** [comment]
Those are the exact responses I had expected. Well, I was feeling really worked up when I made my comment, not helped by it being almost midnight at the time. I also felt like I could've made it much more profane if I really wanted to.

**Comment by IncubusShiba** [comment]
> SOLUTION (Until this is fixed by the indium developers) : Open the Indium jar file using an explorer like WinRar and open the "fabric.mod.json" file. Scroll to the bottom. Where it says "depends" under "sodium", change the version from 0.5.8 to 0.5.10. This solution will cause no issues. Don't forget to keep any modlaunchers like curseforge closed while doing this, and don't accidentally update indium through them again, until an update with the fix is released.
> 
> Credit: u/Specific-Secret665

I made a whole account just to comment on this one. I wanted so badly for this to work, but unfortunately for me it doesn't. If this works for others, that's cool. Changing the line of code dependency only made the modrinth pack crash without an error stating why. Changing it back led to the original logic loop "Indium needs Sodium 5.8" "Sodium 5.10 needs better Indium"
I think we're all just going to have to wish the dev godspeed and wait for the update.

**Comment by Fyoncle** [comment]
> > SOLUTION (Until this is fixed by the indium developers) : Open the Indium jar file using an explorer like WinRar and open the "fabric.mod.json" file. Scroll to the bottom. Where it says "depends" under "sodium", change the version from 0.5.8 to 0.5.10. This solution will cause no issues. Don't forget to keep any modlaunchers like curseforge closed while doing this, and don't accidentally update indium through them again, until an update with the fix is released.
> > Credit: u/Specific-Secret665
> 
> I made a whole account just to comment on this one. I wanted so badly for this to work, but unfortunately for me it doesn't. If this works for others, that's cool. Changing the line of code dependency only made the modrinth pack crash without an error stating why. Changing it back led to the original logic loop "Indium needs Sodium 5.8" "Sodium 5.10 needs better Indium" I think we're all just going to have to wish the dev godspeed and wait for the update.

Dev already working on it :D

**Comment by IncubusShiba** [comment]
> > > SOLUTION (Until this is fixed by the indium developers) : Open the Indium jar file using an explorer like WinRar and open the "fabric.mod.json" file. Scroll to the bottom. Where it says "depends" under "sodium", change the version from 0.5.8 to 0.5.10. This solution will cause no issues. Don't forget to keep any modlaunchers like curseforge closed while doing this, and don't accidentally update indium through them again, until an update with the fix is released.
> > > Credit: u/Specific-Secret665
> > 
> > 
> > I made a whole account just to comment on this one. I wanted so badly for this to work, but unfortunately for me it doesn't. If this works for others, that's cool. Changing the line of code dependency only made the modrinth pack crash without an error stating why. Changing it back led to the original logic loop "Indium needs Sodium 5.8" "Sodium 5.10 needs better Indium" I think we're all just going to have to wish the dev godspeed and wait for the update.
> 
> Dev already working on it :D

And I love that! If I knew how to code better I'd offer to help!

**Comment by comp500** [comment]
I am well aware that there's new versions of Sodium and Minecraft! Please be patient, I have a full time job and limited free time, which I would rather spend updating the mod than closing all 9 (!) of these issues 🙃

**Comment by prockksy** [comment]
> > SOLUTION (Until this is fixed by the indium developers) : Open the Indium jar file using an explorer like WinRar and open the "fabric.mod.json" file. Scroll to the bottom. Where it says "depends" under "sodium", change the version from 0.5.8 to 0.5.10. This solution will cause no issues. Don't forget to keep any modlaunchers like curseforge closed while doing this, and don't accidentally update indium through them again, until an update with the fix is released.
> 
> > 
> 
> > Credit: u/Specific-Secret665
> 
> 
> 
> I made a whole account just to comment on this one. I wanted so badly for this to work, but unfortunately for me it doesn't. If this works for others, that's cool. Changing the line of code dependency only made the modrinth pack crash without an error stating why. Changing it back led to the original logic loop "Indium needs Sodium 5.8" "Sodium 5.10 needs better Indium"
> 
> I think we're all just going to have to wish the dev godspeed and wait for the update.

Sorry this didn't work for you! It just happened to work for me fine!

**Comment by IncubusShiba** [comment]
> > > SOLUTION (Until this is fixed by the indium developers) : Open the Indium jar file using an explorer like WinRar and open the "fabric.mod.json" file. Scroll to the bottom. Where it says "depends" under "sodium", change the version from 0.5.8 to 0.5.10. This solution will cause no issues. Don't forget to keep any modlaunchers like curseforge closed while doing this, and don't accidentally update indium through them again, until an update with the fix is released.
> > 
> > 
> > > 
> > 
> > 
> > > Credit: u/Specific-Secret665
> > 
> > 
> > I made a whole account just to comment on this one. I wanted so badly for this to work, but unfortunately for me it doesn't. If this works for others, that's cool. Changing the line of code dependency only made the modrinth pack crash without an error stating why. Changing it back led to the original logic loop "Indium needs Sodium 5.8" "Sodium 5.10 needs better Indium"
> > I think we're all just going to have to wish the dev godspeed and wait for the update.
> 
> Sorry this didn't work for you! It just happened to work for me fine!

For sure, and I'm glad it did work for you! I had hoped it would work for me too. I was pretty desperate when my indium-sodium problem came up because I was already loading up a bunch more mods into something that didn't come with them already, so I was more afraid that I had broken something. Imagine my relief when I saw it was just a mod update problem and not me breaking my favorite things 🙃
