### ISSUE TITLE
Sodium 0.5.9 & 1.21

### ISSUE THREAD

**Issue by TanushChugh19** [comp500/Indium#309]
Make it compatible with Minecraft 1.21 and Sodium 0.5.9 as I need to use continuity mod with sodium.

**Comment by Cristy678** [comment]
i need it compatible with 1.21 so i can play normally without any problems

**Comment by comp500** [comment]
I am well aware that there's new versions of Sodium and Minecraft! Please be patient, I have a full time job and limited free time, which I would rather spend updating the mod than closing all 9 (!) of these issues 🙃
