### ISSUE TITLE
continuation of issue 30

### ISSUE THREAD

**Issue by itsbumble** [comp500/Indium#31]
while the lag spiking has gotten a decent bit better, my game still seems to have a lower amount of FPS when compared to using normal sodium.

i noticed while using the fork, i get around 150 to 230 FPS. while using normal sodium i get an average of around 250 to 300 fps.  the lagging most commonly occurs when loading chunks, however my game seems to have a considerably lower amount of frames in most scenarios compared to using a normal version of sodium.

**Comment by itsbumble** [comment]
I was testing this using speed 255 in a superflat world. while loading lots of chunks, these were my results

Normal Sodium, no indium - around 170 - 220 fps
Fork Sodium, yes indium -  around 60 - 80 fps

**Comment by comp500** [comment]
By normal Sodium do you mean the latest 1.16.x/next commit? Make sure you try that if you haven't already. Also try testing 1.16.x/next with Indium (not my fork), to see if it's the fork or Indium that is causing the performance issue.

**Comment by itsbumble** [comment]
hmmm,.
today i tried using the same mods as i did when opening the issue and it doesnt lag anymore
it might be my computer lagging itself.
