### ISSUE TITLE
it says delete indium or get a compatible version with sodium i delete it because there are non that work but it says you need indium for sodium to work please fix 

### ISSUE THREAD

**Issue by Jettiboo7** [comp500/Indium#310]

**Comment by Jettiboo7** [comment]
it says delete indium or get a compatible version with sodium i delete it because there are non that work but it says you need indium for sodium to work please fix

**Comment by comp500** [comment]
I am well aware that there's new versions of Sodium and Minecraft! Please be patient, I have a full time job and limited free time, which I would rather spend updating the mod than closing all 9 (!) of these issues 🙃

**Comment by Jettiboo7** [comment]
ok thanks
