### ISSUE TITLE
1.21 dev build for impatients

### ISSUE THREAD

**Issue by ThisCatLikesCrypto** [comp500/Indium#311]
this is simply a download for anyone interested, i built a 1.21 version of the current repo and tested it, works fine
https://dl.wilburwilliams.uk/api/raw/?path=/Other/indium-1.0.32-dev.unknown%2Bmc1.21.jar

**Comment by hollowheap** [comment]
does this work with sodium 0.5.9?

**Comment by Ramixin** [comment]
According to the `fabric.mod.json`, it was built exclusively for sodium 0.5.9

**Comment by SKA-midna** [comment]
so, it looks like we must be patient(?)(didn't work for me unless i am doing something incorrect). thanks for trying though ~ are you still trying to debug the version you build?

**Comment by comp500** [comment]
Please don't post unreleased builds here. This is not the appropriate place to share builds, and makes it harder for me to diagnose bug reports, particularly if bugs were fixed before making the actual release.
