### ISSUE TITLE
Game crash when open inventory

### ISSUE THREAD

**Issue by jxxoee** [comp500/Indium#312]
### Confirmation

- [X] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

My minecraft works fine and I can use the mod until I open my inventory and my game just crashes. When I take Indium out of my mods, it stops crashing.
I have continuity, sodium, iris and indium installed

### Steps to Reproduce

Join a game in minecraft
Open inventory

### Mod Version

indium-1.0.33+mc1.21

### Minecraft Version

1.21

### Attach latest.log

[latest.log](https://github.com/user-attachments/files/15917679/latest.log)

### Attach Crash Report

[crash-2024-06-20_13.21.47-client.txt](https://github.com/user-attachments/files/15917698/crash-2024-06-20_13.21.47-client.txt)

**Comment by demonar** [comment]
same issue here

**Comment by princessSparky** [comment]
Happening for me too,

**Comment by Zackbot2** [comment]
seems to be a conflict between specifically continuity and indium

**Comment by Poopooracoocoo** [comment]
Should be fixed by https://github.com/IrisShaders/Iris/commit/43cf325

**Comment by segura14** [comment]
you think the bug is fixed when

**Comment by RiskE80T** [comment]
im also having this problem

**Comment by Fyoncle** [comment]
Probably fixed with Iris 1.7.2, you can't use it yet because Indium doesn't support, so i'm  assuming it will be fixed in the latest release of Indium

**Comment by comp500** [comment]
Use Iris 1.7.2, with Indium 1.0.34!
