### ISSUE TITLE
Flickering of luminous textures

### ISSUE THREAD

**Issue by ilanich** [comp500/Indium#313]
### Confirmation

- [X] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

"Light Ores" and other similar resource packs have a problem with the flickering of ores (screenshot).
![2024-06-24_17 51 53](https://github.com/comp500/Indium/assets/116487656/1e295571-5bdb-4f40-afac-5b9dcd9135f9)

### Steps to Reproduce

1. Install Sodium, Indium, Continuity. And any resource pack with glowing ores (i've attached light ores)
[Light Ores! Vanilla 1.20.6.zip](https://github.com/user-attachments/files/15955924/Light.Ores.Vanilla.1.20.6.zip)
2. Open Minecraft
3. Find any ore and you'll see how it flickers

### Mod Version

1.0.33

### Minecraft Version

1.21

### Attach latest.log

[latest.log](https://github.com/user-attachments/files/15956008/latest.log)

### Additional Information

I use 5 mods: sodium, indium, continuity, fabric api, mod menu. All the latest versions. All these mods are needed for luminous textures, there are no extra mods. I've seen this bug on minecraft version 1.20.6 and indium version 1.0.30. Once I used Embeddium (fork of sodium, which has indium embedded with some changes) on minecraft version 1.20.6, there was no texture flickering on it.

**Comment by Fyoncle** [comment]
That is not a Indium bug, thats a Sodium bug.

It will be fixed in Sodium 0.6.0

**Comment by Fyoncle** [comment]
@ilanich In the meanwhile you can try to use [MoreMcmeta](https://modrinth.com/mod/moremcmeta) and its addon called [MoreMcmeta Emissive Textures](https://modrinth.com/mod/moremcmeta-emissive) then disable Continuity's Emissive texture feature from the config, and let MoreMcmeta do the job for you without any z-fighting.
