### ISSUE TITLE
Crash du jeu lors de l'ouverture de l'inventaire 

### ISSUE THREAD

**Issue by segura14** [comp500/Indium#314]
### Confirmation

- [x] I have tested the bug without Sodium and Indium.
- [x] I have kept all my mods up to date.

### Bug Description

Alors quand je spawn sur la map tout se passe bien mais dès que j'ouvre mon inventaire mon Minecraft crash

### Steps to Reproduce

Pour reproduire ce bug il faut prendre iris, sodium et indium vous faites une partie classique mais dès que vous allez ouvrir votre inventaire il va y avoir le bug il fera crash votre jeu

### Mod Version

indium-1.0.33+mc1.21.jar

### Minecraft Version

1.21

### Attach latest.log

[latest.log](https://github.com/user-attachments/files/16022432/latest.log)

### Attach Crash Report

[crash-2024-06-28_02.13.11-client.txt](https://github.com/user-attachments/files/16022439/crash-2024-06-28_02.13.11-client.txt)

**Comment by Poopooracoocoo** [comment]
Iris 1.7.2 fixed this (https://github.com/IrisShaders/Iris/commit/43cf325) but it requires Sodium 0.5.11 which Indium does not yet support.

**Comment by comp500** [comment]
Duplicate of https://github.com/comp500/Indium/issues/312
