### ISSUE TITLE
Game Crashing Randomly

### ISSUE THREAD

**Issue by harrrobe** [comp500/Indium#315]
### Confirmation

- [ ] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

game crashes

### Steps to Reproduce

1. Open Minecraft 
2. Play Game
3. Wait For It To Randomly Crash

### Mod Version

1.0.33

### Minecraft Version

1.21

### Attach latest.log

cannot figure out how to make this error again its random so no latest log sorry

### Attach Crash Report

https://paste.labymod.net/axuzezuselomacowocon

**Comment by Fyoncle** [comment]
I don't think that is related to Indium, see https://www.labymod.net/tr/idea/14003 and also you should give a latest log for him to be able to fix this issue.

**Comment by harrrobe** [comment]
> I don't think that is related to Indium, see https://www.labymod.net/tr/idea/14003 and also you should give a latest log for him to be able to fix this issue.

i dont have flux installed
the labymod team said it was indium
when it happens again i will provide latest log

**Comment by Poopooracoocoo** [comment]
Iris 1.7.2 fixed this (https://github.com/IrisShaders/Iris/commit/43cf325) but it requires Sodium 0.5.11 which Indium does not yet support.

**Comment by Fyoncle** [comment]
> > I don't think that is related to Indium, see https://www.labymod.net/tr/idea/14003 and also you should give a latest log for him to be able to fix this issue.
> 
> i dont have flux installed the labymod team said it was indium when it happens again i will provide latest log

It says Flux on your log tho?

**Comment by ShadowRocks2** [comment]
try placing sand or gravel and let it start falling, if you crash its continuity

**Comment by harrrobe** [comment]
> > > I don't think that is related to Indium, see https://www.labymod.net/tr/idea/14003 and also you should give a latest log for him to be able to fix this issue.
> > 
> > 
> > i dont have flux installed the labymod team said it was indium when it happens again i will provide latest log
> 
> It says Flux on your log tho?

well its probably like "no FLux installed"

**Comment by Poopooracoocoo** [comment]
> > It says Flux on your log tho?
> 
> well its probably like "no FLux installed"

Uh

> Installed addons: 1 -> flux (1.2.17)

**Comment by harrrobe** [comment]
> > > It says Flux on your log tho?
> > 
> > 
> > well its probably like "no FLux installed"
> 
> Uh
> 
> > Installed addons: 1 -> flux (1.2.17)
Well All my Addons Are Fabric Loader And Labychat utils

**Comment by harrrobe** [comment]
> try placing sand or gravel and let it start falling, if you crash its continuity

well thats fine if i do that

**Comment by harrrobe** [comment]
> Iris 1.7.2 fixed this ([IrisShaders/Iris@43cf325](https://github.com/IrisShaders/Iris/commit/43cf325)) but it requires Sodium 0.5.11 which Indium does not yet support.

is there anyway workaround to it crashing. i was far away it crashed and the next day when i went back on i drowned with all my loot 4000 blocks away from spawn and there was nothing i could do

**Comment by comp500** [comment]
Please update to Iris 1.7.2 / Sodium 0.5.11 / Indium 1.0.34!
