### ISSUE TITLE
Ask support for sodium 0.5.11

### ISSUE THREAD

**Issue by esuity** [comp500/Indium#317]
### Confirmation

- [x] I have tested the bug without Sodium and Indium.
- [x] I have kept all my mods up to date.

### Bug Description

Sodium's newest version is 0.5.11 now and Indium doesn't support it.

**Comment by liveIns** [comment]
you can change the sodium version in fabric.mod.json i tested it and it works. {temp solution} until indium updates.

**Comment by Fyoncle** [comment]
Don't wanna be rude but how inpatient can you be to ignore the button and open a bug report for that? can't you see that button out there?
![image](https://github.com/comp500/Indium/assets/63975256/08c4a916-4b07-465f-a93c-7a38d14b22c4)

Well IF YOU DON'T HAVE ABILITY to click the buttons, here is what it shows you when u click that.
![image](https://github.com/comp500/Indium/assets/63975256/d88ce20d-6388-461a-a023-ab44da19712e)

**Comment by razorchase49** [comment]
Where does one find fabric.mod.json? I can't find it anywhere in the config folder.
EDIT: found it, it's in the .jar.

> you can change the sodium version in fabric.mod.json i tested it and it works. {temp solution} until indium updates.
