### ISSUE TITLE
indium conflicts with journey map 

### ISSUE THREAD

**Issue by Broken0ora** [comp500/Indium#319]
### Confirmation

- [ ] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

i use Sodium btw.  If i dont use indium when a gravity block falls my game craches  when i try to load the game with indium and  journey map it crashes..   i dont know why they are conflicting 

### Mod Version

-1.0.33+mc1.21.jar

### Minecraft Version

1.21

### Attach Crash Report

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.11+mc1.21 with version 0.5.9.
More details:
	 - Mod 'Indium' (indium) 1.0.33+mc1.21 requires version 0.5.9 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.11+mc1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) 

### Additional Information

![image](https://github.com/comp500/Indium/assets/174324539/58ed312f-9f9f-4e5d-b9fc-46ba1e92ee5d)
![image](https://github.com/comp500/Indium/assets/174324539/abacae40-155f-483f-8e9a-1a847a91b1ee)

**Comment by JENOVAAbsolute** [comment]
This crash is unrelated to JourneyMap. Indium has not been updated to work with the latest version of Sodium. Downgrade Sodium to 0.5.9 until Indium updates.

**Comment by comp500** [comment]
Use Indium 1.0.34!
