### ISSUE TITLE
Transparent lines in water

### ISSUE THREAD

**Issue by Carlosjrlu** [comp500/Indium#32]
I get this weird transparent lines in water.

![2021-03-09_18 02 42](https://user-images.githubusercontent.com/20954701/110550479-c7aebc80-8101-11eb-8014-7d2a9941c1dc.png)
![2021-03-09_18 04 23](https://user-images.githubusercontent.com/20954701/110550569-e9a83f00-8101-11eb-8de9-4e76ba3ba696.png)

Using sodium next that I got from their discord and I built indium myself.

**Comment by Meeni-mc** [comment]
Try disabling Compact Vertex Format in Sodium options, it doesn't work on AMD with Sodium-next at the moment.

**Comment by Carlosjrlu** [comment]
Yeah, that solved, the weird thing is that this only happens when I load indium too.
Sodium next alone doesn't seem to cause that issue.
