### ISSUE TITLE
Newest Fabric Version 0.101.0 doesn't support Indium

### ISSUE THREAD

**Issue by zxiphos** [comp500/Indium#324]
### Confirmation

- [ ] I have tested the bug without Sodium and Indium.
- [ ] I have kept all my mods up to date.

### Bug Description

Newest version of Fabric API causes game to crash when joining a world.

### Steps to Reproduce

Run Fabric API version 0.101.0 with Indium

### Mod Version

1.0.34

### Minecraft Version

1.21

### Attach latest.log

https://mclo.gs/DTl5SVa

### Attach Crash Report

[crash-2024-08-05_00.55.26-client.txt](https://github.com/user-attachments/files/16488396/crash-2024-08-05_00.55.26-client.txt)

### Additional Information

![image](https://github.com/user-attachments/assets/708131e2-0cf4-4ce4-accb-31bec748ab19)
![image](https://github.com/user-attachments/assets/1d3024e6-0c64-4981-b762-4cb0510b8c43)

**Comment by LordEnder-Kitty** [comment]
I was literally just about to report this. I did some testing and I believe it's actually Continuity's fault.
I loaded the game with just fabric api, sodium, indium, mod menu and continuity, and it worked fine, but when I enabled the continuity connecting textures pack, it crashed.

**Comment by LordEnder-Kitty** [comment]
Update: it works without sodium and indium though. So either continuity is just weird, or indium is broken.

**Comment by SpokenWig620933** [comment]
Continuity loads the bad method in indium, causing the crash, nothing to do with continuity itself

**Comment by SpokenWig620933** [comment]
For everyone that sees these errors, downgrade fabric-api to 100.8 or remove continuity/indium until indum has an update.

**Comment by agaertner** [comment]
Not a solution for MultiMC users

**Comment by vico93** [comment]
> For everyone that sees these errors, downgrade fabric-api to 100.8 or remove continuity/indium until indum has an update.

But are 100.8 available to 1.21.1?

**Comment by agaertner** [comment]
> > For everyone that sees these errors, downgrade fabric-api to 100.8 or remove continuity/indium until indum has an update.
> 
> But are 100.8 available to 1.21.1?

Same issue. Made a setup for 1.21.1 and Fabric Loader won't let me start MC with Fabric API 100.8. So I can't easily roll back. I'd have to redo my entire setup for 1.21.0

Only option for me currently is to disable Continuity and Indium although that causes the "Enable Connect Texture" bug on the surfaces of any material.

Hopefully there will be an update for it here soon.

**Comment by zhenlige** [comment]
> > For everyone that sees these errors, downgrade fabric-api to 100.8 or remove continuity/indium until indum has an update.
> 
> But are 100.8 available to 1.21.1?

It seems to be available by modifying `fabric.mod.json` to contain 1.21.1.

**Comment by mpustovoi** [comment]
About 6 of the mods I have already require `Fabric API` 0.102.0, so I guess I have to wait for Indium's update

**Comment by Poopooracoocoo** [comment]
@mpustovoi Do they actually use the new features/changes? Have you tested a dependency override or by editing their FMJs?

**Comment by mpustovoi** [comment]
> Do they actually use the new features/changes?

Yes, they do have some fixes for `ModernFix`'s dynamic resources, for example.

> Have you tested a dependency override or by editing their FMJs?

I don't want to mess with it. I have other instances on 1.20.1 while I wait for the `Indium` update.

**Comment by PukPukov** [comment]
> But are 100.8 available to 1.21.1?

De-facto yes, but you need to manually change 1.21 to 1.21.1 in fabric api jar.

**Comment by bentaex** [comment]
[logs](https://mclo.gs/DLXNnWr)

**Comment by Peppe-73** [comment]
**Need an Indium urgent update please thanks**

**Comment by Peppe-73** [comment]
is it possible that you don't have a discord contact for support?

**Comment by Athar42** [comment]
What would this change having a Discord @Peppe-73 ? harass the dev a little more to hurry up ?
You should be happy that this is a free mod available and just take a breath now.

The update will come when the dev will get time to work on this matter, until now, you can stay on 1.21 for the client (as it can connect to 1.21.1 servers too).

**Comment by PukPukov** [comment]
No, they should not be happy when mod was available and in the one moment it dies/stops updating for a long time breaking player setups. But they should blame not mod author, but mojang that don't want to release stable mod api, or, in this very case, when there is nothing really bad from mojang (the update is minor), themselves, because it is easily fixable by changing 1.21 to 1.21.1 in fabric api jar.

**Comment by No-Eul** [comment]
> For everyone that sees these errors, downgrade fabric-api to 100.8 or remove continuity/indium until indum has an update.

Or download [Fabric Renderer API (v1) 3.3.0+0ae0b97dd1](https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-renderer-api-v1/3.3.0%2B0ae0b97dd1/fabric-renderer-api-v1-3.3.0%2B0ae0b97dd1.jar) and apply it. This method works well in 1.21.1 without modifing `fabric.mod.json` in Fabric API mod file.

**Comment by Peppe-73** [comment]
> What would this change having a Discord @Peppe-73 ? harass the dev a little more to hurry up ? You should be happy that this is a free mod available and just take a breath now.
> 
> The update will come when the dev will get time to work on this matter, until now, you can stay on 1.21 for the client (as it can connect to 1.21.1 servers too).

I don't speak English I use Google, I don't know how google translated my language, but nobody blames the developer, unfortunately the Indium are tied to many other mods that remain blocked if you remove Idium, it simply requires an update to solve the problem, thanks.

**Comment by PukPukov** [comment]
You've been already explained to how you can do without updating indium.

**Comment by Peppe-73** [comment]
I don't speak English I use Google, I don't know how google translated my language, but nobody blames the developer, unfortunately the Indium are tied to many other mods that remain blocked if you remove Idium, it simply requires an update to solve the problem, thanks.

**Comment by Peppe-73** [comment]
> You've been already explained to how you can do without updating indium.

I just explained what I was trying to say, I will try the recommended method while waiting for an update, thanks

**Comment by Peppe-73** [comment]
> > For everyone that sees these errors, downgrade fabric-api to 100.8 or remove continuity/indium until indum has an update.
> 
> Or download [Fabric Renderer API (v1) 3.3.0+0ae0b97dd1](https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-renderer-api-v1/3.3.0%2B0ae0b97dd1/fabric-renderer-api-v1-3.3.0%2B0ae0b97dd1.jar) and apply it. This method works well in 1.21.1 without modifing `fabric.mod.json` in Fabric API mod file.

Hi, thanks for the link, I downloaded it and it worked, and MC started with all the Mods, including Indium. thanks

**Comment by ac1mx** [comment]
This still appears with 1.0.35 and Fabric API 0.102.0+1.21, btw.

**Comment by dmstewart42** [comment]
1.0.35 works for me with Fabric API 0.102.0+1.21 and Continuity 3.0.0-beta5.

ac1mx, does your crash report look the same as the 1.0.34 crash?

**Comment by ac1mx** [comment]
Yes, same crash report. Issue vanishes with Indium disabled.

**Comment by Athar42** [comment]
> 1.0.35 works for me with Fabric API 0.102.0+1.21 and Continuity 3.0.0-beta5.
> 
> ac1mx, does your crash report look the same as the 1.0.34 crash?

Same, fixes for me too, but I use the latest FabricAPI : fabric-api-0.102.1+1.21.1 (as I'm on 1.21.1 client :) )

**Comment by ash-development** [comment]
indium 1.0.35, fabricapi 0.102.0, & continuity 3.0.0-beta.5 work for me :p

**Comment by ac1mx** [comment]
It turns out this issue may be related to Meteor client. Removing either Meteor or Indium seems to fix the issue.

**Comment by LordEnder-Kitty** [comment]
> It turns out this issue may be related to Meteor client. Removing either Meteor or Indium seems to fix the issue.

Meteor Client, as in the hack client?

⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠛⠛⠛⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⠉⠁⠀⠀⠀⠀⠀⠀⠀⠉⠻⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⠋⠈⠀⠀⠀⠀⠐⠺⣖⢄⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡏⢀⡆⠀⠀⠀⢋⣭⣽⡚⢮⣲⠆⠀⠀⠀⠀⠀⠀⢹⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡇⡼⠀⠀⠀⠀⠈⠻⣅⣨⠇⠈⠀⠰⣀⣀⣀⡀⠀⢸⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡇⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣟⢷⣶⠶⣃⢀⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡅⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⠀⠈⠓⠚⢸⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⢀⡠⠀⡄⣀⠀⠀⠀⢻⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠐⠉⠀⠀⠙⠉⠀⠠⡶⣸⠁⠀⣠⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣦⡆⠀⠐⠒⠢⢤⣀⡰⠁⠇⠈⠘⢶⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠠⣄⣉⣙⡉⠓⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤⣀⣀⠀⣀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿

**Comment by bphd** [comment]
[13:31:58] [main/WARN]: Error loading class: link/infra/indium/renderer/render/AbstractQuadRenderer (java.lang.ClassNotFoundException: link/infra/indium/renderer/render/AbstractQuadRenderer)
[13:31:58] [main/INFO]: I used the json to destroy the json
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/fabricmc/mapping/reader/v2/TinyVisitor

**Comment by Poopooracoocoo** [comment]
@bphd Looks like you're in the wrong place. Start by joining the Fabric Discord server and going to the player-support channel. https://fabricmc.net/discuss/
