### ISSUE TITLE
it doesn't start

### ISSUE THREAD

**Issue by Peppe-73** [comp500/Indium#329]
### Confirmation

- [ ] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

I don't know what it depends on but as soon as I start Minecraft the game doesn't open and I get this warning

![idium](https://github.com/user-attachments/assets/0cae26fd-4b13-463d-94f8-ad2fe01b6d9d)
[log.txt](https://github.com/user-attachments/files/16573647/log.txt)

### Minecraft Version

MC 1.21

**Comment by Hakuati** [comment]
Yes same issue with indium... :D

**Comment by vico93** [comment]
Duplicate of #324, i think

**Comment by comp500** [comment]
Duplicate of #324
