### ISSUE TITLE
Blocks turn transparent if it rains or anything changes 

### ISSUE THREAD

**Issue by dMoonShadowElf** [comp500/Indium#33]

**Comment by dMoonShadowElf** [comment]
so if it rains everything becomes see through

**Comment by dMoonShadowElf** [comment]
it fixed when i removed immersive portals

**Comment by comp500** [comment]
Does this happen with only Sodium, without Indium? Also make sure you are using the Immersive Portals fork of Sodium, that is necessary for Immersive Portals to work.

**Comment by DragonEggBedrockBreaking** [comment]
I cannot reproduce this, when using just fabric api, modmenu, immersive portals, the IP sodium fork and indium. This should be closed due to not being indium's fault, either being another mod, or OP using the wrong mod(s).
