### ISSUE TITLE
Latest version of Indium is unfortunately incompatible with 1.21.1

### ISSUE THREAD

**Issue by MrBlackmidi** [comp500/Indium#338]
### Confirmation

- [X] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Mod Version

1.0.35

### Minecraft Version

1.21.1

### Attach latest.log

[latest.log](https://github.com/user-attachments/files/16647292/latest.log)

### Attach Crash Report

[crash-2024-08-18_15.23.40-client.txt](https://github.com/user-attachments/files/16647291/crash-2024-08-18_15.23.40-client.txt)

### Additional Information

![Minecraft Launcher 18_08_2024 3_26_27 PM](https://github.com/user-attachments/assets/010fea4a-763d-4a2b-a3c6-a02df03538a3)

**Comment by comp500** [comment]
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for mixins.iris.compat.sodium.json:shadow_map.frustum.MixinNonCullingFrustum from mod iris during activity: [Transform -> Method sodium$createViewport()Lnet/caffeinemc/mods/sodium/client/render/viewport/Viewport; -> INVOKESPECIAL -> net/caffeinemc/mods/sodium/client/render/viewport/Viewport::<init>:(Lnet/caffeinemc/mods/sodium/client/render/viewport/frustum/Frustum;Lorg/joml/Vector3d;)V]

That looks like a problem with Iris, not Indium...

**Comment by MrBlackmidi** [comment]
confirmed
