### ISSUE TITLE
The game crashed whilst rendering screen

### ISSUE THREAD

**Issue by Micalobia** [comp500/Indium#34]
`The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;`

[Crash Report](https://github.com/comp500/Indium/files/6133997/crash-2021-03-12_20.31.12-client.txt)

**Comment by comp500** [comment]
See https://github.com/CaffeineMC/sodium-fabric/issues/16
