### ISSUE TITLE
Indium isn't loading 1.21.1

### ISSUE THREAD

**Issue by jpaxer** [comp500/Indium#340]
### Confirmation

- [X] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

Indium won't load. I have Fabric API and everything. I have Mod Menu installed, and it doesn't see it either.

### Steps to Reproduce

1. Launch Minecraft with Fabric 1.21.1
2. Try entering a world with a mod that requires Indium
3. Check Mod Menu and see that Indium isn't there

### Mod Version

1.0.35

### Minecraft Version

1.21.1

### Attach latest.log

[latest.log](https://github.com/user-attachments/files/16842336/latest.log)

### Attach Crash Report

[hs_err_pid11014.log](https://github.com/user-attachments/files/16842344/hs_err_pid11014.log)

**Comment by comp500** [comment]
Are you sure you have the right version? Try redownloading it! If it still doesn't show up, send  a screenshot of your mods folder.

**Comment by randomzebra** [comment]
I had this issue just now. If you are using iris, the Iris installer for some reason gives you the beta jars for both Iris and Sodium. Indium has a hard requirement for Sodium ver. 0.5.11, which has a requirement for iris ver. 1.7.3+mc1.21.

**Comment by zero-pome** [comment]
Sodium no longer requires Indium since 0.6.0-beta.

**Comment by comp500** [comment]
Ah yeah @zero-pome is correct - Indium is no longer required for Sodium 0.6, just remove it.
