### ISSUE TITLE
The game crashed whilst tessellating block in world

### ISSUE THREAD

**Issue by pearlxz** [comp500/Indium#341]
### Confirmation

- [x] I have tested the bug without Sodium and Indium.
- [ ] I have kept all my mods up to date.

### Bug Description

when exploring world get bollean render error w place Block{minecraft:dirt_path}

### Steps to Reproduce

1.open mine
2.join game
3.place Block{minecraft:dirt_path}
4.crash game w -1 error

### Mod Version

1.0.25

### Minecraft Version

1.20.1

### Attach latest.log

[latest.log](https://github.com/user-attachments/files/17005982/latest.log)

### Attach Crash Report

[crash-2024-09-15_20.48.50-client.txt](https://github.com/user-attachments/files/17005983/crash-2024-09-15_20.48.50-client.txt)

### Additional Information

https://youtu.be/6oLvl6Yn2IQ

**Comment by Poopooracoocoo** [comment]
> Indium 1.0.25
Sodium 0.5.2
Iris 1.6.8
Sodium Extra 0.5.1
Reese's Sodium Options 1.6.5
Fabric API 0.90.4
More Culling 0.19.0

You're using an old version of Indium. This was fixed a long time ago: https://github.com/comp500/Indium/commit/75088b0e3a8f479484cc020ca8049ae90fb8951f
All you need to do is update Indium and related mods.

**Comment by pearlxz** [comment]
god bless you <3
