### ISSUE TITLE
Doesn't work with latest version of sodium

### ISSUE THREAD

**Issue by ghost** [comp500/Indium#343]
### Confirmation

- [X] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

Not showing up in mod menu, so I pretty sure it's not working, when I replaced the latest sodium with 0.5.11 1.21.x it works fine and shows up in mod menu.

### Steps to Reproduce

Run minecraft in latest release with sodium 0.6.0 Beta 2, fabric api, and indium installed.

### Mod Version

1.0.35

### Minecraft Version

1.21.1

**Comment by Poopooracoocoo** [comment]
Sodium 0.6.0 supports the Fabric Rendering API. There's no need for Indium with it.

**Comment by ghost** [comment]
> Sodium 0.6.0 supports the Fabric Rendering API. There's no need for Indium with it.

Ahh so that's why connected textures still worked(with continuity), is there a point to keeping indium updated anymore?

**Comment by Poopooracoocoo** [comment]
No.
Also see https://github.com/comp500/Indium/issues/342#issuecomment-2365178248

**Comment by ghost** [comment]
> No.
> 
> Also see https://github.com/comp500/Indium/issues/342#issuecomment-2365178248

Alr thanks.
