### ISSUE TITLE
Will there be a NeoForge port?

### ISSUE THREAD

**Issue by NovaViper** [comp500/Indium#345]
Since Sodium/Iris is now available on Neoforge, are there any plans of porting over Indium over to NeoForge?

**Comment by Crystal0404** [comment]
No, Indium is no longer required in Sodium 0.6

**Comment by NovaViper** [comment]
@Crystal0404 Ah alrighty! Thanks for the info! Will close the issue now (Meant to close it earlier but got sidetracked 😓 )
