### ISSUE TITLE
[Suggestion] Make a curseforge page with a ready to use build

### ISSUE THREAD

**Issue by MineAndDine96** [comp500/Indium#35]
Maybe make a curseforge entry for it, because many people have started using it and they alaways have to ask in a Discord for community made builds.

**Comment by comp500** [comment]
See https://github.com/comp500/Indium/issues/13#issuecomment-769573483 - I won't do so until Sodium 1.16.x/next has a release, as you have to use a build of that branch of Sodium anyway.
