### ISSUE TITLE
[sodium fork] Not working with ConnectedBlockTextures

### ISSUE THREAD

**Issue by itsbumble** [comp500/Indium#37]
The normal 1.16.x/next works with ConnectedBlockTextures, however your fork seems to cause a crash when joining world.

**Comment by itsbumble** [comment]
https://paste.ee/p/EQrdA <-- log

**Comment by comp500** [comment]
My fork is slightly out of date, I'll fix it now

**Comment by itsbumble** [comment]
Thank you so much for fixing this. I don't have to deal with ugly glass anymore!
