### ISSUE TITLE
Mouse crashes

### ISSUE THREAD

**Issue by srnyx** [comp500/Indium#40]
**Log 1:** https://pastebin.com/npFwQZ4S
**Log 2:** https://pastebin.com/GF4kGwBt
_I have Architectury API installed if that causes any issues._

**Comment by comp500** [comment]
Does the same crash occur if you remove Sodium and Indium? This looks like an issue with Kibe or Architectury, not Sodium or Indium.

**Comment by srnyx** [comment]
> Does the same crash occur if you remove Sodium and Indium? This looks like an issue with Kibe or Architectury, not Sodium or Indium.

Oh, yeah, it seems to not be because of Indium.
Sorry about this.
