### ISSUE TITLE
Crash on start with ConnectedBlockTextures (Sodium Fork)

### ISSUE THREAD

**Issue by TechnicProblem** [comp500/Indium#41]
I saw someone else have this problem and it was resolved, but it doesn't work for me. I am using Indium and your Sodium fork which works great, but when adding CBT the game crashes on load, saying "The game crashed whilst initializing game
Error: java.lang.UnsupportedOperationException".

Crash report: [https://pastebin.com/VTDUEc15](https://pastebin.com/VTDUEc15)

**Comment by comp500** [comment]
CBT needs to be compiled from the source on Github, the version on CurseForge is broken with recent Fabric API.

**Comment by TechnicProblem** [comment]
Thanks for the help, compiled it from source and now it works!
