### ISSUE TITLE
Indium crashes the game before it even loads

### ISSUE THREAD

**Issue by heyjudek** [comp500/Indium#43]
[crash-2021-03-28_23.35.56-server.txt](https://github.com/comp500/Indium/files/6218137/crash-2021-03-28_23.35.56-server.txt)
[latest.log](https://github.com/comp500/Indium/files/6218124/latest.log)
When I try to load the game, instead of the "loading world" it automatically gets to "Saving world" like one would see upon exiting the game, then it gets stuck there.
Removing indium solves this problem.

**Comment by comp500** [comment]
Do you have the latest versions of both Indium and Sodium compiled from source / Github Actions? It also looks like you have a separate crash caused by Palette, which if I am not mistaken is for 1.14 snapshots and is very unlikely to work on 1.16.5.

**Comment by heyjudek** [comment]
Well, I did get rid of it. And the crash happened again. Yes. I did use the latest of both Sodium and Indium and the lack of palette didn't seem to have fixed the crash.

**Comment by DragonEggBedrockBreaking** [comment]
> If there is anything else I can try, please let me know.

Can you try narrowing down the mods? There are a lot of mods that could be causing the crash, and it would be nice to know which mod(s) is/are causing the issue. I always narrow my crashes down to the two or three mods that cause a crash, to make it easier for devs to solve it, and to make sure I don't post issues on repos that **may8* have nothing to do with the mod.

(Also, on an unrelated note, your `sodium extra` version is out of date, and there have been a bunch of new features added).

**Comment by comp500** [comment]
See https://github.com/CaffeineMC/sodium-fabric#bleeding-edge-builds-unstable for where to download the latest 1.16.x/next development version of Sodium.

**Comment by heyjudek** [comment]
Just curious, should I as a non-modder be using these bleeding edge versions to get Indium to work? As far as I know, my sodium version should be one of the very latest ones already.

**Comment by heyjudek** [comment]
Is building the latest version from code hard? If you already have it, could you please send it so I can test it?

**Comment by heyjudek** [comment]
Update, I downloaded the Sodium extra version you gave and also sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT (tester version, from 05.02.2021) and it finally works.
