### ISSUE TITLE
Game crashes as soon as the world loads

### ISSUE THREAD

**Issue by Hyperbean18** [comp500/Indium#44]
As soon as the world loads, the game shows the saving world screen and crashes. I have the latest versions of both Indium as well as the fork of sodium mentioned in the description. I downloaded them from the Actions tab. 

Crash Report: [Here](https://gist.githubusercontent.com/natanfudge/884d6e1bc29d1f1a229dfa933ce58eb9/raw/7244a72f5b7028f42fe15d002874e0441339d0df/crash.txt)

File: 
[crash-2021-03-30_18.28.55-client.txt](https://github.com/comp500/Indium/files/6229177/crash-2021-03-30_18.28.55-client.txt)

**Comment by comp500** [comment]
You'll want to use the 1.16.x/next branch of my fork, the buildtaskerrorpropagation branch is only for a specific fix, not related to the LBG issue.

**Comment by Hyperbean18** [comment]
Just tried it, works perfectly! Thanks!
