### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Mat0wa3** [comp500/Indium#45]
When i compile the indium mod, and i open my minecraft with it, the water, the portals, the lava, and the fire does not have animations, and in the animations menu are active

how can i active them?...

**Comment by comp500** [comment]
This is a Sodium bug that is fixed in the current 1.16.x/next branch. Please recompile Sodium or [download it from Github Actions](https://github.com/CaffeineMC/sodium-fabric#bleeding-edge-builds-unstable).
