### ISSUE TITLE
I am too dumb for this

### ISSUE THREAD

**Issue by THEKAI64** [comp500/Indium#46]
I cannot for the life of me figure out how to install this mod I have tried running the gradle bat, and it says something about succeeding, but I can't find a .Jar or anything anywhere. I am in need of education in this, so please enlighten me.

**Comment by comp500** [comment]
The built jar is produced in the build/libs/ folder. You can also get a build [from Github Actions](https://github.com/comp500/Indium/issues/13#issuecomment-766741351).
