### ISSUE TITLE
Glass does not connect properly when using CBT

### ISSUE THREAD

**Issue by Hyperbean18** [comp500/Indium#49]
![2021-04-17_20 31 13](https://user-images.githubusercontent.com/79054980/115143766-deccbc80-a066-11eb-8b90-03b18c4deb98.png)

It looks normal when using canvas tho

**Comment by DragonEggBedrockBreaking** [comment]
Build the latest CBT build from source, this has been fixed there.

**Comment by Hyperbean18** [comment]
Works, thanks!
