### ISSUE TITLE
Glass emits light underwater

### ISSUE THREAD

**Issue by Hyperbean18** [comp500/Indium#50]
![2021-04-17_23 36 45](https://user-images.githubusercontent.com/79054980/115143913-75997900-a067-11eb-8639-c02ca9a650ea.png)

Theres no light sources there, kinda weird

**Comment by DragonEggBedrockBreaking** [comment]
What other mods do you use?

**Comment by Hyperbean18** [comment]
![Screen Shot 2021-04-20 at 5 15 28 PM](https://user-images.githubusercontent.com/79054980/115390741-381a2480-a1fc-11eb-8bf0-aab8595a5c37.png)
![Screen Shot 2021-04-20 at 5 15 39 PM](https://user-images.githubusercontent.com/79054980/115390748-3b151500-a1fc-11eb-8e48-608952980dc7.png)
![Screen Shot 2021-04-20 at 5 15 52 PM](https://user-images.githubusercontent.com/79054980/115390751-3c464200-a1fc-11eb-9370-1a7a829c18d2.png)
![Screen Shot 2021-04-20 at 5 16 03 PM](https://user-images.githubusercontent.com/79054980/115390754-3d776f00-a1fc-11eb-97f2-7e6ecd135f18.png)

**Comment by Hyperbean18** [comment]
The tube does rise up over the water, so that might be it

**Comment by Hyperbean18** [comment]
Yep, I tested it without indium and the same thing happened

**Comment by DragonEggBedrockBreaking** [comment]
> Yep, I tested it without indium and the same thing happened

So this is not an indium bug and should be closed.
