### ISSUE TITLE
How to Download

### ISSUE THREAD

**Issue by HauntedBunny** [comp500/Indium#51]
I don't see anywhere to download a java file to put into Fabric. I want to make connected glass textures work with my Fabric setup, because I hate the grid glass.

**Comment by Reeses-Puffs** [comment]
You have to compile it alongside the latest commit of sodium/next branch.

**Comment by HauntedBunny** [comment]
I have no idea ho to code; I only got here by [this page](https://www.curseforge.com/minecraft/mc-mods/ctm-fabric) as it suggests using Indium will make the mod work in tandem with Sodium.

**Comment by Reeses-Puffs** [comment]
No knowledge of coding needed, just compile from source.

**Comment by HauntedBunny** [comment]
And what is compiling from source? When I download it I just get a .zip file.

**Comment by Reeses-Puffs** [comment]
if you don't know what compiling from source means, then you probably shouldn't use this. if you absolutely must, then there are plenty of resources out there that provide information on the process. google search "how to compile java program" for tutorials.

**Comment by HauntedBunny** [comment]
Alright then, thank you.
