### ISSUE TITLE
Client Crash: ConcurrentModificationException - nextNode

### ISSUE THREAD

**Issue by hugeblank** [comp500/Indium#55]
All details can be found in this [crash report](https://github.com/comp500/Indium/files/6446654/message.txt). Not entirely sure if this is indium or sodium, figured I'd fire it here first.

**Comment by comp500** [comment]
Hmm, what mods are you using that require Indium? It looks like a mod is modifying the block entity list during `getRenderAttachmentData`, but I can't seem to find any mods that do that...

**Comment by hugeblank** [comment]
AE2 textures don't render properly with sodium unless indium is installed

**Comment by comp500** [comment]
Does this crash occur when loading the world, or after you'd placed/broken a specific block? If the latter, which blocks were you using?

**Comment by comp500** [comment]
Hmm... could you send me the world that you managed to produce this bug with? No worries if you don't want to, I can hook up some debugging code to Indium and let you test that, but it'd certainly make things quicker to work on the world directly.

**Comment by hugeblank** [comment]
Sure. It's a 5.6 gig (when compressed) multiplayer server, so grab a cup of coffee or something this will probably take a while to download. Have the [world](https://drive.google.com/file/d/13lVTsmIBrbZomLpt_L8d40icHmXM3IHI/view?usp=sharing) and the [modpack](https://drive.google.com/file/d/16QtstSeUdYxpprMlMIkkwfht3RhtWbI9/view)
The place where it happens is the machine room of our starter base, at +1632 8 -2047. If you run around there, looking around it should eventually crash. A lot of my friends crash by coming in from the entrance teleport pad and looking west. 

Honestly, you might want to just give me a build with the debug stuff builtin, I think it would be easier for the both of us :P

**Comment by hugeblank** [comment]
Quick update - I believe I've isolated this issue down to specifically being caused by [Crafting CPUs](https://ae-mod.info/Crafting-CPU/), specifically being in proximity to them.

**Comment by hugeblank** [comment]
Thought I'd also mention that the logs keep getting spammed with errors like:
```[17:47:58] [main/ERROR]: ########## GL ERROR ##########
[17:47:58] [main/ERROR]: @ Pre render
[17:47:58] [main/ERROR]: 65539: Invalid key -1
[17:47:58] [main/ERROR]: ########## GL ERROR ##########
[17:47:58] [main/ERROR]: @ Pre render
[17:47:58] [main/ERROR]: 65539: Invalid key 0```
Figured this might be tangentially related to this issue.

**Comment by hugeblank** [comment]
A third issue better related to this one, with a bit more of a severity:
[crash.txt](https://gist.githubusercontent.com/natanfudge/2f9c065338046586f81c1fb56c7f1fb4/raw/e42998cbbd86c594f31eb151b52a2894ce42cb08/crash.txt)

User logs on, terrain renders for a bit, they see this before crashing with the report above: 
![image](https://user-images.githubusercontent.com/16393543/119949766-0dd02b00-bf4f-11eb-8b78-c3a43c03f22c.png)
where what I see is this:
![image](https://user-images.githubusercontent.com/16393543/119949842-204a6480-bf4f-11eb-9fcc-35457fabe84a.png)

**Comment by comp500** [comment]
That screenshot looks like a registry desync issue, where the mods aren't matching on the server and client. Does it work without Sodium and Indium?

**Comment by comp500** [comment]
I haven't managed to replicate this myself, and the world file was removed before I had the chance to download it. Could you try the [1.16.x/experiments/renderattachmentcme](https://github.com/comp500/Indium/tree/1.16.x/experiments%2Frenderattachmentcme) branch of Indium - it has some extra debugging code to attempt to see what exactly causes this issue. Please also test without Indium, as I don't see why this wouldn't also happen with Indigo.

**Comment by hugeblank** [comment]
> the world file was removed before I had the chance to download it

ahh yeah sorry about that, google drive only gives 15 gigs of storage and the world save was taking over a third of that. I mistakenly assumed you saved it, my bad.

I'm also on a bit of a break right now and away from my main PC. I'll be back at it in a couple weeks. I'll see if I can have a friend of mine test in the mean time.

**Comment by comp500** [comment]
In more recent versions (Sodium 0.3.x and newer) this should be fixed; see also https://github.com/CaffeineMC/sodium-fabric/issues/942
