### ISSUE TITLE
Game crash when loading world

### ISSUE THREAD

**Issue by FumpleWumper** [comp500/Indium#57]
I wanted to use Sodium together with Bits and Chisels but blocks appeared invisible this way, so I saw that I had to install Indium in order for both mods to work together, but with Indium installed now, the game simply crashes after it finishes loading the world, same happening in a singleplayer world

Any way to fix this? The crash report is attached below
[crash-2021-05-11_00.46.53-client.txt](https://github.com/comp500/Indium/files/6455563/crash-2021-05-11_00.46.53-client.txt)

**Comment by comp500** [comment]
Indium requires the [1.16.x/next branch](https://github.com/CaffeineMC/sodium-fabric/tree/1.16.x/next) of Sodium, release 0.1.0 won't work.

**Comment by FumpleWumper** [comment]
Ah thank you, I didn't know about this version! It's working now, thank you for your attention!
