### ISSUE TITLE
Moving Textures

### ISSUE THREAD

**Issue by LordVenom77** [comp500/Indium#59]
When I run Indium and Sodium together the game runs great... except moving textures don't work. Fire, water, and lava are all still. Is there a way to fix this in config or is it a bug?

**Comment by comp500** [comment]
What commit of Sodium are you using? I believe this was fixed by https://github.com/CaffeineMC/sodium-fabric/commit/38e5b45b3645c95b22aaded300c7189e866ba1c2

**Comment by comp500** [comment]
Closing since this is likely to be unrelated.
