### ISSUE TITLE
fabric-rendering-fluids-v1 implementation

### ISSUE THREAD

**Issue by comp500** [comp500/Indium#6]
Sodium replaces Minecraft's FluidRenderer with it's own, so https://github.com/FabricMC/fabric/blob/1.16/fabric-rendering-fluids-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/fluid/MixinFluidRenderer.java doesn't apply. It should be fairly straightforward to reimplement this mixin for Sodium's fluid rendering code.

See https://github.com/jellysquid3/sodium-fabric/issues/485 and https://github.com/Mixinors/Astromine/issues/334

Similarly, some mixins in `fabric-rendering-v1` may also need to be reimplemented.

**Comment by RDKRACZ** [comment]
I came here to report that Indium doesn't fix fluid textures broken by Sodium [e.g Astromine] but if I understand correctly it's because of this right?

**Comment by comp500** [comment]
Yes.
