### ISSUE TITLE
Indium on Curseforge or Modrinth?

### ISSUE THREAD

**Issue by dandin87** [comp500/Indium#63]
With the release of Sodium 0.2.0 on Modrinth, Do you plan on releasing Indium? Or is the plan still to get it implemented into Sodium itself? https://modrinth.com/mod/sodium

**Comment by IronOxidizer** [comment]
Even just having a GitHub release build would be nice.

**Comment by comp500** [comment]
I'm likely going to wait for Sodium 0.2.0 to release on CurseForge first, but yes I would like to release a build for 1.16 on both platforms.

**Comment by douira** [comment]
Sodium 0.3 for Minecraft 1.17.1 has been released. I can confirm that there are big rendering issues if Sodium is used with Indium.

**Comment by comp500** [comment]
Now under review for Modrinth, and available from Github Releases at https://github.com/comp500/Indium/releases!
