### ISSUE TITLE
Sodium with Indium: AOF3 Modern Industrialization machine animation

### ISSUE THREAD

**Issue by Gaurdein** [comp500/Indium#64]
Mods: AOF3 2.8.4, with "modern-industrialization 0.4.0-alpha.10" (changed from 2.8.4's alpha 8), added with "indium-1.0.01.16.5-a997c55.jar" (AOF3 team's FAQ linked) and "sodium-fabric-mc1.16.5-0.2.0+build.4.jar"

When I enable the setting "Animate Only Visible Textures" in Sodium the blocks with a conditional animated texture (like machines which animate when working) only display a single frame of their animation. Changing the setting instantly let's them continue while enabling it again stops them at the current frame. Blocks with always-on animations like fluid pipes which has the water animation sequence inside them works fine.
Java 16, 8600K, RX 570, Mesa 18.3.6, Debian 10

p.s. Downloaded current code and used the wrapper to compile. Issue persists.

**Comment by comp500** [comment]
I think this is due to textures not being passed through to Sodium's `ChunkModelBuilder.addSprite` method. I'll likely wait until 1.17 stabilises to implement this, as it might not be an easy fix.
