### ISSUE TITLE
1.17 branch not updated to 1.17 :)

### ISSUE THREAD

**Issue by TAKfsg** [comp500/Indium#65]
the 1.17 branch when you compile it says in the log that the mod is meant for 1.16

**Comment by comp500** [comment]
It shouldn't? Please send the log...

**Comment by TAKfsg** [comment]
> It shouldn't? Please send the log...

https://pastebin.com/iNi7nTgp

**Comment by comp500** [comment]
You have not compiled the mod correctly. This does not happen on the 1.17.x/main branch.
