### ISSUE TITLE
Error in cmd file

### ISSUE THREAD

**Issue by SourishGhosh7** [comp500/Indium#66]

**Comment by SourishGhosh7** [comment]
I ran the gradlew file in my cmd but it gives a error as follows-

FAILURE: Build failed with an exception.

* What went wrong:
Executing Gradle tasks as part of a build without a settings file is not supported. Make sure that you are executing Gradle from a directory within your Gradle project. Your project should have a 'settings.gradle(.kts)' file in the root directory.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by SourishGhosh7** [comment]
Pls don't say to update Java and gradle they all are in latest version

**Comment by SourishGhosh7** [comment]
Also there is a settings.gradle file in the folder

**Comment by DragonEggBedrockBreaking** [comment]
Did you remember to cd into the directory, sometimes I forget, so it is a possibility?

**Comment by SourishGhosh7** [comment]
> Did you remember to cd into the directory, sometimes I forget, so it is a possibility?


See this know what is the need of cd I wrote the whole path

C:\Users\souri>C:\Users\souri\OneDrive\Desktop\Indium-1.16.x-main\gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Executing Gradle tasks as part of a build without a settings file is not supported. Make sure that you are executing Gradle from a directory within your Gradle project. Your project should have a 'settings.gradle(.kts)' file in the root directory.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by DragonEggBedrockBreaking** [comment]
Maybe the issue is using it in one drive, try using it outside of onedrive

**Comment by SourishGhosh7** [comment]
Didn't work 
I'll rather download artifacts
Thnx for ur patience
