### ISSUE TITLE
Issue with fabric 1.17.1

### ISSUE THREAD

**Issue by eshankiyer** [comp500/Indium#67]
Minecraft doesn't launch and gives this error:

The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

**Comment by Angelic-System** [comment]
Mod Isnt updated for .1 Yet

**Comment by eshankiyer** [comment]
Ok, but even when I change back to 1.17 it fails to launch

**Comment by DragonEggBedrockBreaking** [comment]
> Mod Isnt updated for .1 Yet

The mod works on 1.17.1 in general (if it works on 1.17.0, which it seems it does specifically here).

**Comment by eshankiyer** [comment]
Weird.... whenever I launch 1.17.1 with indium it always crashes and says: suspected mods Fabricloader, Indium

**Comment by eshankiyer** [comment]
Whoops! Turns out Indium is incompatible with seamless-loading-screen. Thats what was causing the launch failure.
