### ISSUE TITLE
Game freezing every once in a while

### ISSUE THREAD

**Issue by xynydev** [comp500/Indium#68]
Yesterday I built Indium from source and after starting to use it my game has been freezing every once in a while.

Logs show nothing except a ton of this
`[12:12:36] [Server thread/INFO]: Saving and pausing game...
[12:12:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[USUV HQ]'/minecraft:overworld
[12:12:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[USUV HQ]'/minecraft:the_nether
[12:12:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[USUV HQ]'/minecraft:the_end`

The only way to fix this is to force quit Minecraft and restart it.

This is my mods list:
Amecs
Appleskin
Architectury
Authme
BetterControls
Cloth API
Cloth Config
Command Macros
ConnectedTexturesMod for Fabric
Dynamic FPS
Fabric API
Fabrishot
Indium (indium-1.0.0+rev.820073e)
Iris
LambdaBetterGrass
LambDynamicLights
Light Overlay
Litematica
Malilib
Minihud
Mod Menu
Mouse Wheelie
Name Pain
Ok Zoomer
Skin Swapper
Tweakeroo
VanillaTweaks Downloader
Worldedit 
Xaeros Minimap
Xaeros Worldmap
(yes I know thats a ton of mods)

The only way to fix the freeze is to force quit Minecraft, which also freezes all of the UI on macos.

Edit: I disabled Indium and this is still happening. It just started happening after I installed Indium.

Edit 2: My whole user account just crashed and booted me back to the login screen, this has never happenened without Indium installed.

**Comment by comp500** [comment]
If the freeze still occurs without Indium installed, it clearly isn't being caused by Indium itself. Please test your mods without Indium+Sodium, as well as only Sodium - this could be a system stability issue, or an issue caused by Sodium.

**Comment by Emanatnawtnodi** [comment]
Iknow im kinda late, but i have the same issue with a similar setup of mods (removing indium didnt fix it, like you said) the crash is probably some other mod conflicting with indium, but not a indium issue. Have you fixed it/ found out what the cause is? I have been trying to get it solved for multiple day now.

**Comment by comp500** [comment]
This issue has very little information so I have no idea what would cause it, and as removing Indium doesn't fix it this repository clearly isn't the right place to be discussing it. I suggest you try removing other mods, such as Iris and Sodium, and if that fixes the issue take it to the support channels (Discord/Github/etc) of those mods. Ideally try to find the smallest set of mods that will cause the issue, and provide a full log file to the developers.
