### ISSUE TITLE
Fire texture not animated

### ISSUE THREAD

**Issue by PotatoPresident** [comp500/Indium#7]
Fire animated texture isn't working in latest commit.

Other animated blocks like sea lanterns seem to be working, but fire isn't.

https://user-images.githubusercontent.com/51728317/105447027-35715880-5c28-11eb-9f60-bd518b260b81.mp4

**Comment by comp500** [comment]
That's an issue with Sodium's `1.16.x/next` branch, not Indium.

**Comment by PotatoPresident** [comment]
Oh, my bad! Should have been more through
