### ISSUE TITLE
Crash after "Tesselating block in world"

### ISSUE THREAD

**Issue by ExecuteOrd66** [comp500/Indium#70]
I was pushing my PC, as I tried to use the Bits and Chisel mod alongside Iris shaders (specifically Contemporary shaders). Don't know if the crash is useful, but I'll post it anyway. (My apologies if I'm posting in the wrong place, as the blame might be for any of the above-mentioned mods). The game and world were able to load successfully. There was a brief moment where everything seemed to work correctly, then the game crashed.

MC Version: 1.17.1

[crash-2020-11-25_10.24.08-client.txt](https://github.com/comp500/Indium/files/6812497/crash-2020-11-25_10.24.08-client.txt)

**Comment by comp500** [comment]
Is that the right crash log? Optifine is not compatible with Sodium, Iris or Indium, and you don't seem to have Indium or Sodium installed.

**Comment by ExecuteOrd66** [comment]
Correct crash log. To be clear, I'm not using Optifine. I'm using Iris Shaders (a mod), which renders Optifine shader packs through sodium (If my understanding is correct).
[latest.log](https://github.com/comp500/Indium/files/6812580/latest.log)

**Comment by ExecuteOrd66** [comment]
My appologies. Lost the crash file.

**Comment by DragonEggBedrockBreaking** [comment]
> I'm using Iris Shaders (a mod), which renders Optifine shader packs through sodium (If my understanding is correct).

That is not correct. Iris is its own mod which allows you to use optifine shaders, and itself has nothing to do with sodium, it is simply *compatible with sodium*, which allows for greater performance than with optifine.
