### ISSUE TITLE
Game crashes when I load into a world

### ISSUE THREAD

**Issue by RuffleSteels** [comp500/Indium#71]
I have those mods and the ones causing the crash are the iris fork of sodium and iris. They work perfectly fine on their own so i think it is a indium issue.
![image](https://user-images.githubusercontent.com/77123399/126043579-744b96a1-95cd-4702-abc8-bad49e30ac1b.png)
[crash_report.txt](https://github.com/comp500/Indium/files/6834981/crash_report.txt

**Comment by comp500** [comment]
The version of Sodium you are using is outdated. Either find the corresponding Indium commit (if one exists) for your version of Sodium, or use the latest version of Sodium. As no official release has been made of Sodium in 1.17, I can't make any guarantees of compatibility between arbitrary versions of Sodium and Indium.
