### ISSUE TITLE
Game loads world and crashes (only happens when indium is installed)

### ISSUE THREAD

**Issue by PaPeedy** [comp500/Indium#73]
This is on the latest 1.17 version. Here is the crash report:
[crash-2021-07-18_08.34.28-client.txt](https://github.com/comp500/Indium/files/6836524/crash-2021-07-18_08.34.28-client.txt)

**Comment by comp500** [comment]
The version of Sodium you are using is outdated. Either find the corresponding Indium commit (if one exists) for your version of Sodium, or use the latest version of Sodium. I can't make any guarantees of compatibility between arbitrary development versions of Sodium and Indium.
