### ISSUE TITLE
[1.17.1] Crash with Latest Sodium Release for 1.17.1 (Tesselating Block in World)

### ISSUE THREAD

**Issue by Desempregago** [comp500/Indium#74]
![image](https://user-images.githubusercontent.com/14002834/126078501-2acc718a-a825-4c7e-8611-317a83523c86.png)

Sodium 0.3.0-build.5 (latest release from CaffeineMC/Modrinth)
Indium from commit 820073e
[Full Crash Report](https://pastebin.com/dJgtUDW6)

**Comment by Desempregago** [comment]
Happened while placing Kibe's Drawbridge block in world

**Comment by comp500** [comment]
You're using an outdated version of Indium, please update.

**Comment by Desempregago** [comment]
Yeah, I saw the changes and I think they might not have been fixed, I'll need to test

**Comment by Desempregago** [comment]
They were fixed. Sorry for taking your time.
