### ISSUE TITLE
Can't work with Iris

### ISSUE THREAD

**Issue by ccicnce113424** [comp500/Indium#76]
The Minecraft version is 1.17.1, and the Sodium version is 0.3.0+IRIS1-rev.7491e3a When [EBE](https://modrinth.com/mod/ebe) was using the Indigo API to render a box, a crash occurred.
[crash-2021-07-21_18.49.31-client.txt](https://github.com/comp500/Indium/files/6855026/crash-2021-07-21_18.49.31-client.txt)
Iris needs a customized version of Sodium, which may be the cause of the crash.

**Comment by Josh-Hagan-77** [comment]
have u got a version of indium for 1.17 and not 1.17.1 ?? ive been looking for a file for ages and cant find one?

**Comment by comp500** [comment]
@ccicnce113424 The version of Sodium that Iris uses is outdated, please use the Indium build pinned in the Iris discord.
@Josh-Hagan-77 Indium for 1.17.1 will run on 1.17 as well, though I suggest you update to 1.17.1.

**Comment by IMS212** [comment]
This will be fixed with the next version of Iris, which should release soon.
