### ISSUE TITLE
Crash while loading this and other mods.

### ISSUE THREAD

**Issue by FredTheNerd** [comp500/Indium#77]
Game crash on rendering a world. Log had "Unreported exception thrown!
java.util.concurrent.CompletionException: net.minecraft.class_148: Tesselating block in world - Indium Renderer"
any insight would be much appreciated :D

edit: removed latest.log. if people want it i can share parts of it but it has my full name in it

using 11 other mods:
clear-skies-mc117-1.5.69
fabric-api-0.37.1+1.17
indium-1.0.0+mc1.17.1
iris-mc1.17-1.1.0
krypton-0.1.4
lambdabettergrass-1.2.0+1.17
lambdynamiclights-2.0.1+1.17
lazydfu-0.1.2
lithium-fabric-mc1.17.1-0.7.3
modmenu-2.0.3
sodium-fabric-mc1.17-0.3.0+IRIS1-rev.7491e3a
starlight-1.0.0-RC3+fabric.1.17.x

**Comment by comp500** [comment]
See #76.
