### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Yird1** [comp500/Indium#8]
The url "https://jitpack.io/com/github/jellysquid3/sodium-fabric/1.16.x~next-SNAPSHOT/maven-metadata.xml" never responds leading to the build failing to get necessary file.

Screenshot:
![Capture](https://user-images.githubusercontent.com/67247581/105551614-bdeb0a00-5cb7-11eb-927a-fa7fa21c5cfd.PNG)
 
Putting the url in a browser doesnt work either:
![image](https://user-images.githubusercontent.com/67247581/105552359-a52f2400-5cb8-11eb-821b-983e60fada78.png)

**Comment by comp500** [comment]
Seems like jitpack is having issues... for now, you can just grab a precompiled jar from https://github.com/comp500/Indium/runs/1743990522

If you need to compile it yourself, you'll probably have to add a maven local publishing task to Sodium, then run it and set Indium to compile using that as a dependency.

**Comment by Yird1** [comment]
I think I'll just use the precompiled jar, since im no expert. By the way thanks for the jar, other than that I have no idea whats going on with jitpack.

**Comment by Yird1** [comment]
I didn't even know the "Actions" tab existed, guess I learned something new today.

**Comment by comp500** [comment]
Jitpack seems to be back up :)
