### ISSUE TITLE
[question] Indium is working very well with Iris (which has Sodium included) so why not publishing on CurseForge?

### ISSUE THREAD

**Issue by MSandro** [comp500/Indium#82]
I think the title says enough. In any case, I get questions about why Sodium and Indium are not included in my modpack. But I can only follow this suggestions as soon as Indium has been published on CurseForge.

**Comment by MSandro** [comment]
When will the new version with the fix be released? I hope very soon.

**Comment by MenacingPerson** [comment]
this is because a compatible version of sodium itself is not present on CF.

**Comment by comp500** [comment]
See https://github.com/comp500/Indium#curseforge
