### ISSUE TITLE
CF Rejection

### ISSUE THREAD

**Issue by LiviiYS** [comp500/Indium#84]
I am unable to upload my modpack with indium included due to the mod having a Curseforge page.

Any chance of an upload or removal of the page?

If unable that's OK.

**Comment by comp500** [comment]
Wouldn't you get the same issue from Sodium having a CurseForge page? See https://github.com/comp500/Indium#curseforge

**Comment by LiviiYS** [comment]
Sodium doesn't get flagged

![CF](https://user-images.githubusercontent.com/72738254/131364017-dcc13c0f-b8cf-4186-8d37-e758c4631994.PNG)

**Comment by comp500** [comment]
The release builds of Indium were never uploaded to CurseForge, only an older development build. Make sure you're using the release files from https://modrinth.com/mod/indium or https://github.com/comp500/Indium/releases - these are different from the file that was uploaded to CurseForge.

**Comment by LiviiYS** [comment]
Tried a build from both GitHub and modrinth with no luck.

Must be a curseforge issue

**Comment by LiviiYS** [comment]
They said to contact them

But I could probs just wait until you upload a build at some point in the future.
