### ISSUE TITLE
Support Sodium 0.3.2

### ISSUE THREAD

**Issue by bxvcd-732** [comp500/Indium#86]
Sodium has released 0.3.2 version, and I want to use it with this mod. Can you update this mod to support Sodium 0.3.2?

**Comment by DragonEggBedrockBreaking** [comment]
this mod already supports sodium 0.3.2

**Comment by bxvcd-732** [comment]
Oh, thank you! I thought it would not support that version because it's said that it's supporting 0.3.0. Sorry!
