### ISSUE TITLE
Freezing on startup

### ISSUE THREAD

**Issue by Huwng** [comp500/Indium#87]
Indium is making the game freeze when the game is trying to reload ResourceManager
Happens with both the newest release of Sodium and Iris from Modrinth
Log file: https://paste.ee/p/tW5UA (Indium + Iris, it also includes my laptop specs if it matters, Indium + Sodium would freeze at that stage also)

**Comment by comp500** [comment]
Are you sure the freeze does not occur when Indium is not present? I don't think Indium would cause this.

**Comment by Huwng** [comment]
Did more testing. Figured out that the issue was on my end, sorry for wasting anyone's time with this issue. Closing.
