### ISSUE TITLE
Add support to sodium 0.4

### ISSUE THREAD

**Issue by andreasdc** [comp500/Indium#88]
Sodium has experimental version (https://github.com/CaffeineMC/sodium-fabric/tree/1.17.x/0.4-experiments) which a lot of people are using, can you update Indium to it? Thanks! :) Great mod!

**Comment by DragonEggBedrockBreaking** [comment]
Sodium 0.4 has support for the Fabric Rendering API inside it already. You should already be able to use FRAPI mods with it

**Comment by andreasdc** [comment]
> Sodium 0.4 has support for the Fabric Rendering API inside it already. You should already be able to use FRAPI mods with it

So indium is not required?

**Comment by andreasdc** [comment]
Oh yea I see connected block textures works, rip Indium :( but cool feature in sodium
