### ISSUE TITLE
Game crash with REI 1.17.1

### ISSUE THREAD

**Issue by cursinorock** [comp500/Indium#89]
The game crash with Indium when a player uses REI or Creative tab to search any item, if you just use the REI arrow to find a item its work just fine.
Without Indium, REI and Creative tab search, works.
[crash-2021-10-03_09.13.18-client.txt](https://github.com/comp500/Indium/files/7273382/crash-2021-10-03_09.13.18-client.txt)

**Comment by comp500** [comment]
https://github.com/Parzivail-Modding-Team/GalaxiesParzisStarWarsMod/issues/51 seems to be the same issue and is fixed in the latest version of PSWG.
