### ISSUE TITLE
Crash when loading world with the newest version of sodium 

### ISSUE THREAD

**Issue by Vapaman** [comp500/Indium#92]
Minecraft 1.17.1
Java 16.0.1 64-bit
Sodium version: 0.3.3 build 8
Indium version: 1.0.0
Crash happened when trying to load a world.
Crash log: [crash-2021-11-23_19.04.41-client.txt](https://github.com/comp500/Indium/files/7589840/crash-2021-11-23_19.04.41-client.txt)

I also experienced crashes before updating sodium.

**Comment by Vapaman** [comment]
Fabric API version: 0.42.1

**Comment by Vapaman** [comment]
My bad there seems to be a PR already in works, should I keep the issue open for other users to see?

**Comment by comp500** [comment]
Updated, please use Indium 1.0.1.
