### ISSUE TITLE
Should modify misleading info on sodium 0.4-exp

### ISSUE THREAD

**Issue by KagefumiMerry** [comp500/Indium#94]
"Will it be merged into Sodium?" section is a bit outdated since current 0.4.0 alpha 4 is still no support FRApi.

In fact, sodium 0.4.0 is literally a port of 0.3.3 to 1.18. nothing related to 0.4-Exp branch.

https://media.discordapp.net/attachments/912720354596761640/914145486288605224/sconosciuto.jpeg

because the above issues making other mods a bit hard to explain why we still need Indium for current sodium 0.4 version.
https://github.com/PepperCode1/Continuity/issues/27

**Comment by comp500** [comment]
The branch is still called "0.4-experiments"; I don't consider this to be misleading since it is still the name of the experimental branch that contains the FRAPI/FREX changes. Do let me know if the branch is renamed and I will update the README.
