### ISSUE TITLE
Fabric missing even though it is installed.

### ISSUE THREAD

**Issue by lucasfolino** [comp500/Indium#96]
Some mods are not working with the latest version of fabric.  Indium is one of them.  I am able to use terralith, sodium, and iris.  I have tried adding continuity and Indium and receive this error.   I do have fabric installed and like I said it does work with other mods.  I am running MC 1.18.

net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
	 - Install fabric-renderer-api-v1, version 0.3.0 or later.
Unmet dependency listing:
	 - Mod 'Continuity' (continuity) 1.0.3+1.18 requires any version of fabric, which is missing!
	 - Mod 'Indium' (indium) 1.0.2-alpha1+mc1.18 requires version 0.3.0 or later of fabric-renderer-api-v1, which is missing!
Inactive mods:
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
	 - Install fabric-renderer-api-v1, version 0.3.0 or later.
Unmet dependency listing:
	 - Mod 'Continuity' (continuity) 1.0.3+1.18 requires any version of fabric, which is missing!
	 - Mod 'Indium' (indium) 1.0.2-alpha1+mc1.18 requires version 0.3.0 or later of fabric-renderer-api-v1, which is missing!
Inactive mods:
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186)
	... 3 more
![fabric_missing](https://user-images.githubusercontent.com/27779366/145477585-d918a84a-35bc-42ad-9eb1-c49a544c31a6.png)

**Comment by lucasfolino** [comment]
So I am dumb.  I am new to fabric.  Been using forge and optifine, but wanted to try fabric and some of its mods.  I didn't realize that fabric loader and fabric API are separate.  I added the actual API to the mod folder and this fixed it.  It is a little confusing that both are referred to as fabric.  Terralith worked so I guess it only needed the loader and not the API.  Or is this wrong because there is a .fabric folder in the minecraft folder near mods.  Do I not need the mod file in the mod folder or should the fabric loader jar file install this?
![fabric_missing2](https://user-images.githubusercontent.com/27779366/145478844-898d0bcb-a413-43a2-840b-782c65f6b9a8.png)

**Comment by comp500** [comment]
Yes, that's correct. You do need the API in the mods folder; the `.fabric` folder is for Fabric loader only.
