### ISSUE TITLE
Implement FREX 6.x

### ISSUE THREAD

**Issue by AlisterGontineac** [comp500/Indium#97]
at startup

https://crashy.net/csoaoLA8NK7tcw3Q51GE

https://crashy.net/NqDeiOLhXKhC51sKnYyW?raw

**Comment by comp500** [comment]
It seems that FREX 6.x is incompatible with other implementations of the Fabric Rendering API. I've asked Grondag about this, now waiting for a response.

**Comment by coderbot16** [comment]
It seems like for Indium to work with FREX 6, it would have to implement the (admittedly significantly simplified) renderer API in FREX 6 and then not offer a FRAPI rendering plugin in favor of letting FREX do so. FREX 6 seems to be intended to supersede the Fabric Rendering API.

**Comment by comp500** [comment]
Ah yeah, that makes sense. I might look into it, but I have plenty of other projects to work on currently so it may not be terribly soon.

**Comment by AmonRay** [comment]
https://github.com/spiralhalo/plumbum

**Comment by comp500** [comment]
Closing this: Indium is now deprecated in favour of Sodium's FRAPI support.
