### ISSUE TITLE
Industrial Revolution Missing Textures

### ISSUE THREAD

**Issue by DavidBolko** [comp500/Indium#99]
Hello, I installed Sodium, Indium and Industrial Revolution and Industrial Revolution has some missing textures, i didn't find any issues on the Internet so that's why i'm opening this Issue...

Minecraft Version - 1.17.1
Indium, Sodium Version - Latest

**Comment by comp500** [comment]
Do the textures work without Sodium+Indium? Which textures are broken specifically?

**Comment by DavidBolko** [comment]
I meant the electrolytic separator and jetpack for example but i just tested it again and it is broken even without Sodium and Indium so they are probably broken and disabled in the IR mod itself...

I'm sorry, I was just thinking that it is strange and i didn't checked it without the Sodium first before i opened this Issue...
